/* mainwindow.c generated by valac, the Vala compiler
 * generated from mainwindow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include </home/pontus/Vala/roxenlauncher/config.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <gee.h>
#include <gdk/gdk.h>


#define ROXENLAUNCHER_TYPE_MAIN_WINDOW (roxenlauncher_main_window_get_type ())
#define ROXENLAUNCHER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindow))
#define ROXENLAUNCHER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowClass))
#define ROXENLAUNCHER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW))
#define ROXENLAUNCHER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_MAIN_WINDOW))
#define ROXENLAUNCHER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowClass))

typedef struct _RoxenlauncherMainWindow RoxenlauncherMainWindow;
typedef struct _RoxenlauncherMainWindowClass RoxenlauncherMainWindowClass;
typedef struct _RoxenlauncherMainWindowPrivate RoxenlauncherMainWindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_LAUNCHER_FILE (launcher_file_get_type ())
#define LAUNCHER_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LAUNCHER_FILE, LauncherFile))
#define LAUNCHER_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LAUNCHER_FILE, LauncherFileClass))
#define IS_LAUNCHER_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LAUNCHER_FILE))
#define IS_LAUNCHER_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LAUNCHER_FILE))
#define LAUNCHER_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LAUNCHER_FILE, LauncherFileClass))

typedef struct _LauncherFile LauncherFile;
typedef struct _LauncherFileClass LauncherFileClass;

#define ROXENLAUNCHER_TYPE_DATE_TIME (roxenlauncher_date_time_get_type ())
#define ROXENLAUNCHER_DATE_TIME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTime))
#define ROXENLAUNCHER_DATE_TIME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTimeClass))
#define ROXENLAUNCHER_IS_DATE_TIME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_DATE_TIME))
#define ROXENLAUNCHER_IS_DATE_TIME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_DATE_TIME))
#define ROXENLAUNCHER_DATE_TIME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTimeClass))

typedef struct _RoxenlauncherDateTime RoxenlauncherDateTime;
typedef struct _RoxenlauncherDateTimeClass RoxenlauncherDateTimeClass;

#define ROXENLAUNCHER_TYPE_APPLICATION (roxenlauncher_application_get_type ())
#define ROXENLAUNCHER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplication))
#define ROXENLAUNCHER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))
#define ROXENLAUNCHER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))

typedef struct _RoxenlauncherApplication RoxenlauncherApplication;
typedef struct _RoxenlauncherApplicationClass RoxenlauncherApplicationClass;

#define ROXENLAUNCHER_TYPE_APPLICATION_FORM (roxenlauncher_application_form_get_type ())
#define ROXENLAUNCHER_APPLICATION_FORM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_APPLICATION_FORM, RoxenlauncherApplicationForm))
#define ROXENLAUNCHER_APPLICATION_FORM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_APPLICATION_FORM, RoxenlauncherApplicationFormClass))
#define ROXENLAUNCHER_IS_APPLICATION_FORM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_APPLICATION_FORM))
#define ROXENLAUNCHER_IS_APPLICATION_FORM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_APPLICATION_FORM))
#define ROXENLAUNCHER_APPLICATION_FORM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_APPLICATION_FORM, RoxenlauncherApplicationFormClass))

typedef struct _RoxenlauncherApplicationForm RoxenlauncherApplicationForm;
typedef struct _RoxenlauncherApplicationFormClass RoxenlauncherApplicationFormClass;
typedef struct _Block2Data Block2Data;

struct _RoxenlauncherMainWindow {
	GObject parent_instance;
	RoxenlauncherMainWindowPrivate * priv;
};

struct _RoxenlauncherMainWindowClass {
	GObjectClass parent_class;
};

struct _RoxenlauncherMainWindowPrivate {
	GtkBuilder* builder;
	GtkWindow* win;
	GtkScrolledWindow* sw_files;
	GtkCheckButton* cb_logging;
	GtkFileChooserButton* fc_logfile;
	GtkButton* btn_edit_file;
	GtkButton* btn_finish_file;
	GtkButton* btn_finish_all;
	GtkButton* btn_edit_app;
	GtkButton* btn_add_app;
	GtkButton* btn_remove_app;
	GtkTreeView* tv_files;
	GtkTreeView* tv_apps;
	GtkListStore* ls_files;
	GtkListStore* ls_apps;
	GtkStatusbar* statusbar;
};

struct _Block2Data {
	int _ref_count_;
	RoxenlauncherMainWindow * self;
	LauncherFile* lf;
	char* status;
};


static gpointer roxenlauncher_main_window_parent_class = NULL;

GType roxenlauncher_main_window_get_type (void);
#define ROXENLAUNCHER_MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowPrivate))
enum  {
	ROXENLAUNCHER_MAIN_WINDOW_DUMMY_PROPERTY
};
#define ROXENLAUNCHER_APP_UI_PATH "gui:" DATADIR "/roxenlauncher/ui"
#define ROXENLAUNCHER_APP_MAIN_UI_FILENAME "mainwindow.ui"
static GObject* roxenlauncher_main_window_gtkobj (RoxenlauncherMainWindow* self, const char* name);
static void roxenlauncher_main_window_on_window_destroy (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_window_destroy_gtk_object_destroy (GtkWindow* _sender, gpointer self);
static void _lambda2_ (RoxenlauncherMainWindow* self);
static void __lambda2__gtk_toggle_button_toggled (GtkCheckButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_finish_file_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_finish_file_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_finish_all_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_finish_all_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _roxenlauncher_main_window_on_window_destroy_gtk_menu_item_activate (GtkImageMenuItem* _sender, gpointer self);
static void roxenlauncher_main_window_on_tv_files_activated (RoxenlauncherMainWindow* self, GtkTreePath* path, GtkTreeViewColumn* col);
static void _roxenlauncher_main_window_on_tv_files_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
GType launcher_file_get_type (void);
GeeArrayList* launcher_file_get_files (void);
gint launcher_file_get_status (LauncherFile* self);
GType roxenlauncher_date_time_get_type (void);
RoxenlauncherDateTime* launcher_file_get_last_upload (LauncherFile* self);
char* roxenlauncher_date_time_to_string (RoxenlauncherDateTime* self);
char* launcher_file_get_uri (LauncherFile* self);
char* launcher_file_status_as_string (LauncherFile* self);
static void roxenlauncher_main_window_set_file_count (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_on_tv_files_selection_changed (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_tv_files_selection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self);
static gboolean roxenlauncher_main_window_on_tv_files_key_release_event (RoxenlauncherMainWindow* self, GtkWidget* source, GdkEventKey* key);
static gboolean _roxenlauncher_main_window_on_tv_files_key_release_event_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
GType roxenlauncher_application_get_type (void);
GeeArrayList* roxenlauncher_application_get_applications (void);
const char* roxenlauncher_application_get_mimetype (RoxenlauncherApplication* self);
const char* roxenlauncher_application_get_name (RoxenlauncherApplication* self);
static void roxenlauncher_main_window_on_tv_apps_activated (RoxenlauncherMainWindow* self, GtkTreePath* path, GtkTreeViewColumn* col);
static void _roxenlauncher_main_window_on_tv_apps_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
static void roxenlauncher_main_window_on_tv_apps_selection_changed (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_tv_apps_selection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self);
RoxenlauncherApplication* roxenlauncher_main_window_editor_dialog_new (RoxenlauncherMainWindow* self, const char* content_type);
static void _lambda8_ (RoxenlauncherMainWindow* self);
static void __lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_edit_app_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_edit_app_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_remove_app_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_remove_app_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static gboolean roxenlauncher_main_window_on_tv_apps_key_release_event (RoxenlauncherMainWindow* self, GtkWidget* source, GdkEventKey* key);
static gboolean _roxenlauncher_main_window_on_tv_apps_key_release_event_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
void roxenlauncher_main_window_init (RoxenlauncherMainWindow* self);
RoxenlauncherApplicationForm* roxenlauncher_application_form_new (void);
RoxenlauncherApplicationForm* roxenlauncher_application_form_construct (GType object_type);
GType roxenlauncher_application_form_get_type (void);
void roxenlauncher_application_form_set_content_type (RoxenlauncherApplicationForm* self, const char* value);
void roxenlauncher_application_form_run (RoxenlauncherApplicationForm* self);
gboolean roxenlauncher_application_form_get_response (RoxenlauncherApplicationForm* self);
const char* roxenlauncher_application_form_get_editor_name (RoxenlauncherApplicationForm* self);
const char* roxenlauncher_application_form_get_editor_command (RoxenlauncherApplicationForm* self);
const char* roxenlauncher_application_form_get_content_type (RoxenlauncherApplicationForm* self);
const char* roxenlauncher_application_form_get_editor_arguments (RoxenlauncherApplicationForm* self);
RoxenlauncherApplication* roxenlauncher_application_new (const char* name, const char* command, const char* mimetype, const char* arguments);
RoxenlauncherApplication* roxenlauncher_application_construct (GType object_type, const char* name, const char* command, const char* mimetype, const char* arguments);
void roxenlauncher_application_add_application (RoxenlauncherApplication* app);
static RoxenlauncherApplication* roxenlauncher_main_window_get_selected_application (RoxenlauncherMainWindow* self, GtkTreeModel** _model, GtkTreeIter* _iter);
void roxenlauncher_application_form_set_editor_name (RoxenlauncherApplicationForm* self, const char* value);
const char* roxenlauncher_application_get_command (RoxenlauncherApplication* self);
void roxenlauncher_application_form_set_editor_command (RoxenlauncherApplicationForm* self, const char* value);
const char* roxenlauncher_application_get_arguments (RoxenlauncherApplication* self);
void roxenlauncher_application_form_set_editor_arguments (RoxenlauncherApplicationForm* self, const char* value);
void roxenlauncher_application_set_mimetype (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_name (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_command (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_arguments (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_save_list (void);
void roxenlauncher_main_window_editor_dialog_edit (RoxenlauncherMainWindow* self);
const char* launcher_file_get_id (LauncherFile* self);
static gboolean _lambda4_ (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, Block2Data* _data2_);
static gboolean __lambda4__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static Block2Data* block2_data_unref (Block2Data* _data2_);
void roxenlauncher_main_window_set_file_status (RoxenlauncherMainWindow* self, LauncherFile* lf, const char* status);
static void roxenlauncher_main_window_remove_application (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_finish_file (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_finish_all_files (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_set_app_buttons_sensitivity (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_set_buttons_sensitivity (RoxenlauncherMainWindow* self);
static LauncherFile* roxenlauncher_main_window_get_selected_file (RoxenlauncherMainWindow* self, GtkTreeModel** _model, GtkTreeIter* _iter);
void launcher_file_download (LauncherFile* self, gboolean do_launch_editor);
gboolean roxenlauncher_alert_confirm (GtkWindow* parent, const char* message);
gboolean launcher_file_delete (LauncherFile* self);
void launcher_file_remove_file (LauncherFile* file);
void launcher_file_clear_files (void);
RoxenlauncherApplication* launcher_file_get_application (LauncherFile* self);
void launcher_file_unset_application (LauncherFile* self);
void roxenlauncher_application_remove_application (RoxenlauncherApplication* app);
static void roxenlauncher_main_window_set_status (RoxenlauncherMainWindow* self, const char* text);
RoxenlauncherMainWindow* roxenlauncher_main_window_new (void);
RoxenlauncherMainWindow* roxenlauncher_main_window_construct (GType object_type);
static void roxenlauncher_main_window_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);
static int _vala_strcmp0 (const char * str1, const char * str2);



static void _roxenlauncher_main_window_on_window_destroy_gtk_object_destroy (GtkWindow* _sender, gpointer self) {
	roxenlauncher_main_window_on_window_destroy (self);
}


static void _lambda2_ (RoxenlauncherMainWindow* self) {
	g_object_set ((GtkWidget*) self->priv->fc_logfile, "sensitive", gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->cb_logging), NULL);
}


static void __lambda2__gtk_toggle_button_toggled (GtkCheckButton* _sender, gpointer self) {
	_lambda2_ (self);
}


static void _roxenlauncher_main_window_on_btn_finish_file_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_finish_file_clicked (self);
}


static void _roxenlauncher_main_window_on_btn_finish_all_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_finish_all_clicked (self);
}


static void _roxenlauncher_main_window_on_window_destroy_gtk_menu_item_activate (GtkImageMenuItem* _sender, gpointer self) {
	roxenlauncher_main_window_on_window_destroy (self);
}


static void _roxenlauncher_main_window_on_tv_files_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
	roxenlauncher_main_window_on_tv_files_activated (self, path, column);
}


static void _roxenlauncher_main_window_on_tv_files_selection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self) {
	roxenlauncher_main_window_on_tv_files_selection_changed (self);
}


static gboolean _roxenlauncher_main_window_on_tv_files_key_release_event_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	return roxenlauncher_main_window_on_tv_files_key_release_event (self, _sender, event);
}


static void _roxenlauncher_main_window_on_tv_apps_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
	roxenlauncher_main_window_on_tv_apps_activated (self, path, column);
}


static void _roxenlauncher_main_window_on_tv_apps_selection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self) {
	roxenlauncher_main_window_on_tv_apps_selection_changed (self);
}


static void _lambda8_ (RoxenlauncherMainWindow* self) {
	RoxenlauncherApplication* _tmp0_;
	_tmp0_ = roxenlauncher_main_window_editor_dialog_new (self, "");
	_g_object_unref0 (_tmp0_);
}


static void __lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	_lambda8_ (self);
}


static void _roxenlauncher_main_window_on_btn_edit_app_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_edit_app_clicked (self);
}


static void _roxenlauncher_main_window_on_btn_remove_app_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_remove_app_clicked (self);
}


static gboolean _roxenlauncher_main_window_on_tv_apps_key_release_event_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	return roxenlauncher_main_window_on_tv_apps_key_release_event (self, _sender, event);
}


void roxenlauncher_main_window_init (RoxenlauncherMainWindow* self) {
	GError * _inner_error_;
	GtkBuilder* _tmp0_;
	gboolean gui_loaded;
	char** _tmp2_;
	gint ui_paths_size;
	gint ui_paths_length1;
	char** _tmp1_;
	char** ui_paths;
	GtkWindow* _tmp6_;
	GtkScrolledWindow* _tmp7_;
	GtkFileChooserButton* _tmp8_;
	GtkCheckButton* _tmp9_;
	GtkButton* _tmp10_;
	GtkButton* _tmp11_;
	GtkButton* _tmp12_;
	GtkButton* _tmp13_;
	GtkButton* _tmp14_;
	GtkButton* _tmp15_;
	GtkTreeView* _tmp16_;
	GtkListStore* _tmp17_;
	GtkTreeView* _tmp18_;
	GtkListStore* _tmp19_;
	GtkStatusbar* _tmp20_;
	GtkImageMenuItem* _tmp21_;
	GtkListStore* _tmp22_;
	char** _tmp24_;
	gint cols_size;
	gint cols_length1;
	char** _tmp23_ = NULL;
	char** cols;
	GeeArrayList* _tmp31_;
	gboolean _tmp32_;
	GtkListStore* _tmp33_;
	char** _tmp35_;
	char** _tmp34_ = NULL;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	self->priv->builder = (_tmp0_ = gtk_builder_new (), _g_object_unref0 (self->priv->builder), _tmp0_);
	gui_loaded = FALSE;
	g_message ("mainwindow.vala:38: UI PATH: %s", ROXENLAUNCHER_APP_UI_PATH);
	ui_paths = (_tmp2_ = _tmp1_ = g_strsplit (ROXENLAUNCHER_APP_UI_PATH, ":", 8), ui_paths_length1 = _vala_array_length (_tmp1_), ui_paths_size = ui_paths_length1, _tmp2_);
	{
		char** path_collection;
		int path_collection_length1;
		int path_it;
		path_collection = ui_paths;
		path_collection_length1 = ui_paths_length1;
		for (path_it = 0; path_it < ui_paths_length1; path_it = path_it + 1) {
			char* path;
			path = g_strdup (path_collection[path_it]);
			{
				char* _tmp3_;
				char* _tmp4_;
				char* filename;
				filename = (_tmp4_ = g_strconcat (_tmp3_ = g_strconcat (path, "/", NULL), ROXENLAUNCHER_APP_MAIN_UI_FILENAME, NULL), _g_free0 (_tmp3_), _tmp4_);
				if (!g_str_has_prefix (filename, "/")) {
					char* _tmp5_;
					filename = (_tmp5_ = g_strconcat ("/home/pontus/Vala/roxenlauncher/src/", filename, NULL), _g_free0 (filename), _tmp5_);
				}
				g_message ("mainwindow.vala:48: UI file name: %s", filename);
				if (g_file_test (filename, G_FILE_TEST_EXISTS)) {
					{
						gtk_builder_set_translation_domain (self->priv->builder, "roxenlauncher");
						gtk_builder_add_from_file (self->priv->builder, filename, &_inner_error_);
						if (_inner_error_ != NULL) {
							goto __catch15_g_error;
							goto __finally15;
						}
						gui_loaded = TRUE;
					}
					goto __finally15;
					__catch15_g_error:
					{
						GError * e;
						e = _inner_error_;
						_inner_error_ = NULL;
						{
							g_warning ("mainwindow.vala:56: GUI load error: %s", e->message);
							_g_error_free0 (e);
						}
					}
					__finally15:
					if (_inner_error_ != NULL) {
						_g_free0 (path);
						_g_free0 (filename);
						ui_paths = (_vala_array_free (ui_paths, ui_paths_length1, (GDestroyNotify) g_free), NULL);
						g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
						g_clear_error (&_inner_error_);
						return;
					}
				}
				_g_free0 (path);
				_g_free0 (filename);
			}
		}
	}
	if (!gui_loaded) {
		g_error ("mainwindow.vala:62: Unable to load GUI for main window");
	}
	gtk_builder_connect_signals (self->priv->builder, self);
	self->priv->win = (_tmp6_ = GTK_WINDOW (roxenlauncher_main_window_gtkobj (self, "mainwindow")), _g_object_unref0 (self->priv->win), _tmp6_);
	self->priv->sw_files = (_tmp7_ = GTK_SCROLLED_WINDOW (roxenlauncher_main_window_gtkobj (self, "sw_files")), _g_object_unref0 (self->priv->sw_files), _tmp7_);
	self->priv->fc_logfile = (_tmp8_ = GTK_FILE_CHOOSER_BUTTON (roxenlauncher_main_window_gtkobj (self, "fc_logfile")), _g_object_unref0 (self->priv->fc_logfile), _tmp8_);
	self->priv->cb_logging = (_tmp9_ = GTK_CHECK_BUTTON (roxenlauncher_main_window_gtkobj (self, "cb_logging")), _g_object_unref0 (self->priv->cb_logging), _tmp9_);
	self->priv->btn_edit_file = (_tmp10_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_edit_file")), _g_object_unref0 (self->priv->btn_edit_file), _tmp10_);
	self->priv->btn_finish_file = (_tmp11_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_finish_file")), _g_object_unref0 (self->priv->btn_finish_file), _tmp11_);
	self->priv->btn_finish_all = (_tmp12_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_finish_all")), _g_object_unref0 (self->priv->btn_finish_all), _tmp12_);
	self->priv->btn_edit_app = (_tmp13_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_edit_app")), _g_object_unref0 (self->priv->btn_edit_app), _tmp13_);
	self->priv->btn_add_app = (_tmp14_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_add_app")), _g_object_unref0 (self->priv->btn_add_app), _tmp14_);
	self->priv->btn_remove_app = (_tmp15_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_remove_app")), _g_object_unref0 (self->priv->btn_remove_app), _tmp15_);
	self->priv->tv_files = (_tmp16_ = GTK_TREE_VIEW (roxenlauncher_main_window_gtkobj (self, "tv_files")), _g_object_unref0 (self->priv->tv_files), _tmp16_);
	self->priv->ls_files = (_tmp17_ = GTK_LIST_STORE (roxenlauncher_main_window_gtkobj (self, "ls_files")), _g_object_unref0 (self->priv->ls_files), _tmp17_);
	self->priv->tv_apps = (_tmp18_ = GTK_TREE_VIEW (roxenlauncher_main_window_gtkobj (self, "tv_apps")), _g_object_unref0 (self->priv->tv_apps), _tmp18_);
	self->priv->ls_apps = (_tmp19_ = GTK_LIST_STORE (roxenlauncher_main_window_gtkobj (self, "ls_apps")), _g_object_unref0 (self->priv->ls_apps), _tmp19_);
	self->priv->statusbar = (_tmp20_ = GTK_STATUSBAR (roxenlauncher_main_window_gtkobj (self, "statusbar1")), _g_object_unref0 (self->priv->statusbar), _tmp20_);
	g_signal_connect_object ((GtkObject*) self->priv->win, "destroy", (GCallback) _roxenlauncher_main_window_on_window_destroy_gtk_object_destroy, self, 0);
	g_signal_connect_object ((GtkToggleButton*) self->priv->cb_logging, "toggled", (GCallback) __lambda2__gtk_toggle_button_toggled, self, 0);
	g_signal_connect_object (self->priv->btn_finish_file, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_finish_file_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btn_finish_all, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_finish_all_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object ((GtkMenuItem*) (_tmp21_ = GTK_IMAGE_MENU_ITEM (roxenlauncher_main_window_gtkobj (self, "im_quit"))), "activate", (GCallback) _roxenlauncher_main_window_on_window_destroy_gtk_menu_item_activate, self, 0);
	_g_object_unref0 (_tmp21_);
	g_signal_connect_object (self->priv->tv_files, "row-activated", (GCallback) _roxenlauncher_main_window_on_tv_files_activated_gtk_tree_view_row_activated, self, 0);
	self->priv->ls_files = (_tmp22_ = gtk_list_store_new (4, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, TYPE_LAUNCHER_FILE, NULL), _g_object_unref0 (self->priv->ls_files), _tmp22_);
	gtk_tree_view_set_model (self->priv->tv_files, (GtkTreeModel*) self->priv->ls_files);
	cols = (_tmp24_ = (_tmp23_ = g_new0 (char*, 3 + 1), _tmp23_[0] = g_strdup ("File"), _tmp23_[1] = g_strdup ("Staus"), _tmp23_[2] = g_strdup ("Last upload"), _tmp23_), cols_length1 = 3, cols_size = cols_length1, _tmp24_);
	{
		gulong i;
		i = (gulong) 0;
		{
			gboolean _tmp25_;
			_tmp25_ = TRUE;
			while (TRUE) {
				GtkCellRendererText* ct;
				GtkTreeViewColumn* cl;
				if (!_tmp25_) {
					i++;
				}
				_tmp25_ = FALSE;
				if (!(i < cols_length1)) {
					break;
				}
				ct = g_object_ref_sink ((GtkCellRendererText*) gtk_cell_renderer_text_new ());
				cl = g_object_ref_sink (gtk_tree_view_column_new_with_attributes (cols[i], (GtkCellRenderer*) ct, "text", i, NULL, NULL));
				gtk_tree_view_column_set_resizable (cl, TRUE);
				gtk_tree_view_column_set_expand (cl, TRUE);
				gtk_tree_view_insert_column (self->priv->tv_files, cl, -1);
				_g_object_unref0 (ct);
				_g_object_unref0 (cl);
			}
		}
	}
	{
		GeeArrayList* _tmp26_;
		GeeIterator* _tmp27_;
		GeeIterator* _lf_it;
		_lf_it = (_tmp27_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) (_tmp26_ = launcher_file_get_files ())), _g_object_unref0 (_tmp26_), _tmp27_);
		while (TRUE) {
			LauncherFile* lf;
			GtkTreeIter iter = {0};
			char* last_upload;
			char* _tmp30_;
			char* _tmp29_;
			if (!gee_iterator_next (_lf_it)) {
				break;
			}
			lf = (LauncherFile*) gee_iterator_get (_lf_it);
			gtk_list_store_append (self->priv->ls_files, &iter);
			last_upload = g_strdup ("");
			if (launcher_file_get_status (lf) == 0) {
				char* _tmp28_;
				last_upload = (_tmp28_ = roxenlauncher_date_time_to_string (launcher_file_get_last_upload (lf)), _g_free0 (last_upload), _tmp28_);
			}
			gtk_list_store_set (self->priv->ls_files, &iter, 0, _tmp29_ = launcher_file_get_uri (lf), 1, _tmp30_ = launcher_file_status_as_string (lf), 2, last_upload, 3, lf, -1, -1);
			_g_free0 (_tmp30_);
			_g_free0 (_tmp29_);
			_g_object_unref0 (lf);
			_g_free0 (last_upload);
		}
		_g_object_unref0 (_lf_it);
	}
	if ((_tmp32_ = gee_collection_get_size ((GeeCollection*) (_tmp31_ = launcher_file_get_files ())) > 0, _g_object_unref0 (_tmp31_), _tmp32_)) {
		g_object_set ((GtkWidget*) self->priv->btn_finish_all, "sensitive", TRUE, NULL);
	}
	roxenlauncher_main_window_set_file_count (self);
	g_signal_connect_object (gtk_tree_view_get_selection (self->priv->tv_files), "changed", (GCallback) _roxenlauncher_main_window_on_tv_files_selection_changed_gtk_tree_selection_changed, self, 0);
	g_signal_connect_object ((GtkWidget*) self->priv->tv_files, "key-release-event", (GCallback) _roxenlauncher_main_window_on_tv_files_key_release_event_gtk_widget_key_release_event, self, 0);
	self->priv->ls_apps = (_tmp33_ = gtk_list_store_new (3, G_TYPE_STRING, G_TYPE_STRING, ROXENLAUNCHER_TYPE_APPLICATION, NULL), _g_object_unref0 (self->priv->ls_apps), _tmp33_);
	gtk_tree_view_set_model (self->priv->tv_apps, (GtkTreeModel*) self->priv->ls_apps);
	cols = (_tmp35_ = (_tmp34_ = g_new0 (char*, 2 + 1), _tmp34_[0] = g_strdup ("Content type"), _tmp34_[1] = g_strdup ("Application"), _tmp34_), cols = (_vala_array_free (cols, cols_length1, (GDestroyNotify) g_free), NULL), cols_length1 = 2, cols_size = cols_length1, _tmp35_);
	{
		gulong i;
		i = (gulong) 0;
		{
			gboolean _tmp36_;
			_tmp36_ = TRUE;
			while (TRUE) {
				GtkCellRendererText* ct;
				GtkTreeViewColumn* cl;
				if (!_tmp36_) {
					i++;
				}
				_tmp36_ = FALSE;
				if (!(i < cols_length1)) {
					break;
				}
				ct = g_object_ref_sink ((GtkCellRendererText*) gtk_cell_renderer_text_new ());
				cl = g_object_ref_sink (gtk_tree_view_column_new_with_attributes (cols[i], (GtkCellRenderer*) ct, "text", i, NULL, NULL));
				gtk_tree_view_column_set_resizable (cl, TRUE);
				gtk_tree_view_insert_column (self->priv->tv_apps, cl, -1);
				_g_object_unref0 (ct);
				_g_object_unref0 (cl);
			}
		}
	}
	{
		GeeArrayList* _tmp37_;
		GeeIterator* _tmp38_;
		GeeIterator* _app_it;
		_app_it = (_tmp38_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) (_tmp37_ = roxenlauncher_application_get_applications ())), _g_object_unref0 (_tmp37_), _tmp38_);
		while (TRUE) {
			RoxenlauncherApplication* app;
			GtkTreeIter iter = {0};
			if (!gee_iterator_next (_app_it)) {
				break;
			}
			app = (RoxenlauncherApplication*) gee_iterator_get (_app_it);
			gtk_list_store_append (self->priv->ls_apps, &iter);
			gtk_list_store_set (self->priv->ls_apps, &iter, 0, roxenlauncher_application_get_mimetype (app), 1, roxenlauncher_application_get_name (app), 2, app, -1, -1);
			_g_object_unref0 (app);
		}
		_g_object_unref0 (_app_it);
	}
	g_signal_connect_object (self->priv->tv_apps, "row-activated", (GCallback) _roxenlauncher_main_window_on_tv_apps_activated_gtk_tree_view_row_activated, self, 0);
	g_signal_connect_object (gtk_tree_view_get_selection (self->priv->tv_apps), "changed", (GCallback) _roxenlauncher_main_window_on_tv_apps_selection_changed_gtk_tree_selection_changed, self, 0);
	g_signal_connect_object (self->priv->btn_add_app, "clicked", (GCallback) __lambda8__gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btn_edit_app, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_edit_app_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btn_remove_app, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_remove_app_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object ((GtkWidget*) self->priv->tv_apps, "key-release-event", (GCallback) _roxenlauncher_main_window_on_tv_apps_key_release_event_gtk_widget_key_release_event, self, 0);
	gtk_widget_show_all ((GtkWidget*) self->priv->win);
	ui_paths = (_vala_array_free (ui_paths, ui_paths_length1, (GDestroyNotify) g_free), NULL);
	cols = (_vala_array_free (cols, cols_length1, (GDestroyNotify) g_free), NULL);
}


RoxenlauncherApplication* roxenlauncher_main_window_editor_dialog_new (RoxenlauncherMainWindow* self, const char* content_type) {
	RoxenlauncherApplication* result;
	RoxenlauncherApplicationForm* d;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (content_type != NULL, NULL);
	g_message ("mainwindow.vala:177: OK");
	d = roxenlauncher_application_form_new ();
	roxenlauncher_application_form_set_content_type (d, content_type);
	g_message ("mainwindow.vala:181: Running dialog...");
	roxenlauncher_application_form_run (d);
	if (roxenlauncher_application_form_get_response (d)) {
		RoxenlauncherApplication* app;
		GtkTreeIter iter = {0};
		g_message ("mainwindow.vala:184: Ok, save...");
		app = roxenlauncher_application_new (roxenlauncher_application_form_get_editor_name (d), roxenlauncher_application_form_get_editor_command (d), roxenlauncher_application_form_get_content_type (d), roxenlauncher_application_form_get_editor_arguments (d));
		roxenlauncher_application_add_application (app);
		gtk_list_store_append (self->priv->ls_apps, &iter);
		gtk_list_store_set (self->priv->ls_apps, &iter, 0, roxenlauncher_application_get_mimetype (app), 1, roxenlauncher_application_get_name (app), 2, app, -1);
		result = app;
		_g_object_unref0 (d);
		return result;
	} else {
		g_message ("mainwindow.vala:195: Abort...");
	}
	result = NULL;
	_g_object_unref0 (d);
	return result;
}


void roxenlauncher_main_window_editor_dialog_edit (RoxenlauncherMainWindow* self) {
	GtkTreeModel* model;
	GtkTreeIter iter = {0};
	GtkTreeModel* _tmp2_;
	RoxenlauncherApplication* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	RoxenlauncherApplication* app;
	g_return_if_fail (self != NULL);
	model = NULL;
	app = (_tmp1_ = roxenlauncher_main_window_get_selected_application (self, &_tmp0_, &iter), model = (_tmp2_ = _tmp0_, _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (app != NULL) {
		RoxenlauncherApplicationForm* d;
		d = roxenlauncher_application_form_new ();
		roxenlauncher_application_form_set_content_type (d, roxenlauncher_application_get_mimetype (app));
		roxenlauncher_application_form_set_editor_name (d, roxenlauncher_application_get_name (app));
		roxenlauncher_application_form_set_editor_command (d, roxenlauncher_application_get_command (app));
		roxenlauncher_application_form_set_editor_arguments (d, roxenlauncher_application_get_arguments (app));
		roxenlauncher_application_form_run (d);
		if (roxenlauncher_application_form_get_response (d)) {
			g_message ("mainwindow.vala:218: Ok update ...");
			roxenlauncher_application_set_mimetype (app, roxenlauncher_application_form_get_content_type (d));
			roxenlauncher_application_set_name (app, roxenlauncher_application_form_get_editor_name (d));
			roxenlauncher_application_set_command (app, roxenlauncher_application_form_get_editor_command (d));
			roxenlauncher_application_set_arguments (app, roxenlauncher_application_form_get_editor_arguments (d));
			roxenlauncher_application_save_list ();
			gtk_list_store_set (self->priv->ls_apps, &iter, 0, roxenlauncher_application_form_get_content_type (d), 1, roxenlauncher_application_form_get_editor_name (d), -1);
		}
		_g_object_unref0 (d);
	}
	_g_object_unref0 (model);
	_g_object_unref0 (app);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean _lambda4_ (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, Block2Data* _data2_) {
	RoxenlauncherMainWindow * self;
	gboolean result;
	GValue v = {0};
	GValue _tmp1_;
	GValue _tmp0_ = {0};
	LauncherFile* f;
	gboolean _tmp2_ = FALSE;
	self = _data2_->self;
	g_return_val_if_fail (model != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	gtk_tree_model_get_value (model, iter, 3, &_tmp0_);
	v = (_tmp1_ = _tmp0_, G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL, _tmp1_);
	f = _g_object_ref0 (g_value_get_object (&v));
	if (f != NULL) {
		_tmp2_ = _vala_strcmp0 (launcher_file_get_id (_data2_->lf), launcher_file_get_id (f)) == 0;
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		gtk_list_store_set (self->priv->ls_files, iter, 1, _data2_->status, -1);
		result = TRUE;
		G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL;
		_g_object_unref0 (f);
		return result;
	}
	g_value_unset (&v);
	result = FALSE;
	G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL;
	_g_object_unref0 (f);
	return result;
}


static gboolean __lambda4__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self) {
	return _lambda4_ (model, path, iter, self);
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
	++_data2_->_ref_count_;
	return _data2_;
}


static Block2Data* block2_data_unref (Block2Data* _data2_) {
	if ((--_data2_->_ref_count_) == 0) {
		_g_object_unref0 (_data2_->self);
		_g_object_unref0 (_data2_->lf);
		_g_free0 (_data2_->status);
		g_slice_free (Block2Data, _data2_);
	}
}


void roxenlauncher_main_window_set_file_status (RoxenlauncherMainWindow* self, LauncherFile* lf, const char* status) {
	Block2Data* _data2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (lf != NULL);
	g_return_if_fail (status != NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_data2_->self = g_object_ref (self);
	_data2_->lf = _g_object_ref0 (lf);
	_data2_->status = g_strdup (status);
	gtk_tree_model_foreach ((GtkTreeModel*) self->priv->ls_files, __lambda4__gtk_tree_model_foreach_func, _data2_);
	block2_data_unref (_data2_);
}


static GObject* roxenlauncher_main_window_gtkobj (RoxenlauncherMainWindow* self, const char* name) {
	GObject* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	result = _g_object_ref0 (gtk_builder_get_object (self->priv->builder, name));
	return result;
}


static void roxenlauncher_main_window_on_btn_edit_app_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_editor_dialog_edit (self);
}


static void roxenlauncher_main_window_on_btn_remove_app_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_remove_application (self);
}


static void roxenlauncher_main_window_on_btn_finish_file_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_finish_file (self);
}


static void roxenlauncher_main_window_on_btn_finish_all_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_finish_all_files (self);
}


static void roxenlauncher_main_window_on_tv_apps_selection_changed (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_set_app_buttons_sensitivity (self);
}


static void roxenlauncher_main_window_on_tv_files_selection_changed (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_set_buttons_sensitivity (self);
}


static void roxenlauncher_main_window_on_tv_files_activated (RoxenlauncherMainWindow* self, GtkTreePath* path, GtkTreeViewColumn* col) {
	GtkTreeModel* a;
	GtkTreeIter b = {0};
	GtkTreeModel* _tmp2_;
	LauncherFile* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	LauncherFile* lf;
	g_return_if_fail (self != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (col != NULL);
	a = NULL;
	lf = (_tmp1_ = roxenlauncher_main_window_get_selected_file (self, &_tmp0_, &b), a = (_tmp2_ = _tmp0_, _g_object_unref0 (a), _tmp2_), _tmp1_);
	if (lf != NULL) {
		char* _tmp3_;
		g_message ("mainwindow.vala:324: Got row...%s", _tmp3_ = launcher_file_get_uri (lf));
		_g_free0 (_tmp3_);
		launcher_file_download (lf, TRUE);
	}
	_g_object_unref0 (a);
	_g_object_unref0 (lf);
}


static void roxenlauncher_main_window_on_tv_apps_activated (RoxenlauncherMainWindow* self, GtkTreePath* path, GtkTreeViewColumn* col) {
	GtkTreeModel* a;
	GtkTreeIter b = {0};
	RoxenlauncherApplication* _tmp3_;
	GtkTreeModel* _tmp2_;
	RoxenlauncherApplication* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean _tmp4_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (col != NULL);
	a = NULL;
	if ((_tmp4_ = (_tmp3_ = (_tmp1_ = roxenlauncher_main_window_get_selected_application (self, &_tmp0_, &b), a = (_tmp2_ = _tmp0_, _g_object_unref0 (a), _tmp2_), _tmp1_)) != NULL, _g_object_unref0 (_tmp3_), _tmp4_)) {
		roxenlauncher_main_window_editor_dialog_edit (self);
	}
	_g_object_unref0 (a);
}


static gboolean roxenlauncher_main_window_on_tv_files_key_release_event (RoxenlauncherMainWindow* self, GtkWidget* source, GdkEventKey* key) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	GeeArrayList* _tmp1_;
	gboolean _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (source != NULL, FALSE);
	if ((_tmp2_ = gee_collection_get_size ((GeeCollection*) (_tmp1_ = launcher_file_get_files ())) > 0, _g_object_unref0 (_tmp1_), _tmp2_)) {
		char* _tmp3_;
		_tmp0_ = _vala_strcmp0 (_tmp3_ = g_utf8_strdown (gdk_keyval_name ((*key).keyval), -1), "delete") == 0;
		_g_free0 (_tmp3_);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		GtkTreeModel* model;
		GtkTreeIter iter = {0};
		LauncherFile* _tmp7_;
		GtkTreeModel* _tmp6_;
		LauncherFile* _tmp5_;
		GtkTreeModel* _tmp4_ = NULL;
		gboolean _tmp8_;
		model = NULL;
		if ((_tmp8_ = (_tmp7_ = (_tmp5_ = roxenlauncher_main_window_get_selected_file (self, &_tmp4_, &iter), model = (_tmp6_ = _tmp4_, _g_object_unref0 (model), _tmp6_), _tmp5_)) == NULL, _g_object_unref0 (_tmp7_), _tmp8_)) {
			g_message ("mainwindow.vala:360: No selected file to delete!");
			result = FALSE;
			_g_object_unref0 (model);
			return result;
		}
		if (roxenlauncher_alert_confirm (self->priv->win, "Do you want to delete the selected file?")) {
			roxenlauncher_main_window_finish_file (self);
			result = TRUE;
			_g_object_unref0 (model);
			return result;
		}
		_g_object_unref0 (model);
	}
	result = FALSE;
	return result;
}


static gboolean roxenlauncher_main_window_on_tv_apps_key_release_event (RoxenlauncherMainWindow* self, GtkWidget* source, GdkEventKey* key) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	GeeArrayList* _tmp1_;
	gboolean _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (source != NULL, FALSE);
	if ((_tmp2_ = gee_collection_get_size ((GeeCollection*) (_tmp1_ = roxenlauncher_application_get_applications ())) > 0, _g_object_unref0 (_tmp1_), _tmp2_)) {
		char* _tmp3_;
		_tmp0_ = _vala_strcmp0 (_tmp3_ = g_utf8_strdown (gdk_keyval_name ((*key).keyval), -1), "delete") == 0;
		_g_free0 (_tmp3_);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		GtkTreeModel* model;
		GtkTreeIter iter = {0};
		RoxenlauncherApplication* _tmp7_;
		GtkTreeModel* _tmp6_;
		RoxenlauncherApplication* _tmp5_;
		GtkTreeModel* _tmp4_ = NULL;
		gboolean _tmp8_;
		char* msg;
		model = NULL;
		if ((_tmp8_ = (_tmp7_ = (_tmp5_ = roxenlauncher_main_window_get_selected_application (self, &_tmp4_, &iter), model = (_tmp6_ = _tmp4_, _g_object_unref0 (model), _tmp6_), _tmp5_)) == NULL, _g_object_unref0 (_tmp7_), _tmp8_)) {
			g_message ("mainwindow.vala:389: No selected file to delete!");
			result = FALSE;
			_g_object_unref0 (model);
			return result;
		}
		msg = g_strdup ("Do you want to delete the selected application?");
		if (roxenlauncher_alert_confirm (self->priv->win, msg)) {
			roxenlauncher_main_window_remove_application (self);
			result = TRUE;
			_g_object_unref0 (model);
			_g_free0 (msg);
			return result;
		}
		_g_object_unref0 (model);
		_g_free0 (msg);
	}
	result = FALSE;
	return result;
}


static void roxenlauncher_main_window_on_window_destroy (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	g_message ("mainwindow.vala:408: Main killed");
	gtk_main_quit ();
}


static void roxenlauncher_main_window_set_app_buttons_sensitivity (RoxenlauncherMainWindow* self) {
	GtkTreeSelection* sel;
	GtkTreeIter iter = {0};
	GtkTreeModel* model;
	GtkTreeModel* _tmp2_;
	gboolean _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean is_active;
	g_return_if_fail (self != NULL);
	sel = _g_object_ref0 (gtk_tree_view_get_selection (self->priv->tv_apps));
	model = NULL;
	is_active = (_tmp1_ = gtk_tree_selection_get_selected (sel, &_tmp0_, &iter), model = (_tmp2_ = _g_object_ref0 (_tmp0_), _g_object_unref0 (model), _tmp2_), _tmp1_);
	g_object_set ((GtkWidget*) self->priv->btn_edit_app, "sensitive", is_active, NULL);
	g_object_set ((GtkWidget*) self->priv->btn_remove_app, "sensitive", is_active, NULL);
	_g_object_unref0 (sel);
	_g_object_unref0 (model);
}


static void roxenlauncher_main_window_set_buttons_sensitivity (RoxenlauncherMainWindow* self) {
	GtkTreeSelection* sel;
	GtkTreeIter iter = {0};
	GtkTreeModel* model;
	GtkTreeModel* _tmp2_;
	gboolean _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean is_active;
	GeeArrayList* _tmp3_;
	g_return_if_fail (self != NULL);
	sel = _g_object_ref0 (gtk_tree_view_get_selection (self->priv->tv_files));
	model = NULL;
	is_active = (_tmp1_ = gtk_tree_selection_get_selected (sel, &_tmp0_, &iter), model = (_tmp2_ = _g_object_ref0 (_tmp0_), _g_object_unref0 (model), _tmp2_), _tmp1_);
	g_object_set ((GtkWidget*) self->priv->btn_edit_file, "sensitive", is_active, NULL);
	g_object_set ((GtkWidget*) self->priv->btn_finish_file, "sensitive", is_active, NULL);
	g_object_set ((GtkWidget*) self->priv->btn_finish_all, "sensitive", gee_collection_get_size ((GeeCollection*) (_tmp3_ = launcher_file_get_files ())) > 0, NULL);
	_g_object_unref0 (_tmp3_);
	_g_object_unref0 (sel);
	_g_object_unref0 (model);
}


static void roxenlauncher_main_window_finish_file (RoxenlauncherMainWindow* self) {
	GtkTreeModel* model;
	GtkTreeIter iter = {0};
	GtkTreeModel* _tmp2_;
	LauncherFile* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	LauncherFile* file;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (self != NULL);
	model = NULL;
	file = (_tmp1_ = roxenlauncher_main_window_get_selected_file (self, &_tmp0_, &iter), model = (_tmp2_ = _tmp0_, _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (file != NULL) {
		_tmp3_ = launcher_file_delete (file);
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		gtk_list_store_remove (self->priv->ls_files, &iter);
		launcher_file_remove_file (file);
	}
	roxenlauncher_main_window_set_file_count (self);
	roxenlauncher_main_window_set_buttons_sensitivity (self);
	_g_object_unref0 (model);
	_g_object_unref0 (file);
}


static void roxenlauncher_main_window_finish_all_files (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	g_message ("mainwindow.vala:466: Finish all files...");
	gtk_list_store_clear (self->priv->ls_files);
	{
		GeeArrayList* _tmp0_;
		GeeIterator* _tmp1_;
		GeeIterator* _lf_it;
		_lf_it = (_tmp1_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) (_tmp0_ = launcher_file_get_files ())), _g_object_unref0 (_tmp0_), _tmp1_);
		while (TRUE) {
			LauncherFile* lf;
			if (!gee_iterator_next (_lf_it)) {
				break;
			}
			lf = (LauncherFile*) gee_iterator_get (_lf_it);
			launcher_file_delete (lf);
			_g_object_unref0 (lf);
		}
		_g_object_unref0 (_lf_it);
	}
	launcher_file_clear_files ();
	roxenlauncher_main_window_set_buttons_sensitivity (self);
	roxenlauncher_main_window_set_file_count (self);
}


static void roxenlauncher_main_window_remove_application (RoxenlauncherMainWindow* self) {
	GtkTreeModel* model;
	GtkTreeIter iter = {0};
	GtkTreeModel* _tmp2_;
	RoxenlauncherApplication* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	RoxenlauncherApplication* app;
	g_return_if_fail (self != NULL);
	model = NULL;
	app = (_tmp1_ = roxenlauncher_main_window_get_selected_application (self, &_tmp0_, &iter), model = (_tmp2_ = _tmp0_, _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (app != NULL) {
		{
			GeeArrayList* _tmp3_;
			GeeIterator* _tmp4_;
			GeeIterator* _lf_it;
			_lf_it = (_tmp4_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) (_tmp3_ = launcher_file_get_files ())), _g_object_unref0 (_tmp3_), _tmp4_);
			while (TRUE) {
				LauncherFile* lf;
				if (!gee_iterator_next (_lf_it)) {
					break;
				}
				lf = (LauncherFile*) gee_iterator_get (_lf_it);
				if (_vala_strcmp0 (roxenlauncher_application_get_mimetype (launcher_file_get_application (lf)), roxenlauncher_application_get_mimetype (app)) == 0) {
					launcher_file_unset_application (lf);
				}
				_g_object_unref0 (lf);
			}
			_g_object_unref0 (_lf_it);
		}
		roxenlauncher_application_remove_application (app);
		gtk_list_store_remove (self->priv->ls_apps, &iter);
	}
	_g_object_unref0 (model);
	_g_object_unref0 (app);
}


static LauncherFile* roxenlauncher_main_window_get_selected_file (RoxenlauncherMainWindow* self, GtkTreeModel** _model, GtkTreeIter* _iter) {
	LauncherFile* result;
	GtkTreeSelection* sel;
	GtkTreeIter iter = {0};
	GtkTreeModel* model;
	GtkTreeModel* _tmp2_;
	gboolean _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean has_sel;
	LauncherFile* lf;
	GtkTreeModel* _tmp3_;
	g_return_val_if_fail (self != NULL, NULL);
	if (_model != NULL) {
		*_model = NULL;
	}
	sel = _g_object_ref0 (gtk_tree_view_get_selection (self->priv->tv_files));
	model = NULL;
	has_sel = (_tmp1_ = gtk_tree_selection_get_selected (sel, &_tmp0_, &iter), model = (_tmp2_ = _g_object_ref0 (_tmp0_), _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (!has_sel) {
		result = NULL;
		_g_object_unref0 (sel);
		_g_object_unref0 (model);
		return result;
	}
	lf = NULL;
	gtk_tree_model_get (model, &iter, 3, &lf, -1, -1);
	if (lf == NULL) {
		g_message ("mainwindow.vala:518: No file selected!");
		result = NULL;
		_g_object_unref0 (sel);
		_g_object_unref0 (model);
		_g_object_unref0 (lf);
		return result;
	}
	*_model = (_tmp3_ = _g_object_ref0 (model), _g_object_unref0 (*_model), _tmp3_);
	*_iter = iter;
	result = lf;
	_g_object_unref0 (sel);
	_g_object_unref0 (model);
	return result;
}


static RoxenlauncherApplication* roxenlauncher_main_window_get_selected_application (RoxenlauncherMainWindow* self, GtkTreeModel** _model, GtkTreeIter* _iter) {
	RoxenlauncherApplication* result;
	GtkTreeSelection* sel;
	GtkTreeIter iter = {0};
	GtkTreeModel* model;
	GtkTreeModel* _tmp2_;
	gboolean _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean has_sel;
	RoxenlauncherApplication* app;
	GtkTreeModel* _tmp3_;
	g_return_val_if_fail (self != NULL, NULL);
	if (_model != NULL) {
		*_model = NULL;
	}
	sel = _g_object_ref0 (gtk_tree_view_get_selection (self->priv->tv_apps));
	model = NULL;
	has_sel = (_tmp1_ = gtk_tree_selection_get_selected (sel, &_tmp0_, &iter), model = (_tmp2_ = _g_object_ref0 (_tmp0_), _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (!has_sel) {
		result = NULL;
		_g_object_unref0 (sel);
		_g_object_unref0 (model);
		return result;
	}
	app = NULL;
	gtk_tree_model_get (model, &iter, 2, &app, -1, -1);
	if (app == NULL) {
		g_message ("mainwindow.vala:553: No application selected...!");
		result = NULL;
		_g_object_unref0 (sel);
		_g_object_unref0 (model);
		_g_object_unref0 (app);
		return result;
	}
	*_model = (_tmp3_ = _g_object_ref0 (model), _g_object_unref0 (*_model), _tmp3_);
	*_iter = iter;
	result = app;
	_g_object_unref0 (sel);
	_g_object_unref0 (model);
	return result;
}


static void roxenlauncher_main_window_set_file_count (RoxenlauncherMainWindow* self) {
	char* m;
	GeeArrayList* _tmp0_;
	gint _tmp1_;
	gint num;
	char* _tmp5_;
	g_return_if_fail (self != NULL);
	m = g_strdup ("");
	num = (_tmp1_ = gee_collection_get_size ((GeeCollection*) (_tmp0_ = launcher_file_get_files ())), _g_object_unref0 (_tmp0_), _tmp1_);
	if (num == 0) {
		char* _tmp2_;
		m = (_tmp2_ = g_strdup ("No files"), _g_free0 (m), _tmp2_);
	} else {
		if (num == 1) {
			char* _tmp3_;
			m = (_tmp3_ = g_strdup ("One file"), _g_free0 (m), _tmp3_);
		} else {
			char* _tmp4_;
			m = (_tmp4_ = g_strdup_printf ("%ld files", (glong) num), _g_free0 (m), _tmp4_);
		}
	}
	roxenlauncher_main_window_set_status (self, _tmp5_ = g_strconcat ("# ", m, NULL));
	_g_free0 (_tmp5_);
	_g_free0 (m);
}


static void roxenlauncher_main_window_set_status (RoxenlauncherMainWindow* self, const char* text) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (text != NULL);
	gtk_statusbar_push (self->priv->statusbar, (guint) 0, text);
}


RoxenlauncherMainWindow* roxenlauncher_main_window_construct (GType object_type) {
	RoxenlauncherMainWindow * self;
	self = (RoxenlauncherMainWindow*) g_object_new (object_type, NULL);
	return self;
}


RoxenlauncherMainWindow* roxenlauncher_main_window_new (void) {
	return roxenlauncher_main_window_construct (ROXENLAUNCHER_TYPE_MAIN_WINDOW);
}


static void roxenlauncher_main_window_class_init (RoxenlauncherMainWindowClass * klass) {
	roxenlauncher_main_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (RoxenlauncherMainWindowPrivate));
	G_OBJECT_CLASS (klass)->finalize = roxenlauncher_main_window_finalize;
}


static void roxenlauncher_main_window_instance_init (RoxenlauncherMainWindow * self) {
	self->priv = ROXENLAUNCHER_MAIN_WINDOW_GET_PRIVATE (self);
}


static void roxenlauncher_main_window_finalize (GObject* obj) {
	RoxenlauncherMainWindow * self;
	self = ROXENLAUNCHER_MAIN_WINDOW (obj);
	_g_object_unref0 (self->priv->builder);
	_g_object_unref0 (self->priv->win);
	_g_object_unref0 (self->priv->sw_files);
	_g_object_unref0 (self->priv->cb_logging);
	_g_object_unref0 (self->priv->fc_logfile);
	_g_object_unref0 (self->priv->btn_edit_file);
	_g_object_unref0 (self->priv->btn_finish_file);
	_g_object_unref0 (self->priv->btn_finish_all);
	_g_object_unref0 (self->priv->btn_edit_app);
	_g_object_unref0 (self->priv->btn_add_app);
	_g_object_unref0 (self->priv->btn_remove_app);
	_g_object_unref0 (self->priv->tv_files);
	_g_object_unref0 (self->priv->tv_apps);
	_g_object_unref0 (self->priv->ls_files);
	_g_object_unref0 (self->priv->ls_apps);
	_g_object_unref0 (self->priv->statusbar);
	G_OBJECT_CLASS (roxenlauncher_main_window_parent_class)->finalize (obj);
}


GType roxenlauncher_main_window_get_type (void) {
	static GType roxenlauncher_main_window_type_id = 0;
	if (roxenlauncher_main_window_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (RoxenlauncherMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) roxenlauncher_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RoxenlauncherMainWindow), 0, (GInstanceInitFunc) roxenlauncher_main_window_instance_init, NULL };
		roxenlauncher_main_window_type_id = g_type_register_static (G_TYPE_OBJECT, "RoxenlauncherMainWindow", &g_define_type_info, 0);
	}
	return roxenlauncher_main_window_type_id;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




