/* application.c generated by valac, the Vala compiler
 * generated from application.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include </home/pontus/Vala/roxenlauncher/config.h>
#include <gconf/gconf-client.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gconf/gconf.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define ROXENLAUNCHER_TYPE_APPLICATION (roxenlauncher_application_get_type ())
#define ROXENLAUNCHER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplication))
#define ROXENLAUNCHER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))
#define ROXENLAUNCHER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))

typedef struct _RoxenlauncherApplication RoxenlauncherApplication;
typedef struct _RoxenlauncherApplicationClass RoxenlauncherApplicationClass;
typedef struct _RoxenlauncherApplicationPrivate RoxenlauncherApplicationPrivate;
#define __g_slist_free_g_free0(var) ((var == NULL) ? NULL : (var = (_g_slist_free_g_free (var), NULL)))

struct _RoxenlauncherApplication {
	GObject parent_instance;
	RoxenlauncherApplicationPrivate * priv;
};

struct _RoxenlauncherApplicationClass {
	GObjectClass parent_class;
};

struct _RoxenlauncherApplicationPrivate {
	char* _name;
	char* _command;
	char* _mimetype;
	char* _arguments;
};


static GeeArrayList* roxenlauncher_application_applications;
static GeeArrayList* roxenlauncher_application_applications = NULL;
static gpointer roxenlauncher_application_parent_class = NULL;

#define ROXENLAUNCHER_APP_NAME "Roxen Application Launcher"
#define ROXENLAUNCHER_APP_LIB_UNIQUE_PATH "com.roxen.launcher"
#define ROXENLAUNCHER_APP_DIR ".roxenlauncher"
#define ROXENLAUNCHER_APP_FILES_DIR "files"
#define ROXENLAUNCHER_APP_MAIN_UI_FILENAME "mainwindow.ui"
#define ROXENLAUNCHER_APP_EDITOR_UI_FILENAME "application-form.ui"
#define ROXENLAUNCHER_APP_UI_PATH "gui:" DATADIR "/roxenlauncher/ui"
#define ROXENLAUNCHER_APP_GCONF_ROOT "/apps/roxenlauncher/"
#define ROXENLAUNCHER_APP_LAST_FOLDER "~/"
char* roxenlauncher_getdir (const char* which);
char* roxenlauncher_get_last_folder (void);
void roxenlauncher_set_last_folder (const char* path);
GType roxenlauncher_application_get_type (void);
#define ROXENLAUNCHER_APPLICATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationPrivate))
enum  {
	ROXENLAUNCHER_APPLICATION_DUMMY_PROPERTY,
	ROXENLAUNCHER_APPLICATION_NAME,
	ROXENLAUNCHER_APPLICATION_COMMAND,
	ROXENLAUNCHER_APPLICATION_MIMETYPE,
	ROXENLAUNCHER_APPLICATION_ARGUMENTS
};
GeeArrayList* roxenlauncher_application_get_applications (void);
RoxenlauncherApplication* roxenlauncher_application_get_for_mimetype (const char* mimetype);
const char* roxenlauncher_application_get_mimetype (RoxenlauncherApplication* self);
void roxenlauncher_application_save_list (void);
void roxenlauncher_application_add_application (RoxenlauncherApplication* app);
void roxenlauncher_application_remove_application (RoxenlauncherApplication* app);
GSList* roxenlauncher_application_to_gconf_list (void);
static void _g_slist_free_g_free (GSList* self);
char* roxenlauncher_application_to_gconf_string (RoxenlauncherApplication* self);
RoxenlauncherApplication* roxenlauncher_application_new (const char* name, const char* command, const char* mimetype, const char* arguments);
RoxenlauncherApplication* roxenlauncher_application_construct (GType object_type, const char* name, const char* command, const char* mimetype, const char* arguments);
void roxenlauncher_application_set_arguments (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_load_from_gconf (void);
void roxenlauncher_application_set_name (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_command (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_mimetype (RoxenlauncherApplication* self, const char* value);
const char* roxenlauncher_application_get_name (RoxenlauncherApplication* self);
const char* roxenlauncher_application_get_command (RoxenlauncherApplication* self);
const char* roxenlauncher_application_get_arguments (RoxenlauncherApplication* self);
static void roxenlauncher_application_finalize (GObject* obj);
static void roxenlauncher_application_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void roxenlauncher_application_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);
static int _vala_strcmp0 (const char * str1, const char * str2);



static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


char* roxenlauncher_get_last_folder (void) {
	char* result;
	GError * _inner_error_;
	GConfClient* cli;
	char* k;
	_inner_error_ = NULL;
	cli = _g_object_ref0 (gconf_client_get_default ());
	k = NULL;
	{
		const char* _tmp0_;
		char* _tmp1_;
		_tmp0_ = gconf_client_get_string (cli, ROXENLAUNCHER_APP_GCONF_ROOT "properties/last-folder", &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch11_g_error;
			goto __finally11;
		}
		k = (_tmp1_ = g_strdup (_tmp0_), _g_free0 (k), _tmp1_);
	}
	goto __finally11;
	__catch11_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:28: Error getting GConf key \"%s\": %s", k, e->message);
			_g_error_free0 (e);
		}
	}
	__finally11:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (cli);
		_g_free0 (k);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	if (k == NULL) {
		char* _tmp2_;
		k = (_tmp2_ = roxenlauncher_getdir ("$home"), _g_free0 (k), _tmp2_);
	}
	result = k;
	_g_object_unref0 (cli);
	return result;
}


void roxenlauncher_set_last_folder (const char* path) {
	GError * _inner_error_;
	GConfClient* cli;
	char* key;
	g_return_if_fail (path != NULL);
	_inner_error_ = NULL;
	cli = _g_object_ref0 (gconf_client_get_default ());
	key = g_strdup (ROXENLAUNCHER_APP_GCONF_ROOT "properties/last-folder");
	{
		gconf_client_set_string (cli, key, path, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch12_g_error;
			goto __finally12;
		}
		g_message ("application.vala:41: Set last folder to: %s", path);
	}
	goto __finally12;
	__catch12_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:44: Error setting GConf key \"%s\": %s", key, e->message);
			_g_error_free0 (e);
		}
	}
	__finally12:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (cli);
		_g_free0 (key);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (cli);
	_g_free0 (key);
}


GeeArrayList* roxenlauncher_application_get_applications (void) {
	GeeArrayList* result;
	result = _g_object_ref0 (roxenlauncher_application_applications);
	return result;
}


void roxenlauncher_application_add_application (RoxenlauncherApplication* app) {
	RoxenlauncherApplication* a;
	RoxenlauncherApplication* _tmp1_;
	g_return_if_fail (app != NULL);
	if (roxenlauncher_application_applications == NULL) {
		GeeArrayList* _tmp0_;
		roxenlauncher_application_applications = (_tmp0_ = gee_array_list_new (ROXENLAUNCHER_TYPE_APPLICATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (roxenlauncher_application_applications), _tmp0_);
	}
	a = NULL;
	if ((a = (_tmp1_ = roxenlauncher_application_get_for_mimetype (app->priv->_mimetype), _g_object_unref0 (a), _tmp1_)) != NULL) {
		_g_object_unref0 (a);
		return;
	}
	g_message ("application.vala:74: Do add application...");
	gee_abstract_collection_add ((GeeAbstractCollection*) roxenlauncher_application_applications, app);
	roxenlauncher_application_save_list ();
	_g_object_unref0 (a);
}


void roxenlauncher_application_remove_application (RoxenlauncherApplication* app) {
	g_return_if_fail (app != NULL);
	gee_abstract_collection_remove ((GeeAbstractCollection*) roxenlauncher_application_applications, app);
	roxenlauncher_application_save_list ();
}


static void _g_slist_free_g_free (GSList* self) {
	g_slist_foreach (self, (GFunc) g_free, NULL);
	g_slist_free (self);
}


void roxenlauncher_application_save_list (void) {
	GError * _inner_error_;
	GSList* list;
	_inner_error_ = NULL;
	list = roxenlauncher_application_to_gconf_list ();
	{
		GConfClient* cli;
		char* key;
		cli = _g_object_ref0 (gconf_client_get_default ());
		key = g_strdup (ROXENLAUNCHER_APP_GCONF_ROOT "settings/applications");
		gconf_client_set_list (cli, key, GCONF_VALUE_STRING, list, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (cli);
			_g_free0 (key);
			goto __catch13_g_error;
			goto __finally13;
		}
		_g_object_unref0 (cli);
		_g_free0 (key);
	}
	goto __finally13;
	__catch13_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:101: Failed to save applications to GConf: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally13:
	if (_inner_error_ != NULL) {
		__g_slist_free_g_free0 (list);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	__g_slist_free_g_free0 (list);
}


RoxenlauncherApplication* roxenlauncher_application_get_for_mimetype (const char* mimetype) {
	RoxenlauncherApplication* result;
	g_return_val_if_fail (mimetype != NULL, NULL);
	if (roxenlauncher_application_applications == NULL) {
		GeeArrayList* _tmp0_;
		roxenlauncher_application_applications = (_tmp0_ = gee_array_list_new (ROXENLAUNCHER_TYPE_APPLICATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (roxenlauncher_application_applications), _tmp0_);
	}
	if (gee_collection_get_size ((GeeCollection*) roxenlauncher_application_applications) == 0) {
		result = NULL;
		return result;
	}
	{
		GeeIterator* _app_it;
		_app_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) roxenlauncher_application_applications);
		while (TRUE) {
			RoxenlauncherApplication* app;
			if (!gee_iterator_next (_app_it)) {
				break;
			}
			app = (RoxenlauncherApplication*) gee_iterator_get (_app_it);
			if (_vala_strcmp0 (app->priv->_mimetype, mimetype) == 0) {
				result = app;
				_g_object_unref0 (_app_it);
				return result;
			}
			_g_object_unref0 (app);
		}
		_g_object_unref0 (_app_it);
	}
	result = NULL;
	return result;
}


GSList* roxenlauncher_application_to_gconf_list (void) {
	GSList* result;
	GSList* list;
	if (roxenlauncher_application_applications == NULL) {
		GeeArrayList* _tmp0_;
		roxenlauncher_application_applications = (_tmp0_ = gee_array_list_new (ROXENLAUNCHER_TYPE_APPLICATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (roxenlauncher_application_applications), _tmp0_);
	}
	list = NULL;
	{
		GeeIterator* _app_it;
		_app_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) roxenlauncher_application_applications);
		while (TRUE) {
			RoxenlauncherApplication* app;
			if (!gee_iterator_next (_app_it)) {
				break;
			}
			app = (RoxenlauncherApplication*) gee_iterator_get (_app_it);
			list = g_slist_append (list, roxenlauncher_application_to_gconf_string (app));
			_g_object_unref0 (app);
		}
		_g_object_unref0 (_app_it);
	}
	result = list;
	return result;
}


static glong string_get_length (const char* self) {
	glong result;
	g_return_val_if_fail (self != NULL, 0L);
	result = g_utf8_strlen (self, -1);
	return result;
}


void roxenlauncher_application_load_from_gconf (void) {
	GError * _inner_error_;
	GConfClient* cli;
	char* key;
	GSList* list;
	_inner_error_ = NULL;
	if (roxenlauncher_application_applications == NULL) {
		GeeArrayList* _tmp0_;
		roxenlauncher_application_applications = (_tmp0_ = gee_array_list_new (ROXENLAUNCHER_TYPE_APPLICATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (roxenlauncher_application_applications), _tmp0_);
	}
	cli = _g_object_ref0 (gconf_client_get_default ());
	key = g_strdup (ROXENLAUNCHER_APP_GCONF_ROOT "settings/applications");
	list = NULL;
	{
		GSList* _tmp1_;
		_tmp1_ = gconf_client_get_list (cli, key, GCONF_VALUE_STRING, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch14_g_error;
			goto __finally14;
		}
		list = _tmp1_;
	}
	goto __finally14;
	__catch14_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:157: Error getting GConf list for \"%s\": %s", key, e->message);
			_g_error_free0 (e);
		}
	}
	__finally14:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (cli);
		_g_free0 (key);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	if (list != NULL) {
		{
			GSList* s_collection;
			GSList* s_it;
			s_collection = list;
			for (s_it = s_collection; s_it != NULL; s_it = s_it->next) {
				char* s;
				s = g_strdup ((const char*) s_it->data);
				{
					char** _tmp3_;
					gint pts_size;
					gint pts_length1;
					char** _tmp2_;
					char** pts;
					RoxenlauncherApplication* app;
					gboolean _tmp4_ = FALSE;
					pts = (_tmp3_ = _tmp2_ = g_strsplit (s, "::", 0), pts_length1 = _vala_array_length (_tmp2_), pts_size = pts_length1, _tmp3_);
					app = roxenlauncher_application_new (pts[0], pts[1], pts[2], "");
					if (pts_length1 > 3) {
						_tmp4_ = string_get_length (pts[3]) > 0;
					} else {
						_tmp4_ = FALSE;
					}
					if (_tmp4_) {
						roxenlauncher_application_set_arguments (app, pts[3]);
					}
					gee_abstract_collection_add ((GeeAbstractCollection*) roxenlauncher_application_applications, app);
					_g_free0 (s);
					pts = (_vala_array_free (pts, pts_length1, (GDestroyNotify) g_free), NULL);
					_g_object_unref0 (app);
				}
			}
		}
	}
	_g_object_unref0 (cli);
	_g_free0 (key);
}


RoxenlauncherApplication* roxenlauncher_application_construct (GType object_type, const char* name, const char* command, const char* mimetype, const char* arguments) {
	RoxenlauncherApplication * self;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (command != NULL, NULL);
	g_return_val_if_fail (mimetype != NULL, NULL);
	g_return_val_if_fail (arguments != NULL, NULL);
	self = (RoxenlauncherApplication*) g_object_new (object_type, NULL);
	roxenlauncher_application_set_name (self, name);
	roxenlauncher_application_set_command (self, command);
	roxenlauncher_application_set_mimetype (self, mimetype);
	roxenlauncher_application_set_arguments (self, arguments);
	return self;
}


RoxenlauncherApplication* roxenlauncher_application_new (const char* name, const char* command, const char* mimetype, const char* arguments) {
	return roxenlauncher_application_construct (ROXENLAUNCHER_TYPE_APPLICATION, name, command, mimetype, arguments);
}


char* roxenlauncher_application_to_gconf_string (RoxenlauncherApplication* self) {
	char* result;
	char* _tmp4_;
	char* _tmp3_;
	char* _tmp2_;
	char* _tmp1_;
	char* _tmp0_;
	char* _tmp5_;
	g_return_val_if_fail (self != NULL, NULL);
	result = (_tmp5_ = g_strconcat (_tmp4_ = g_strconcat (_tmp3_ = g_strconcat (_tmp2_ = g_strconcat (_tmp1_ = g_strconcat (_tmp0_ = g_strconcat (self->priv->_name, "::", NULL), self->priv->_command, NULL), "::", NULL), self->priv->_mimetype, NULL), "::", NULL), self->priv->_arguments, NULL), _g_free0 (_tmp4_), _g_free0 (_tmp3_), _g_free0 (_tmp2_), _g_free0 (_tmp1_), _g_free0 (_tmp0_), _tmp5_);
	return result;
}


const char* roxenlauncher_application_get_name (RoxenlauncherApplication* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_name;
	return result;
}


void roxenlauncher_application_set_name (RoxenlauncherApplication* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_name), _tmp0_);
	g_object_notify ((GObject *) self, "name");
}


const char* roxenlauncher_application_get_command (RoxenlauncherApplication* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_command;
	return result;
}


void roxenlauncher_application_set_command (RoxenlauncherApplication* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_command = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_command), _tmp0_);
	g_object_notify ((GObject *) self, "command");
}


const char* roxenlauncher_application_get_mimetype (RoxenlauncherApplication* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_mimetype;
	return result;
}


void roxenlauncher_application_set_mimetype (RoxenlauncherApplication* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_mimetype = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_mimetype), _tmp0_);
	g_object_notify ((GObject *) self, "mimetype");
}


const char* roxenlauncher_application_get_arguments (RoxenlauncherApplication* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_arguments;
	return result;
}


void roxenlauncher_application_set_arguments (RoxenlauncherApplication* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_arguments = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_arguments), _tmp0_);
	g_object_notify ((GObject *) self, "arguments");
}


static void roxenlauncher_application_class_init (RoxenlauncherApplicationClass * klass) {
	roxenlauncher_application_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (RoxenlauncherApplicationPrivate));
	G_OBJECT_CLASS (klass)->get_property = roxenlauncher_application_get_property;
	G_OBJECT_CLASS (klass)->set_property = roxenlauncher_application_set_property;
	G_OBJECT_CLASS (klass)->finalize = roxenlauncher_application_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ROXENLAUNCHER_APPLICATION_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ROXENLAUNCHER_APPLICATION_COMMAND, g_param_spec_string ("command", "command", "command", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ROXENLAUNCHER_APPLICATION_MIMETYPE, g_param_spec_string ("mimetype", "mimetype", "mimetype", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ROXENLAUNCHER_APPLICATION_ARGUMENTS, g_param_spec_string ("arguments", "arguments", "arguments", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void roxenlauncher_application_instance_init (RoxenlauncherApplication * self) {
	self->priv = ROXENLAUNCHER_APPLICATION_GET_PRIVATE (self);
}


static void roxenlauncher_application_finalize (GObject* obj) {
	RoxenlauncherApplication * self;
	self = ROXENLAUNCHER_APPLICATION (obj);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_command);
	_g_free0 (self->priv->_mimetype);
	_g_free0 (self->priv->_arguments);
	G_OBJECT_CLASS (roxenlauncher_application_parent_class)->finalize (obj);
}


GType roxenlauncher_application_get_type (void) {
	static GType roxenlauncher_application_type_id = 0;
	if (roxenlauncher_application_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (RoxenlauncherApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) roxenlauncher_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RoxenlauncherApplication), 0, (GInstanceInitFunc) roxenlauncher_application_instance_init, NULL };
		roxenlauncher_application_type_id = g_type_register_static (G_TYPE_OBJECT, "RoxenlauncherApplication", &g_define_type_info, 0);
	}
	return roxenlauncher_application_type_id;
}


static void roxenlauncher_application_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	RoxenlauncherApplication * self;
	self = ROXENLAUNCHER_APPLICATION (object);
	switch (property_id) {
		case ROXENLAUNCHER_APPLICATION_NAME:
		g_value_set_string (value, roxenlauncher_application_get_name (self));
		break;
		case ROXENLAUNCHER_APPLICATION_COMMAND:
		g_value_set_string (value, roxenlauncher_application_get_command (self));
		break;
		case ROXENLAUNCHER_APPLICATION_MIMETYPE:
		g_value_set_string (value, roxenlauncher_application_get_mimetype (self));
		break;
		case ROXENLAUNCHER_APPLICATION_ARGUMENTS:
		g_value_set_string (value, roxenlauncher_application_get_arguments (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void roxenlauncher_application_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	RoxenlauncherApplication * self;
	self = ROXENLAUNCHER_APPLICATION (object);
	switch (property_id) {
		case ROXENLAUNCHER_APPLICATION_NAME:
		roxenlauncher_application_set_name (self, g_value_get_string (value));
		break;
		case ROXENLAUNCHER_APPLICATION_COMMAND:
		roxenlauncher_application_set_command (self, g_value_get_string (value));
		break;
		case ROXENLAUNCHER_APPLICATION_MIMETYPE:
		roxenlauncher_application_set_mimetype (self, g_value_get_string (value));
		break;
		case ROXENLAUNCHER_APPLICATION_ARGUMENTS:
		roxenlauncher_application_set_arguments (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




