/* application.c generated by valac, the Vala compiler
 * generated from application.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: t; c-basic-offset: 2; tab-width: 2 -*- */
/*
 * application.vala
 * Copyright (C) Pontus Östlund 2009 <pontus@poppa.se>
 *
 * This file is part of Roxen Application Launcher (RAL)
 * 
 * RAL is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * RAL is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with RAL.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <config.h>
#include <glib/gi18n-lib.h>
#include <string.h>
#include <gconf/gconf-client.h>
#include <stdlib.h>
#include <gee.h>
#include <gconf/gconf.h>


#define ROXENLAUNCHER_TYPE_WINDOWS_PROPERTIES (roxenlauncher_windows_properties_get_type ())
typedef struct _RoxenlauncherWindowsProperties RoxenlauncherWindowsProperties;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define ROXENLAUNCHER_TYPE_APPLICATION (roxenlauncher_application_get_type ())
#define ROXENLAUNCHER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplication))
#define ROXENLAUNCHER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))
#define ROXENLAUNCHER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))

typedef struct _RoxenlauncherApplication RoxenlauncherApplication;
typedef struct _RoxenlauncherApplicationClass RoxenlauncherApplicationClass;
typedef struct _RoxenlauncherApplicationPrivate RoxenlauncherApplicationPrivate;
#define __g_slist_free_g_free0(var) ((var == NULL) ? NULL : (var = (_g_slist_free_g_free (var), NULL)))

struct _RoxenlauncherWindowsProperties {
	gint width;
	gint height;
	gint x;
	gint y;
};

struct _RoxenlauncherApplication {
	GObject parent_instance;
	RoxenlauncherApplicationPrivate * priv;
};

struct _RoxenlauncherApplicationClass {
	GObjectClass parent_class;
};

struct _RoxenlauncherApplicationPrivate {
	char* _name;
	char* _command;
	char* _mimetype;
	char* _arguments;
};


extern RoxenlauncherWindowsProperties winprops;
static GeeArrayList* roxenlauncher_application_applications;
static GeeArrayList* roxenlauncher_application_applications = NULL;
static gpointer roxenlauncher_application_parent_class = NULL;

#define ROXENLAUNCHER_APP_VERSION VERSION
#define ROXENLAUNCHER_APP_NAME _ ("Roxen Application Launcher")
#define ROXENLAUNCHER_APP_LIB_UNIQUE_PATH "com.roxen.launcher"
#define ROXENLAUNCHER_APP_DIR ".roxenlauncher"
#define ROXENLAUNCHER_APP_FILES_DIR "files"
#define ROXENLAUNCHER_APP_MAIN_UI_FILENAME "mainwindow.ui"
#define ROXENLAUNCHER_APP_EDITOR_UI_FILENAME "application-form.ui"
#define ROXENLAUNCHER_APP_GCONF_ROOT "/apps/roxenlauncher/"
#define ROXENLAUNCHER_APP_DATE_FORMAT "%Y-%m-%d %H:%M"
#define ROXENLAUNCHER_APP_USER_AGENT "Roxen Application Launcher for Linux (" ROXENLAUNCHER_APP_VERSION ")"
GType roxenlauncher_windows_properties_get_type (void);
RoxenlauncherWindowsProperties* roxenlauncher_windows_properties_dup (const RoxenlauncherWindowsProperties* self);
void roxenlauncher_windows_properties_free (RoxenlauncherWindowsProperties* self);
void roxenlauncher_init (void);
gboolean roxenlauncher_file_exists (const char* file);
char* roxenlauncher_get_ui_path (const char* local_path);
void roxenlauncher_save_window_properties (gint width, gint height, gint x, gint y);
char* roxenlauncher_getdir (const char* which);
char* roxenlauncher_get_last_folder (void);
void roxenlauncher_set_last_folder (const char* path);
GType roxenlauncher_application_get_type (void);
#define ROXENLAUNCHER_APPLICATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationPrivate))
enum  {
	ROXENLAUNCHER_APPLICATION_DUMMY_PROPERTY,
	ROXENLAUNCHER_APPLICATION_NAME,
	ROXENLAUNCHER_APPLICATION_COMMAND,
	ROXENLAUNCHER_APPLICATION_MIMETYPE,
	ROXENLAUNCHER_APPLICATION_ARGUMENTS
};
GeeArrayList* roxenlauncher_application_get_applications (void);
RoxenlauncherApplication* roxenlauncher_application_get_for_mimetype (const char* mimetype);
const char* roxenlauncher_application_get_mimetype (RoxenlauncherApplication* self);
void roxenlauncher_application_save_list (void);
void roxenlauncher_application_add_application (RoxenlauncherApplication* app);
void roxenlauncher_application_remove_application (RoxenlauncherApplication* app);
GSList* roxenlauncher_application_to_gconf_list (void);
static void _g_slist_free_g_free (GSList* self);
char* roxenlauncher_application_to_gconf_string (RoxenlauncherApplication* self);
RoxenlauncherApplication* roxenlauncher_application_new (const char* name, const char* command, const char* mimetype, const char* arguments);
RoxenlauncherApplication* roxenlauncher_application_construct (GType object_type, const char* name, const char* command, const char* mimetype, const char* arguments);
void roxenlauncher_application_set_arguments (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_load_from_gconf (void);
void roxenlauncher_application_set_name (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_command (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_mimetype (RoxenlauncherApplication* self, const char* value);
const char* roxenlauncher_application_get_name (RoxenlauncherApplication* self);
const char* roxenlauncher_application_get_command (RoxenlauncherApplication* self);
const char* roxenlauncher_application_get_arguments (RoxenlauncherApplication* self);
static void roxenlauncher_application_finalize (GObject* obj);
static void roxenlauncher_application_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void roxenlauncher_application_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);
static int _vala_strcmp0 (const char * str1, const char * str2);



RoxenlauncherWindowsProperties* roxenlauncher_windows_properties_dup (const RoxenlauncherWindowsProperties* self) {
	RoxenlauncherWindowsProperties* dup;
	dup = g_new0 (RoxenlauncherWindowsProperties, 1);
	memcpy (dup, self, sizeof (RoxenlauncherWindowsProperties));
	return dup;
}


void roxenlauncher_windows_properties_free (RoxenlauncherWindowsProperties* self) {
	g_free (self);
}


GType roxenlauncher_windows_properties_get_type (void) {
	static GType roxenlauncher_windows_properties_type_id = 0;
	if (roxenlauncher_windows_properties_type_id == 0) {
		roxenlauncher_windows_properties_type_id = g_boxed_type_register_static ("RoxenlauncherWindowsProperties", (GBoxedCopyFunc) roxenlauncher_windows_properties_dup, (GBoxedFreeFunc) roxenlauncher_windows_properties_free);
	}
	return roxenlauncher_windows_properties_type_id;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void roxenlauncher_init (void) {
	GError * _inner_error_;
	RoxenlauncherWindowsProperties _tmp0_ = {0};
	GConfClient* cli;
	_inner_error_ = NULL;
	winprops = (_tmp0_.width = 0, _tmp0_.height = 0, _tmp0_.x = 0, _tmp0_.y = 0, _tmp0_);
	cli = _g_object_ref0 (gconf_client_get_default ());
	{
		char* p;
		char* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		char* _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		char* _tmp7_;
		gint _tmp8_;
		gint _tmp9_;
		char* _tmp10_;
		gint _tmp11_;
		gint _tmp12_;
		p = g_strdup (ROXENLAUNCHER_APP_GCONF_ROOT "properties/");
		_tmp3_ = (_tmp2_ = gconf_client_get_int (cli, _tmp1_ = g_strconcat (p, "window-width", NULL), &_inner_error_), _g_free0 (_tmp1_), _tmp2_);
		if (_inner_error_ != NULL) {
			_g_free0 (p);
			goto __catch2_g_error;
			goto __finally2;
		}
		winprops.width = _tmp3_;
		_tmp6_ = (_tmp5_ = gconf_client_get_int (cli, _tmp4_ = g_strconcat (p, "window-height", NULL), &_inner_error_), _g_free0 (_tmp4_), _tmp5_);
		if (_inner_error_ != NULL) {
			_g_free0 (p);
			goto __catch2_g_error;
			goto __finally2;
		}
		winprops.height = _tmp6_;
		_tmp9_ = (_tmp8_ = gconf_client_get_int (cli, _tmp7_ = g_strconcat (p, "window-x", NULL), &_inner_error_), _g_free0 (_tmp7_), _tmp8_);
		if (_inner_error_ != NULL) {
			_g_free0 (p);
			goto __catch2_g_error;
			goto __finally2;
		}
		winprops.x = _tmp9_;
		_tmp12_ = (_tmp11_ = gconf_client_get_int (cli, _tmp10_ = g_strconcat (p, "window-y", NULL), &_inner_error_), _g_free0 (_tmp10_), _tmp11_);
		if (_inner_error_ != NULL) {
			_g_free0 (p);
			goto __catch2_g_error;
			goto __finally2;
		}
		winprops.y = _tmp12_;
		_g_free0 (p);
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:63: Failed to read window properties from GConf: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally2:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (cli);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (cli);
}


char* roxenlauncher_get_ui_path (const char* local_path) {
	char* result;
	char** _tmp1_;
	gint paths_size;
	gint paths_length1;
	char** _tmp0_ = NULL;
	char** paths;
	char* full_path;
	g_return_val_if_fail (local_path != NULL, NULL);
	paths = (_tmp1_ = (_tmp0_ = g_new0 (char*, 2 + 1), _tmp0_[0] = g_strdup ("gui"), _tmp0_[1] = g_strdup (DATADIR "/roxenlauncher/gui"), _tmp0_), paths_length1 = 2, paths_size = paths_length1, _tmp1_);
	full_path = NULL;
	{
		char** path_collection;
		int path_collection_length1;
		int path_it;
		path_collection = paths;
		path_collection_length1 = paths_length1;
		for (path_it = 0; path_it < paths_length1; path_it = path_it + 1) {
			char* path;
			path = g_strdup (path_collection[path_it]);
			{
				char* _tmp2_;
				full_path = (_tmp2_ = g_build_filename (path, local_path, NULL), _g_free0 (full_path), _tmp2_);
				if (roxenlauncher_file_exists (full_path)) {
					result = full_path;
					_g_free0 (path);
					paths = (_vala_array_free (paths, paths_length1, (GDestroyNotify) g_free), NULL);
					return result;
				}
				_g_free0 (path);
			}
		}
	}
	result = NULL;
	paths = (_vala_array_free (paths, paths_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (full_path);
	return result;
}


void roxenlauncher_save_window_properties (gint width, gint height, gint x, gint y) {
	GError * _inner_error_;
	_inner_error_ = NULL;
	winprops.width = width;
	winprops.height = height;
	winprops.x = x;
	winprops.y = y;
	{
		GConfClient* cli;
		char* p;
		char* _tmp0_;
		char* _tmp1_;
		char* _tmp2_;
		char* _tmp3_;
		cli = _g_object_ref0 (gconf_client_get_default ());
		p = g_strdup (ROXENLAUNCHER_APP_GCONF_ROOT "properties/");
		gconf_client_set_int (cli, _tmp0_ = g_strconcat (p, "window-width", NULL), winprops.width, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (cli);
			_g_free0 (p);
			goto __catch3_g_error;
			goto __finally3;
		}
		_g_free0 (_tmp0_);
		gconf_client_set_int (cli, _tmp1_ = g_strconcat (p, "window-height", NULL), winprops.height, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (cli);
			_g_free0 (p);
			goto __catch3_g_error;
			goto __finally3;
		}
		_g_free0 (_tmp1_);
		gconf_client_set_int (cli, _tmp2_ = g_strconcat (p, "window-x", NULL), winprops.x, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (cli);
			_g_free0 (p);
			goto __catch3_g_error;
			goto __finally3;
		}
		_g_free0 (_tmp2_);
		gconf_client_set_int (cli, _tmp3_ = g_strconcat (p, "window-y", NULL), winprops.y, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (cli);
			_g_free0 (p);
			goto __catch3_g_error;
			goto __finally3;
		}
		_g_free0 (_tmp3_);
		_g_object_unref0 (cli);
		_g_free0 (p);
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:96: Failed to save window properties to GConf: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally3:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
}


char* roxenlauncher_get_last_folder (void) {
	char* result;
	GError * _inner_error_;
	GConfClient* cli;
	char* k;
	_inner_error_ = NULL;
	cli = _g_object_ref0 (gconf_client_get_default ());
	k = NULL;
	{
		const char* _tmp0_;
		char* _tmp1_;
		_tmp0_ = gconf_client_get_string (cli, ROXENLAUNCHER_APP_GCONF_ROOT "properties/last-folder", &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch4_g_error;
			goto __finally4;
		}
		k = (_tmp1_ = g_strdup (_tmp0_), _g_free0 (k), _tmp1_);
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:106: Error getting GConf key \"%s\": %s", k, e->message);
			_g_error_free0 (e);
		}
	}
	__finally4:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (cli);
		_g_free0 (k);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	if (k == NULL) {
		char* _tmp2_;
		k = (_tmp2_ = roxenlauncher_getdir ("$home"), _g_free0 (k), _tmp2_);
	}
	result = k;
	_g_object_unref0 (cli);
	return result;
}


void roxenlauncher_set_last_folder (const char* path) {
	GError * _inner_error_;
	GConfClient* cli;
	char* key;
	g_return_if_fail (path != NULL);
	_inner_error_ = NULL;
	cli = _g_object_ref0 (gconf_client_get_default ());
	key = g_strdup (ROXENLAUNCHER_APP_GCONF_ROOT "properties/last-folder");
	{
		gconf_client_set_string (cli, key, path, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch5_g_error;
			goto __finally5;
		}
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:119: Error setting GConf key \"%s\": %s", key, e->message);
			_g_error_free0 (e);
		}
	}
	__finally5:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (cli);
		_g_free0 (key);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_object_unref0 (cli);
	_g_free0 (key);
}


GeeArrayList* roxenlauncher_application_get_applications (void) {
	GeeArrayList* result;
	result = _g_object_ref0 (roxenlauncher_application_applications);
	return result;
}


void roxenlauncher_application_add_application (RoxenlauncherApplication* app) {
	RoxenlauncherApplication* a;
	RoxenlauncherApplication* _tmp1_;
	g_return_if_fail (app != NULL);
	if (roxenlauncher_application_applications == NULL) {
		GeeArrayList* _tmp0_;
		roxenlauncher_application_applications = (_tmp0_ = gee_array_list_new (ROXENLAUNCHER_TYPE_APPLICATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (roxenlauncher_application_applications), _tmp0_);
	}
	a = NULL;
	if ((a = (_tmp1_ = roxenlauncher_application_get_for_mimetype (app->priv->_mimetype), _g_object_unref0 (a), _tmp1_)) != NULL) {
		_g_object_unref0 (a);
		return;
	}
	gee_abstract_collection_add ((GeeAbstractCollection*) roxenlauncher_application_applications, app);
	roxenlauncher_application_save_list ();
	_g_object_unref0 (a);
}


void roxenlauncher_application_remove_application (RoxenlauncherApplication* app) {
	g_return_if_fail (app != NULL);
	gee_abstract_collection_remove ((GeeAbstractCollection*) roxenlauncher_application_applications, app);
	roxenlauncher_application_save_list ();
}


static void _g_slist_free_g_free (GSList* self) {
	g_slist_foreach (self, (GFunc) g_free, NULL);
	g_slist_free (self);
}


void roxenlauncher_application_save_list (void) {
	GError * _inner_error_;
	GSList* list;
	_inner_error_ = NULL;
	list = roxenlauncher_application_to_gconf_list ();
	{
		GConfClient* cli;
		char* key;
		cli = _g_object_ref0 (gconf_client_get_default ());
		key = g_strdup (ROXENLAUNCHER_APP_GCONF_ROOT "settings/applications");
		gconf_client_set_list (cli, key, GCONF_VALUE_STRING, list, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (cli);
			_g_free0 (key);
			goto __catch6_g_error;
			goto __finally6;
		}
		_g_object_unref0 (cli);
		_g_free0 (key);
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:178: Failed to save applications to GConf: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally6:
	if (_inner_error_ != NULL) {
		__g_slist_free_g_free0 (list);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	__g_slist_free_g_free0 (list);
}


RoxenlauncherApplication* roxenlauncher_application_get_for_mimetype (const char* mimetype) {
	RoxenlauncherApplication* result;
	g_return_val_if_fail (mimetype != NULL, NULL);
	if (roxenlauncher_application_applications == NULL) {
		GeeArrayList* _tmp0_;
		roxenlauncher_application_applications = (_tmp0_ = gee_array_list_new (ROXENLAUNCHER_TYPE_APPLICATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (roxenlauncher_application_applications), _tmp0_);
	}
	if (gee_collection_get_size ((GeeCollection*) roxenlauncher_application_applications) == 0) {
		result = NULL;
		return result;
	}
	{
		GeeIterator* _app_it;
		_app_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) roxenlauncher_application_applications);
		while (TRUE) {
			RoxenlauncherApplication* app;
			if (!gee_iterator_next (_app_it)) {
				break;
			}
			app = (RoxenlauncherApplication*) gee_iterator_get (_app_it);
			if (_vala_strcmp0 (app->priv->_mimetype, mimetype) == 0) {
				result = app;
				_g_object_unref0 (_app_it);
				return result;
			}
			_g_object_unref0 (app);
		}
		_g_object_unref0 (_app_it);
	}
	result = NULL;
	return result;
}


GSList* roxenlauncher_application_to_gconf_list (void) {
	GSList* result;
	GSList* list;
	if (roxenlauncher_application_applications == NULL) {
		GeeArrayList* _tmp0_;
		roxenlauncher_application_applications = (_tmp0_ = gee_array_list_new (ROXENLAUNCHER_TYPE_APPLICATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (roxenlauncher_application_applications), _tmp0_);
	}
	list = NULL;
	{
		GeeIterator* _app_it;
		_app_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) roxenlauncher_application_applications);
		while (TRUE) {
			RoxenlauncherApplication* app;
			if (!gee_iterator_next (_app_it)) {
				break;
			}
			app = (RoxenlauncherApplication*) gee_iterator_get (_app_it);
			list = g_slist_append (list, roxenlauncher_application_to_gconf_string (app));
			_g_object_unref0 (app);
		}
		_g_object_unref0 (_app_it);
	}
	result = list;
	return result;
}


static glong string_get_length (const char* self) {
	glong result;
	g_return_val_if_fail (self != NULL, 0L);
	result = g_utf8_strlen (self, -1);
	return result;
}


void roxenlauncher_application_load_from_gconf (void) {
	GError * _inner_error_;
	GConfClient* cli;
	char* key;
	GSList* list;
	_inner_error_ = NULL;
	if (roxenlauncher_application_applications == NULL) {
		GeeArrayList* _tmp0_;
		roxenlauncher_application_applications = (_tmp0_ = gee_array_list_new (ROXENLAUNCHER_TYPE_APPLICATION, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (roxenlauncher_application_applications), _tmp0_);
	}
	cli = _g_object_ref0 (gconf_client_get_default ());
	key = g_strdup (ROXENLAUNCHER_APP_GCONF_ROOT "settings/applications");
	list = NULL;
	{
		GSList* _tmp1_;
		_tmp1_ = gconf_client_get_list (cli, key, GCONF_VALUE_STRING, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch7_g_error;
			goto __finally7;
		}
		list = _tmp1_;
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("application.vala:232: Error getting GConf list for \"%s\": %s", key, e->message);
			_g_error_free0 (e);
		}
	}
	__finally7:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (cli);
		_g_free0 (key);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	if (list != NULL) {
		{
			GSList* s_collection;
			GSList* s_it;
			s_collection = list;
			for (s_it = s_collection; s_it != NULL; s_it = s_it->next) {
				char* s;
				s = g_strdup ((const char*) s_it->data);
				{
					char** _tmp3_;
					gint pts_size;
					gint pts_length1;
					char** _tmp2_;
					char** pts;
					RoxenlauncherApplication* app;
					gboolean _tmp4_ = FALSE;
					pts = (_tmp3_ = _tmp2_ = g_strsplit (s, "::", 0), pts_length1 = _vala_array_length (_tmp2_), pts_size = pts_length1, _tmp3_);
					app = roxenlauncher_application_new (pts[0], pts[1], pts[2], "");
					if (pts_length1 > 3) {
						_tmp4_ = string_get_length (pts[3]) > 0;
					} else {
						_tmp4_ = FALSE;
					}
					if (_tmp4_) {
						roxenlauncher_application_set_arguments (app, pts[3]);
					}
					gee_abstract_collection_add ((GeeAbstractCollection*) roxenlauncher_application_applications, app);
					_g_free0 (s);
					pts = (_vala_array_free (pts, pts_length1, (GDestroyNotify) g_free), NULL);
					_g_object_unref0 (app);
				}
			}
		}
	}
	_g_object_unref0 (cli);
	_g_free0 (key);
}


RoxenlauncherApplication* roxenlauncher_application_construct (GType object_type, const char* name, const char* command, const char* mimetype, const char* arguments) {
	RoxenlauncherApplication * self;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (command != NULL, NULL);
	g_return_val_if_fail (mimetype != NULL, NULL);
	g_return_val_if_fail (arguments != NULL, NULL);
	self = (RoxenlauncherApplication*) g_object_new (object_type, NULL);
	roxenlauncher_application_set_name (self, name);
	roxenlauncher_application_set_command (self, command);
	roxenlauncher_application_set_mimetype (self, mimetype);
	roxenlauncher_application_set_arguments (self, arguments);
	return self;
}


RoxenlauncherApplication* roxenlauncher_application_new (const char* name, const char* command, const char* mimetype, const char* arguments) {
	return roxenlauncher_application_construct (ROXENLAUNCHER_TYPE_APPLICATION, name, command, mimetype, arguments);
}


char* roxenlauncher_application_to_gconf_string (RoxenlauncherApplication* self) {
	char* result;
	char* _tmp4_;
	char* _tmp3_;
	char* _tmp2_;
	char* _tmp1_;
	char* _tmp0_;
	char* _tmp5_;
	g_return_val_if_fail (self != NULL, NULL);
	result = (_tmp5_ = g_strconcat (_tmp4_ = g_strconcat (_tmp3_ = g_strconcat (_tmp2_ = g_strconcat (_tmp1_ = g_strconcat (_tmp0_ = g_strconcat (self->priv->_name, "::", NULL), self->priv->_command, NULL), "::", NULL), self->priv->_mimetype, NULL), "::", NULL), self->priv->_arguments, NULL), _g_free0 (_tmp4_), _g_free0 (_tmp3_), _g_free0 (_tmp2_), _g_free0 (_tmp1_), _g_free0 (_tmp0_), _tmp5_);
	return result;
}


const char* roxenlauncher_application_get_name (RoxenlauncherApplication* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_name;
	return result;
}


void roxenlauncher_application_set_name (RoxenlauncherApplication* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_name), _tmp0_);
	g_object_notify ((GObject *) self, "name");
}


const char* roxenlauncher_application_get_command (RoxenlauncherApplication* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_command;
	return result;
}


void roxenlauncher_application_set_command (RoxenlauncherApplication* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_command = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_command), _tmp0_);
	g_object_notify ((GObject *) self, "command");
}


const char* roxenlauncher_application_get_mimetype (RoxenlauncherApplication* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_mimetype;
	return result;
}


void roxenlauncher_application_set_mimetype (RoxenlauncherApplication* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_mimetype = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_mimetype), _tmp0_);
	g_object_notify ((GObject *) self, "mimetype");
}


const char* roxenlauncher_application_get_arguments (RoxenlauncherApplication* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_arguments;
	return result;
}


void roxenlauncher_application_set_arguments (RoxenlauncherApplication* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_arguments = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_arguments), _tmp0_);
	g_object_notify ((GObject *) self, "arguments");
}


static void roxenlauncher_application_class_init (RoxenlauncherApplicationClass * klass) {
	roxenlauncher_application_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (RoxenlauncherApplicationPrivate));
	G_OBJECT_CLASS (klass)->get_property = roxenlauncher_application_get_property;
	G_OBJECT_CLASS (klass)->set_property = roxenlauncher_application_set_property;
	G_OBJECT_CLASS (klass)->finalize = roxenlauncher_application_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ROXENLAUNCHER_APPLICATION_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ROXENLAUNCHER_APPLICATION_COMMAND, g_param_spec_string ("command", "command", "command", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ROXENLAUNCHER_APPLICATION_MIMETYPE, g_param_spec_string ("mimetype", "mimetype", "mimetype", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ROXENLAUNCHER_APPLICATION_ARGUMENTS, g_param_spec_string ("arguments", "arguments", "arguments", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void roxenlauncher_application_instance_init (RoxenlauncherApplication * self) {
	self->priv = ROXENLAUNCHER_APPLICATION_GET_PRIVATE (self);
}


static void roxenlauncher_application_finalize (GObject* obj) {
	RoxenlauncherApplication * self;
	self = ROXENLAUNCHER_APPLICATION (obj);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_command);
	_g_free0 (self->priv->_mimetype);
	_g_free0 (self->priv->_arguments);
	G_OBJECT_CLASS (roxenlauncher_application_parent_class)->finalize (obj);
}


GType roxenlauncher_application_get_type (void) {
	static GType roxenlauncher_application_type_id = 0;
	if (roxenlauncher_application_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (RoxenlauncherApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) roxenlauncher_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RoxenlauncherApplication), 0, (GInstanceInitFunc) roxenlauncher_application_instance_init, NULL };
		roxenlauncher_application_type_id = g_type_register_static (G_TYPE_OBJECT, "RoxenlauncherApplication", &g_define_type_info, 0);
	}
	return roxenlauncher_application_type_id;
}


static void roxenlauncher_application_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	RoxenlauncherApplication * self;
	self = ROXENLAUNCHER_APPLICATION (object);
	switch (property_id) {
		case ROXENLAUNCHER_APPLICATION_NAME:
		g_value_set_string (value, roxenlauncher_application_get_name (self));
		break;
		case ROXENLAUNCHER_APPLICATION_COMMAND:
		g_value_set_string (value, roxenlauncher_application_get_command (self));
		break;
		case ROXENLAUNCHER_APPLICATION_MIMETYPE:
		g_value_set_string (value, roxenlauncher_application_get_mimetype (self));
		break;
		case ROXENLAUNCHER_APPLICATION_ARGUMENTS:
		g_value_set_string (value, roxenlauncher_application_get_arguments (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void roxenlauncher_application_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	RoxenlauncherApplication * self;
	self = ROXENLAUNCHER_APPLICATION (object);
	switch (property_id) {
		case ROXENLAUNCHER_APPLICATION_NAME:
		roxenlauncher_application_set_name (self, g_value_get_string (value));
		break;
		case ROXENLAUNCHER_APPLICATION_COMMAND:
		roxenlauncher_application_set_command (self, g_value_get_string (value));
		break;
		case ROXENLAUNCHER_APPLICATION_MIMETYPE:
		roxenlauncher_application_set_mimetype (self, g_value_get_string (value));
		break;
		case ROXENLAUNCHER_APPLICATION_ARGUMENTS:
		roxenlauncher_application_set_arguments (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




