/* launcherfile.c generated by valac, the Vala compiler
 * generated from launcherfile.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: t; c-basic-offset: 2; tab-width: 2 -*- */
/*
 * launcherfile.vala
 * Copyright (C) Pontus Östlund 2009 <pontus@poppa.se>
 *
 * This file is part of Roxen Application Launcher (RAL)
 * 
 * RAL is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * RAL is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with RAL.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gee.h>
#include <glib/gi18n-lib.h>
#include <config.h>
#include <time.h>
#include <math.h>
#include <glib/gstdio.h>


#define TYPE_LAUNCHER_FILE (launcher_file_get_type ())
#define LAUNCHER_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LAUNCHER_FILE, LauncherFile))
#define LAUNCHER_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LAUNCHER_FILE, LauncherFileClass))
#define IS_LAUNCHER_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LAUNCHER_FILE))
#define IS_LAUNCHER_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LAUNCHER_FILE))
#define LAUNCHER_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LAUNCHER_FILE, LauncherFileClass))

typedef struct _LauncherFile LauncherFile;
typedef struct _LauncherFileClass LauncherFileClass;
typedef struct _LauncherFilePrivate LauncherFilePrivate;

#define ROXENLAUNCHER_TYPE_DATE_TIME (roxenlauncher_date_time_get_type ())
#define ROXENLAUNCHER_DATE_TIME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTime))
#define ROXENLAUNCHER_DATE_TIME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTimeClass))
#define ROXENLAUNCHER_IS_DATE_TIME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_DATE_TIME))
#define ROXENLAUNCHER_IS_DATE_TIME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_DATE_TIME))
#define ROXENLAUNCHER_DATE_TIME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTimeClass))

typedef struct _RoxenlauncherDateTime RoxenlauncherDateTime;
typedef struct _RoxenlauncherDateTimeClass RoxenlauncherDateTimeClass;

#define ROXENLAUNCHER_TYPE_APPLICATION (roxenlauncher_application_get_type ())
#define ROXENLAUNCHER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplication))
#define ROXENLAUNCHER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))
#define ROXENLAUNCHER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))

typedef struct _RoxenlauncherApplication RoxenlauncherApplication;
typedef struct _RoxenlauncherApplicationClass RoxenlauncherApplicationClass;

#define LAUNCHER_FILE_TYPE_STATUSES (launcher_file_statuses_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define ROXENLAUNCHER_TYPE_MAIN_WINDOW (roxenlauncher_main_window_get_type ())
#define ROXENLAUNCHER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindow))
#define ROXENLAUNCHER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowClass))
#define ROXENLAUNCHER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW))
#define ROXENLAUNCHER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_MAIN_WINDOW))
#define ROXENLAUNCHER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowClass))

typedef struct _RoxenlauncherMainWindow RoxenlauncherMainWindow;
typedef struct _RoxenlauncherMainWindowClass RoxenlauncherMainWindowClass;

#define ROXENLAUNCHER_HTTP_TYPE_REQUEST (roxenlauncher_http_request_get_type ())
#define ROXENLAUNCHER_HTTP_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_HTTP_TYPE_REQUEST, RoxenlauncherHTTPRequest))
#define ROXENLAUNCHER_HTTP_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_HTTP_TYPE_REQUEST, RoxenlauncherHTTPRequestClass))
#define ROXENLAUNCHER_HTTP_IS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_HTTP_TYPE_REQUEST))
#define ROXENLAUNCHER_HTTP_IS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_HTTP_TYPE_REQUEST))
#define ROXENLAUNCHER_HTTP_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_HTTP_TYPE_REQUEST, RoxenlauncherHTTPRequestClass))

typedef struct _RoxenlauncherHTTPRequest RoxenlauncherHTTPRequest;
typedef struct _RoxenlauncherHTTPRequestClass RoxenlauncherHTTPRequestClass;

#define ROXENLAUNCHER_HTTP_TYPE_RESPONSE (roxenlauncher_http_response_get_type ())
#define ROXENLAUNCHER_HTTP_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_HTTP_TYPE_RESPONSE, RoxenlauncherHTTPResponse))
#define ROXENLAUNCHER_HTTP_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_HTTP_TYPE_RESPONSE, RoxenlauncherHTTPResponseClass))
#define ROXENLAUNCHER_HTTP_IS_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_HTTP_TYPE_RESPONSE))
#define ROXENLAUNCHER_HTTP_IS_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_HTTP_TYPE_RESPONSE))
#define ROXENLAUNCHER_HTTP_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_HTTP_TYPE_RESPONSE, RoxenlauncherHTTPResponseClass))

typedef struct _RoxenlauncherHTTPResponse RoxenlauncherHTTPResponse;
typedef struct _RoxenlauncherHTTPResponseClass RoxenlauncherHTTPResponseClass;

struct _LauncherFile {
	GObject parent_instance;
	LauncherFilePrivate * priv;
};

struct _LauncherFileClass {
	GObjectClass parent_class;
};

struct _LauncherFilePrivate {
	char* _rawdata;
	char* _schema;
	char* _host;
	char* _port;
	char* _auth_cookie;
	char* _content_type;
	char* _sb_params;
	char* _id;
	char* _path;
	char* _local_dir;
	char* _local_file;
	gint _status;
	gboolean _is_downloading;
	gboolean _is_uploading;
	RoxenlauncherDateTime* _last_upload;
	RoxenlauncherDateTime* _last_download;
	RoxenlauncherDateTime* _last_modified;
	RoxenlauncherDateTime* _age;
	RoxenlauncherApplication* _application;
	GFileMonitor* monitor;
	GFileMonitorEvent previous_event;
};

typedef enum  {
	LAUNCHER_FILE_STATUSES_DUMMY_STATUS,
	LAUNCHER_FILE_STATUSES_NOT_DOWNLOADED,
	LAUNCHER_FILE_STATUSES_DOWNLOADED,
	LAUNCHER_FILE_STATUSES_UPLOADED,
	LAUNCHER_FILE_STATUSES_NOT_UPLOADED,
	LAUNCHER_FILE_STATUSES_DOWNLOADING,
	LAUNCHER_FILE_STATUSES_UPLOADING,
	LAUNCHER_FILE_STATUSES_NOT_CHANGED
} LauncherFileStatuses;

typedef enum  {
	ROXENLAUNCHER_ROXEN_ERROR_BAD_LAUNCHERFILE,
	ROXENLAUNCHER_ROXEN_ERROR_GENERIC
} RoxenlauncherRoxenError;
#define ROXENLAUNCHER_ROXEN_ERROR roxenlauncher_roxen_error_quark ()

static GeeArrayList* launcher_file_launcherfiles;
static GeeArrayList* launcher_file_launcherfiles = NULL;
extern RoxenlauncherMainWindow* win;
static gpointer launcher_file_parent_class = NULL;

GType launcher_file_get_type (void);
GType roxenlauncher_date_time_get_type (void);
GType roxenlauncher_application_get_type (void);
#define LAUNCHER_FILE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LAUNCHER_FILE, LauncherFilePrivate))
enum  {
	LAUNCHER_FILE_DUMMY_PROPERTY,
	LAUNCHER_FILE_RAWDATA,
	LAUNCHER_FILE_SCHEMA,
	LAUNCHER_FILE_HOST,
	LAUNCHER_FILE_PORT,
	LAUNCHER_FILE_AUTH_COOKIE,
	LAUNCHER_FILE_CONTENT_TYPE,
	LAUNCHER_FILE_SB_PARAMS,
	LAUNCHER_FILE_ID,
	LAUNCHER_FILE_PATH,
	LAUNCHER_FILE_LOCAL_DIR,
	LAUNCHER_FILE_LOCAL_FILE,
	LAUNCHER_FILE_STATUS,
	LAUNCHER_FILE_IS_DOWNLOADING,
	LAUNCHER_FILE_IS_UPLOADING,
	LAUNCHER_FILE_LAST_UPLOAD,
	LAUNCHER_FILE_LAST_DOWNLOAD,
	LAUNCHER_FILE_LAST_MODIFIED,
	LAUNCHER_FILE_AGE,
	LAUNCHER_FILE_APPLICATION
};
static GType launcher_file_statuses_get_type (void);
GeeArrayList* launcher_file_get_files (void);
GeeArrayList* launcher_file_get_reversed_files (void);
char* launcher_file_get_uri (LauncherFile* self);
void launcher_file_add_file (LauncherFile* lf);
void launcher_file_remove_file (LauncherFile* file);
LauncherFile* launcher_file_find_by_uri (const char* uri);
void launcher_file_clear_files (void);
char* roxenlauncher_getdir (const char* which);
GQuark roxenlauncher_roxen_error_quark (void);
LauncherFile* launcher_file_new_from_existing (const char* id, const char* data, GError** error);
LauncherFile* launcher_file_construct_from_existing (GType object_type, const char* id, const char* data, GError** error);
void launcher_file_load_existing (void);
char** roxenlauncher_slice (char** s, int s_length1, guint from, guint to, int* result_length1, GError** error);
char* roxenlauncher_implode (char** s, int s_length1, const char* glue);
const char* launcher_file_get_rawdata (LauncherFile* self);
void launcher_file_download (LauncherFile* self, gboolean do_launch_editor);
LauncherFile* launcher_file_new (const char* data, GError** error);
LauncherFile* launcher_file_construct (GType object_type, const char* data, GError** error);
gboolean launcher_file_incomming (const char* data, LauncherFile** file, GError** error);
static void launcher_file_set_rawdata (LauncherFile* self, const char* value);
static void launcher_file_init (LauncherFile* self, const char* _id, GError** error);
static void launcher_file_set_id (LauncherFile* self, const char* value);
static char* launcher_file_load (LauncherFile* self);
gint launcher_file_get_status (LauncherFile* self);
char* launcher_file_status_as_string (LauncherFile* self);
const char* launcher_file_get_schema (LauncherFile* self);
const char* launcher_file_get_host (LauncherFile* self);
const char* launcher_file_get_port (LauncherFile* self);
const char* launcher_file_get_path (LauncherFile* self);
const char* launcher_file_get_auth_cookie (LauncherFile* self);
const char* launcher_file_get_sb_params (LauncherFile* self);
char* launcher_file_get_cookie (LauncherFile* self);
static void launcher_file_set_application (LauncherFile* self, RoxenlauncherApplication* value);
void launcher_file_unset_application (LauncherFile* self);
const char* launcher_file_get_local_dir (LauncherFile* self);
gboolean launcher_file_delete (LauncherFile* self);
RoxenlauncherApplication* launcher_file_get_application (LauncherFile* self);
RoxenlauncherApplication* roxenlauncher_application_get_for_mimetype (const char* mimetype);
const char* launcher_file_get_content_type (LauncherFile* self);
GType roxenlauncher_main_window_get_type (void);
RoxenlauncherApplication* roxenlauncher_main_window_editor_dialog_new (RoxenlauncherMainWindow* self, const char* content_type);
gboolean roxenlauncher_file_exists (const char* file);
const char* launcher_file_get_local_file (LauncherFile* self);
const char* roxenlauncher_application_get_command (RoxenlauncherApplication* self);
const char* roxenlauncher_application_get_arguments (RoxenlauncherApplication* self);
static void launcher_file_set_monitor (LauncherFile* self);
void launcher_file_launch_editor (LauncherFile* self);
static void launcher_file_on_file_changed (LauncherFile* self, GFile* f, GFile* other, GFileMonitorEvent e);
static void _launcher_file_on_file_changed_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self);
static void launcher_file_stop_monitor (LauncherFile* self);
static void launcher_file_win_set_status (LauncherFile* self, gint st);
GType roxenlauncher_http_request_get_type (void);
static RoxenlauncherHTTPRequest* launcher_file_get_http_client (LauncherFile* self);
GType roxenlauncher_http_response_get_type (void);
RoxenlauncherHTTPResponse* roxenlauncher_http_request_do_method (RoxenlauncherHTTPRequest* self, char* method, const char* data);
gint roxenlauncher_http_response_get_status_code (RoxenlauncherHTTPResponse* self);
static gboolean launcher_file_write_download_data (LauncherFile* self, RoxenlauncherHTTPResponse* resp);
static void launcher_file_save (LauncherFile* self);
static gboolean _lambda6_ (LauncherFile* self);
static gboolean __lambda6__gsource_func (gpointer self);
char* roxenlauncher_file_get_contents (const char* file);
RoxenlauncherDateTime* roxenlauncher_date_time_now (void);
static void launcher_file_set_last_upload (LauncherFile* self, RoxenlauncherDateTime* value);
static gboolean _lambda9_ (LauncherFile* self);
static gboolean __lambda9__gsource_func (gpointer self);
void launcher_file_upload (LauncherFile* self);
guint8* roxenlauncher_http_response_get_raw_data (RoxenlauncherHTTPResponse* self, int* result_length1);
static void launcher_file_set_status (LauncherFile* self, gint value);
void roxenlauncher_main_window_set_file_status (RoxenlauncherMainWindow* self, LauncherFile* lf, const char* status);
static gboolean _lambda4_ (LauncherFile* self);
static gboolean __lambda4__gsource_func (gpointer self);
RoxenlauncherHTTPRequest* roxenlauncher_http_request_new (const char* the_uri);
RoxenlauncherHTTPRequest* roxenlauncher_http_request_construct (GType object_type, const char* the_uri);
GeeHashMap* roxenlauncher_http_request_get_headers (RoxenlauncherHTTPRequest* self);
#define ROXENLAUNCHER_APP_VERSION VERSION
#define ROXENLAUNCHER_APP_USER_AGENT "Roxen Application Launcher for Linux (" ROXENLAUNCHER_APP_VERSION ")"
void roxenlauncher_http_request_set_keep_alive (RoxenlauncherHTTPRequest* self, gboolean value);
static void launcher_file_set_schema (LauncherFile* self, const char* value);
static void launcher_file_set_host (LauncherFile* self, const char* value);
static void launcher_file_set_port (LauncherFile* self, const char* value);
static void launcher_file_set_auth_cookie (LauncherFile* self, const char* value);
static void launcher_file_set_path (LauncherFile* self, const char* value);
static void launcher_file_set_content_type (LauncherFile* self, const char* value);
static void launcher_file_set_sb_params (LauncherFile* self, const char* value);
RoxenlauncherDateTime* roxenlauncher_date_time_unixtime (time_t timestamp);
RoxenlauncherDateTime* roxenlauncher_date_time_new (guint year, guint month, guint date, guint hour, guint minute, guint second);
RoxenlauncherDateTime* roxenlauncher_date_time_construct (GType object_type, guint year, guint month, guint date, guint hour, guint minute, guint second);
static void launcher_file_randid (LauncherFile* self);
const char* launcher_file_get_id (LauncherFile* self);
static void launcher_file_set_local_dir (LauncherFile* self, const char* value);
static void launcher_file_set_local_file (LauncherFile* self, const char* value);
void roxenlauncher_main_window_add_launcher_file (RoxenlauncherMainWindow* self, LauncherFile* lf);
static gboolean _lambda2_ (LauncherFile* self);
static gboolean __lambda2__gsource_func (gpointer self);
RoxenlauncherDateTime* roxenlauncher_filemtime (const char* path);
static void launcher_file_set_last_modified (LauncherFile* self, RoxenlauncherDateTime* value);
RoxenlauncherDateTime* roxenlauncher_filectime (const char* path);
static void launcher_file_set_age (LauncherFile* self, RoxenlauncherDateTime* value);
char* roxenlauncher_trim (const char* s, const char* chars);
static void _vala_array_add1 (char*** array, int* length, int* size, char* value);
static void launcher_file_create_dir (LauncherFile* self);
RoxenlauncherDateTime* launcher_file_get_last_upload (LauncherFile* self);
time_t roxenlauncher_date_time_to_unixtime (RoxenlauncherDateTime* self);
gboolean launcher_file_get_is_downloading (LauncherFile* self);
static void launcher_file_set_is_downloading (LauncherFile* self, gboolean value);
gboolean launcher_file_get_is_uploading (LauncherFile* self);
static void launcher_file_set_is_uploading (LauncherFile* self, gboolean value);
RoxenlauncherDateTime* launcher_file_get_last_download (LauncherFile* self);
static void launcher_file_set_last_download (LauncherFile* self, RoxenlauncherDateTime* value);
RoxenlauncherDateTime* launcher_file_get_last_modified (LauncherFile* self);
RoxenlauncherDateTime* launcher_file_get_age (LauncherFile* self);
static void launcher_file_finalize (GObject* obj);
static void launcher_file_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void launcher_file_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);
static int _vala_strcmp0 (const char * str1, const char * str2);




static GType launcher_file_statuses_get_type (void) {
	static GType launcher_file_statuses_type_id = 0;
	if (G_UNLIKELY (launcher_file_statuses_type_id == 0)) {
		static const GEnumValue values[] = {{LAUNCHER_FILE_STATUSES_DUMMY_STATUS, "LAUNCHER_FILE_STATUSES_DUMMY_STATUS", "dummy-status"}, {LAUNCHER_FILE_STATUSES_NOT_DOWNLOADED, "LAUNCHER_FILE_STATUSES_NOT_DOWNLOADED", "not-downloaded"}, {LAUNCHER_FILE_STATUSES_DOWNLOADED, "LAUNCHER_FILE_STATUSES_DOWNLOADED", "downloaded"}, {LAUNCHER_FILE_STATUSES_UPLOADED, "LAUNCHER_FILE_STATUSES_UPLOADED", "uploaded"}, {LAUNCHER_FILE_STATUSES_NOT_UPLOADED, "LAUNCHER_FILE_STATUSES_NOT_UPLOADED", "not-uploaded"}, {LAUNCHER_FILE_STATUSES_DOWNLOADING, "LAUNCHER_FILE_STATUSES_DOWNLOADING", "downloading"}, {LAUNCHER_FILE_STATUSES_UPLOADING, "LAUNCHER_FILE_STATUSES_UPLOADING", "uploading"}, {LAUNCHER_FILE_STATUSES_NOT_CHANGED, "LAUNCHER_FILE_STATUSES_NOT_CHANGED", "not-changed"}, {0, NULL, NULL}};
		launcher_file_statuses_type_id = g_enum_register_static ("LauncherFileStatuses", values);
	}
	return launcher_file_statuses_type_id;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GeeArrayList* launcher_file_get_files (void) {
	GeeArrayList* result;
	result = _g_object_ref0 (launcher_file_launcherfiles);
	return result;
}


GeeArrayList* launcher_file_get_reversed_files (void) {
	GeeArrayList* result;
	GeeArrayList* nlist;
	nlist = gee_array_list_new (TYPE_LAUNCHER_FILE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
	{
		gint i;
		i = gee_collection_get_size ((GeeCollection*) launcher_file_launcherfiles);
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				LauncherFile* _tmp1_;
				if (!_tmp0_) {
				}
				_tmp0_ = FALSE;
				if (!(i > 0)) {
					break;
				}
				gee_abstract_collection_add ((GeeAbstractCollection*) nlist, _tmp1_ = (LauncherFile*) gee_abstract_list_get ((GeeAbstractList*) launcher_file_launcherfiles, i = i - 1));
				_g_object_unref0 (_tmp1_);
			}
		}
	}
	result = nlist;
	return result;
}


void launcher_file_add_file (LauncherFile* lf) {
	g_return_if_fail (lf != NULL);
	{
		GeeIterator* _l_it;
		_l_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) launcher_file_launcherfiles);
		while (TRUE) {
			LauncherFile* l;
			char* _tmp1_;
			char* _tmp0_;
			gboolean _tmp2_;
			if (!gee_iterator_next (_l_it)) {
				break;
			}
			l = (LauncherFile*) gee_iterator_get (_l_it);
			if ((_tmp2_ = _vala_strcmp0 (_tmp0_ = launcher_file_get_uri (l), _tmp1_ = launcher_file_get_uri (lf)) == 0, _g_free0 (_tmp1_), _g_free0 (_tmp0_), _tmp2_)) {
				g_message ("launcherfile.vala:63: Launcher file exists. Skip adding!");
				_g_object_unref0 (l);
				_g_object_unref0 (_l_it);
				return;
			}
			_g_object_unref0 (l);
		}
		_g_object_unref0 (_l_it);
	}
	gee_abstract_collection_add ((GeeAbstractCollection*) launcher_file_launcherfiles, lf);
}


void launcher_file_remove_file (LauncherFile* file) {
	g_return_if_fail (file != NULL);
	gee_abstract_collection_remove ((GeeAbstractCollection*) launcher_file_launcherfiles, file);
}


LauncherFile* launcher_file_find_by_uri (const char* uri) {
	LauncherFile* result;
	g_return_val_if_fail (uri != NULL, NULL);
	{
		GeeIterator* _lf_it;
		_lf_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) launcher_file_launcherfiles);
		while (TRUE) {
			LauncherFile* lf;
			char* _tmp0_;
			gboolean _tmp1_;
			if (!gee_iterator_next (_lf_it)) {
				break;
			}
			lf = (LauncherFile*) gee_iterator_get (_lf_it);
			if ((_tmp1_ = _vala_strcmp0 (_tmp0_ = launcher_file_get_uri (lf), uri) == 0, _g_free0 (_tmp0_), _tmp1_)) {
				result = lf;
				_g_object_unref0 (_lf_it);
				return result;
			}
			_g_object_unref0 (lf);
		}
		_g_object_unref0 (_lf_it);
	}
	result = NULL;
	return result;
}


void launcher_file_clear_files (void) {
	gee_abstract_collection_clear ((GeeAbstractCollection*) launcher_file_launcherfiles);
}


void launcher_file_load_existing (void) {
	GError * _inner_error_;
	char* p;
	_inner_error_ = NULL;
	if (launcher_file_launcherfiles == NULL) {
		GeeArrayList* _tmp0_;
		launcher_file_launcherfiles = (_tmp0_ = gee_array_list_new (TYPE_LAUNCHER_FILE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (launcher_file_launcherfiles), _tmp0_);
	}
	p = roxenlauncher_getdir ("files");
	{
		GFile* _tmp1_;
		GFileEnumerator* _tmp2_;
		GFileEnumerator* f;
		GFileInfo* fi;
		f = (_tmp2_ = g_file_enumerate_children (_tmp1_ = g_file_new_for_path (p), "standard::name", G_FILE_QUERY_INFO_NONE, NULL, &_inner_error_), _g_object_unref0 (_tmp1_), _tmp2_);
		if (_inner_error_ != NULL) {
			goto __catch12_g_error;
			goto __finally12;
		}
		fi = NULL;
		while (TRUE) {
			GFileInfo* _tmp3_;
			GFileInfo* _tmp4_;
			LauncherFile* lf;
			_tmp3_ = g_file_enumerator_next_file (f, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (f);
				_g_object_unref0 (fi);
				goto __catch12_g_error;
				goto __finally12;
			}
			if (!((fi = (_tmp4_ = _tmp3_, _g_object_unref0 (fi), _tmp4_)) != NULL)) {
				break;
			}
			lf = launcher_file_new_from_existing (g_file_info_get_name (fi), NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (f);
				_g_object_unref0 (fi);
				goto __catch12_g_error;
				goto __finally12;
			}
			gee_abstract_collection_add ((GeeAbstractCollection*) launcher_file_launcherfiles, lf);
			_g_object_unref0 (lf);
		}
		_g_object_unref0 (f);
		_g_object_unref0 (fi);
	}
	goto __finally12;
	__catch12_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("launcherfile.vala:125: Failed to load launcher files: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally12:
	if (_inner_error_ != NULL) {
		_g_free0 (p);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (p);
}


gboolean launcher_file_incomming (const char* data, LauncherFile** file, GError** error) {
	gboolean result;
	GError * _inner_error_;
	char** _tmp1_;
	gint s_size;
	gint s_length1;
	char** _tmp0_;
	char** s;
	char** _tmp4_;
	gint _tmp3__size;
	gint _tmp3__length1;
	gint _tmp2_;
	char** _tmp3_;
	gint _tmp5__length1;
	char** _tmp5_;
	char* _tmp6_;
	char* ss;
	LauncherFile* _tmp17_;
	LauncherFile* _tmp18_;
	g_return_val_if_fail (data != NULL, FALSE);
	if (file != NULL) {
		*file = NULL;
	}
	_inner_error_ = NULL;
	s = (_tmp1_ = _tmp0_ = g_strsplit (data, "\r\n", 0), s_length1 = _vala_array_length (_tmp0_), s_size = s_length1, _tmp1_);
	if (s_length1 < 6) {
		_inner_error_ = g_error_new_literal (ROXENLAUNCHER_ROXEN_ERROR, ROXENLAUNCHER_ROXEN_ERROR_BAD_LAUNCHERFILE, _ ("Bad data in launcher file!"));
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == ROXENLAUNCHER_ROXEN_ERROR) {
				g_propagate_error (error, _inner_error_);
				s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
				return FALSE;
			} else {
				s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
				g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
				g_clear_error (&_inner_error_);
				return FALSE;
			}
		}
	}
	_tmp3_ = (_tmp4_ = roxenlauncher_slice (s, s_length1, (guint) 0, (guint) 6, &_tmp2_, &_inner_error_), _tmp3__length1 = _tmp2_, _tmp3__size = _tmp3__length1, _tmp4_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == ROXENLAUNCHER_ROXEN_ERROR) {
			g_propagate_error (error, _inner_error_);
			s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
			return FALSE;
		} else {
			s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
	}
	ss = (_tmp6_ = roxenlauncher_implode ((_tmp5_ = _tmp3_, _tmp5__length1 = _tmp3__length1, _tmp5_), _tmp3__length1, "\r\n"), _tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) g_free), NULL), _tmp6_);
	{
		GeeIterator* _lf_it;
		_lf_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) launcher_file_launcherfiles);
		while (TRUE) {
			LauncherFile* lf;
			char** _tmp13_;
			gint _tmp12__size;
			gint _tmp12__length1;
			gint _tmp10_;
			char** _tmp9_;
			gint _tmp8__length1;
			char** _tmp8_;
			char** _tmp7_;
			char** _tmp11_;
			char** _tmp12_;
			gint _tmp14__length1;
			char** _tmp14_;
			char* _tmp15_;
			char* raw;
			if (!gee_iterator_next (_lf_it)) {
				break;
			}
			lf = (LauncherFile*) gee_iterator_get (_lf_it);
			_tmp12_ = (_tmp13_ = (_tmp11_ = (_tmp9_ = (_tmp8_ = _tmp7_ = g_strsplit (lf->priv->_rawdata, "\r\n", 0), _tmp8__length1 = _vala_array_length (_tmp7_), _tmp8_), roxenlauncher_slice (_tmp9_, _vala_array_length (_tmp7_), (guint) 0, (guint) 6, &_tmp10_, &_inner_error_)), _tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL), _tmp11_), _tmp12__length1 = _tmp10_, _tmp12__size = _tmp12__length1, _tmp13_);
			if (_inner_error_ != NULL) {
				if (_inner_error_->domain == ROXENLAUNCHER_ROXEN_ERROR) {
					g_propagate_error (error, _inner_error_);
					_g_object_unref0 (lf);
					_g_object_unref0 (_lf_it);
					s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (ss);
					return FALSE;
				} else {
					_g_object_unref0 (lf);
					_g_object_unref0 (_lf_it);
					s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (ss);
					g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
					g_clear_error (&_inner_error_);
					return FALSE;
				}
			}
			raw = (_tmp15_ = roxenlauncher_implode ((_tmp14_ = _tmp12_, _tmp14__length1 = _tmp12__length1, _tmp14_), _tmp12__length1, "\r\n"), _tmp14_ = (_vala_array_free (_tmp14_, _tmp14__length1, (GDestroyNotify) g_free), NULL), _tmp15_);
			if (_vala_strcmp0 (raw, ss) == 0) {
				LauncherFile* _tmp16_;
				*file = (_tmp16_ = _g_object_ref0 (lf), _g_object_unref0 (*file), _tmp16_);
				launcher_file_download (*file, TRUE);
				result = FALSE;
				_g_object_unref0 (lf);
				_g_free0 (raw);
				_g_object_unref0 (_lf_it);
				s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (ss);
				return result;
			}
			_g_object_unref0 (lf);
			_g_free0 (raw);
		}
		_g_object_unref0 (_lf_it);
	}
	_tmp17_ = launcher_file_new (data, &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == ROXENLAUNCHER_ROXEN_ERROR) {
			g_propagate_error (error, _inner_error_);
			s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (ss);
			return FALSE;
		} else {
			s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (ss);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
	}
	*file = (_tmp18_ = _tmp17_, _g_object_unref0 (*file), _tmp18_);
	result = TRUE;
	s = (_vala_array_free (s, s_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (ss);
	return result;
}


LauncherFile* launcher_file_construct (GType object_type, const char* data, GError** error) {
	GError * _inner_error_;
	LauncherFile * self;
	g_return_val_if_fail (data != NULL, NULL);
	_inner_error_ = NULL;
	self = (LauncherFile*) g_object_new (object_type, NULL);
	launcher_file_set_rawdata (self, data);
	launcher_file_init (self, NULL, &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == ROXENLAUNCHER_ROXEN_ERROR) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	return self;
}


LauncherFile* launcher_file_new (const char* data, GError** error) {
	return launcher_file_construct (TYPE_LAUNCHER_FILE, data, error);
}


LauncherFile* launcher_file_construct_from_existing (GType object_type, const char* id, const char* data, GError** error) {
	GError * _inner_error_;
	LauncherFile * self;
	char* _tmp0_;
	g_return_val_if_fail (id != NULL, NULL);
	_inner_error_ = NULL;
	self = (LauncherFile*) g_object_new (object_type, NULL);
	launcher_file_set_id (self, id);
	_tmp0_ = NULL;
	if (data == NULL) {
		char* _tmp1_;
		_tmp0_ = (_tmp1_ = launcher_file_load (self), _g_free0 (_tmp0_), _tmp1_);
	} else {
		char* _tmp2_;
		_tmp0_ = (_tmp2_ = g_strdup (data), _g_free0 (_tmp0_), _tmp2_);
	}
	launcher_file_set_rawdata (self, _tmp0_);
	launcher_file_init (self, id, &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == ROXENLAUNCHER_ROXEN_ERROR) {
			g_propagate_error (error, _inner_error_);
			_g_free0 (_tmp0_);
			return NULL;
		} else {
			_g_free0 (_tmp0_);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_g_free0 (_tmp0_);
	return self;
}


LauncherFile* launcher_file_new_from_existing (const char* id, const char* data, GError** error) {
	return launcher_file_construct_from_existing (TYPE_LAUNCHER_FILE, id, data, error);
}


char* launcher_file_status_as_string (LauncherFile* self) {
	char* result;
	char* s;
	g_return_val_if_fail (self != NULL, NULL);
	s = NULL;
	switch (self->priv->_status) {
		case 1:
		{
			char* _tmp0_;
			s = (_tmp0_ = g_strdup (_ ("Not downloaded")), _g_free0 (s), _tmp0_);
			break;
		}
		case 2:
		{
			char* _tmp1_;
			s = (_tmp1_ = g_strdup (_ ("Downloaded")), _g_free0 (s), _tmp1_);
			break;
		}
		case 3:
		{
			char* _tmp2_;
			s = (_tmp2_ = g_strdup (_ ("Uploaded")), _g_free0 (s), _tmp2_);
			break;
		}
		case 4:
		{
			char* _tmp3_;
			s = (_tmp3_ = g_strdup (_ ("Not uploaded")), _g_free0 (s), _tmp3_);
			break;
		}
		case 5:
		{
			char* _tmp4_;
			s = (_tmp4_ = g_strdup (_ ("Downloading...")), _g_free0 (s), _tmp4_);
			break;
		}
		case 6:
		{
			char* _tmp5_;
			s = (_tmp5_ = g_strdup (_ ("Uploading...")), _g_free0 (s), _tmp5_);
			break;
		}
		case 7:
		{
			char* _tmp6_;
			s = (_tmp6_ = g_strdup (_ ("Not changed")), _g_free0 (s), _tmp6_);
			break;
		}
		default:
		{
			char* _tmp7_;
			s = (_tmp7_ = g_strdup (""), _g_free0 (s), _tmp7_);
			break;
		}
	}
	result = s;
	return result;
}


char* launcher_file_get_uri (LauncherFile* self) {
	char* result;
	char* _tmp0_;
	char* _tmp1_;
	char* s;
	gboolean _tmp2_ = FALSE;
	char* _tmp6_;
	g_return_val_if_fail (self != NULL, NULL);
	s = (_tmp1_ = g_strconcat (_tmp0_ = g_strconcat (self->priv->_schema, "://", NULL), self->priv->_host, NULL), _g_free0 (_tmp0_), _tmp1_);
	if (_vala_strcmp0 (self->priv->_schema, "https") == 0) {
		_tmp2_ = _vala_strcmp0 (self->priv->_port, "443") != 0;
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		char* _tmp3_;
		s = (_tmp3_ = g_strconcat (s, self->priv->_port, NULL), _g_free0 (s), _tmp3_);
	} else {
		gboolean _tmp4_ = FALSE;
		if (_vala_strcmp0 (self->priv->_schema, "http") == 0) {
			_tmp4_ = _vala_strcmp0 (self->priv->_port, "80") != 0;
		} else {
			_tmp4_ = FALSE;
		}
		if (_tmp4_) {
			char* _tmp5_;
			s = (_tmp5_ = g_strconcat (s, self->priv->_port, NULL), _g_free0 (s), _tmp5_);
		}
	}
	s = (_tmp6_ = g_strconcat (s, self->priv->_path, NULL), _g_free0 (s), _tmp6_);
	result = s;
	return result;
}


char* launcher_file_get_cookie (LauncherFile* self) {
	char* result;
	char* _tmp3_;
	char* _tmp2_;
	char* _tmp1_;
	char* _tmp0_;
	char* _tmp4_;
	g_return_val_if_fail (self != NULL, NULL);
	result = (_tmp4_ = g_strconcat (_tmp3_ = g_strconcat (_tmp2_ = g_strconcat (_tmp1_ = g_strconcat (_tmp0_ = g_strconcat ("RoxenACauth=", self->priv->_auth_cookie, NULL), "; ", NULL), "RoxenALparams=\"", NULL), self->priv->_sb_params, NULL), "\"", NULL), _g_free0 (_tmp3_), _g_free0 (_tmp2_), _g_free0 (_tmp1_), _g_free0 (_tmp0_), _tmp4_);
	return result;
}


void launcher_file_unset_application (LauncherFile* self) {
	g_return_if_fail (self != NULL);
	launcher_file_set_application (self, NULL);
}


gboolean launcher_file_delete (LauncherFile* self) {
	gboolean result;
	GError * _inner_error_;
	gboolean retval;
	g_return_val_if_fail (self != NULL, FALSE);
	_inner_error_ = NULL;
	retval = TRUE;
	{
		GFile* _tmp0_;
		GFileEnumerator* _tmp1_;
		GFileEnumerator* dir;
		GFileInfo* fi;
		char* fp;
		GFile* _tmp6_;
		if (self->priv->monitor != NULL) {
			g_file_monitor_cancel (self->priv->monitor);
		}
		dir = (_tmp1_ = g_file_enumerate_children (_tmp0_ = g_file_new_for_path (self->priv->_local_dir), "standard::name", 0, NULL, &_inner_error_), _g_object_unref0 (_tmp0_), _tmp1_);
		if (_inner_error_ != NULL) {
			goto __catch13_g_error;
			goto __finally13;
		}
		fi = NULL;
		fp = NULL;
		while (TRUE) {
			GFileInfo* _tmp2_;
			GFileInfo* _tmp3_;
			char* _tmp4_;
			GFile* _tmp5_;
			_tmp2_ = g_file_enumerator_next_file (dir, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (dir);
				_g_object_unref0 (fi);
				_g_free0 (fp);
				goto __catch13_g_error;
				goto __finally13;
			}
			if (!((fi = (_tmp3_ = _tmp2_, _g_object_unref0 (fi), _tmp3_)) != NULL)) {
				break;
			}
			fp = (_tmp4_ = g_build_filename (self->priv->_local_dir, g_file_info_get_name (fi), NULL), _g_free0 (fp), _tmp4_);
			g_file_delete (_tmp5_ = g_file_new_for_path (fp), NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (dir);
				_g_object_unref0 (fi);
				_g_free0 (fp);
				goto __catch13_g_error;
				goto __finally13;
			}
			_g_object_unref0 (_tmp5_);
		}
		g_file_delete (_tmp6_ = g_file_new_for_path (self->priv->_local_dir), NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (dir);
			_g_object_unref0 (fi);
			_g_free0 (fp);
			goto __catch13_g_error;
			goto __finally13;
		}
		_g_object_unref0 (_tmp6_);
		_g_object_unref0 (dir);
		_g_object_unref0 (fi);
		_g_free0 (fp);
	}
	goto __finally13;
	__catch13_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("launcherfile.vala:311: Failed to delete launcher file: %s!", e->message);
			retval = FALSE;
			_g_error_free0 (e);
		}
	}
	__finally13:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	result = retval;
	return result;
}


static glong string_get_length (const char* self) {
	glong result;
	g_return_val_if_fail (self != NULL, 0L);
	result = g_utf8_strlen (self, -1);
	return result;
}


void launcher_file_launch_editor (LauncherFile* self) {
	GError * _inner_error_;
	char* cmd;
	gboolean _tmp1_ = FALSE;
	char* _tmp6_;
	char* _tmp5_;
	char* _tmp4_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	if (self->priv->_application == NULL) {
		RoxenlauncherApplication* app;
		app = roxenlauncher_application_get_for_mimetype (self->priv->_content_type);
		if (app == NULL) {
			RoxenlauncherApplication* _tmp0_;
			launcher_file_set_application (self, _tmp0_ = roxenlauncher_main_window_editor_dialog_new (win, self->priv->_content_type));
			_g_object_unref0 (_tmp0_);
			if (self->priv->_application == NULL) {
				_g_object_unref0 (app);
				return;
			}
		} else {
			launcher_file_set_application (self, app);
		}
		_g_object_unref0 (app);
	}
	if (!roxenlauncher_file_exists (self->priv->_local_file)) {
		launcher_file_download (self, TRUE);
		return;
	}
	cmd = g_strdup (roxenlauncher_application_get_command (self->priv->_application));
	if (roxenlauncher_application_get_arguments (self->priv->_application) != NULL) {
		_tmp1_ = string_get_length (roxenlauncher_application_get_arguments (self->priv->_application)) > 0;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		char* _tmp3_;
		char* _tmp2_;
		cmd = (_tmp3_ = g_strconcat (cmd, _tmp2_ = g_strconcat (" ", roxenlauncher_application_get_arguments (self->priv->_application), NULL), NULL), _g_free0 (cmd), _tmp3_);
		_g_free0 (_tmp2_);
	}
	cmd = (_tmp6_ = g_strconcat (cmd, _tmp5_ = g_strconcat (_tmp4_ = g_strconcat (" \"", self->priv->_local_file, NULL), "\"", NULL), NULL), _g_free0 (cmd), _tmp6_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp4_);
	{
		launcher_file_set_monitor (self);
		g_spawn_command_line_async (cmd, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch14_g_error;
			goto __finally14;
		}
	}
	goto __finally14;
	__catch14_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("launcherfile.vala:354: Error starting application: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally14:
	if (_inner_error_ != NULL) {
		_g_free0 (cmd);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (cmd);
}


static void _launcher_file_on_file_changed_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self) {
	launcher_file_on_file_changed (self, file, other_file, event_type);
}


static void launcher_file_set_monitor (LauncherFile* self) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	{
		GFile* f;
		GFileMonitor* _tmp0_;
		GFileMonitor* _tmp1_;
		if (self->priv->monitor != NULL) {
			g_file_monitor_cancel (self->priv->monitor);
		}
		f = g_file_new_for_path (self->priv->_local_file);
		_tmp0_ = g_file_monitor_file (f, G_FILE_MONITOR_NONE, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (f);
			goto __catch15_g_error;
			goto __finally15;
		}
		self->priv->monitor = (_tmp1_ = _tmp0_, _g_object_unref0 (self->priv->monitor), _tmp1_);
		g_signal_connect_object (self->priv->monitor, "changed", (GCallback) _launcher_file_on_file_changed_g_file_monitor_changed, self, 0);
		_g_object_unref0 (f);
	}
	goto __finally15;
	__catch15_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("launcherfile.vala:372: Failed to set monitor for \"%s\"", self->priv->_local_file);
			_g_error_free0 (e);
		}
	}
	__finally15:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void launcher_file_stop_monitor (LauncherFile* self) {
	GFileMonitor* _tmp0_;
	g_return_if_fail (self != NULL);
	if (self->priv->monitor != NULL) {
		g_file_monitor_cancel (self->priv->monitor);
	}
	self->priv->monitor = (_tmp0_ = NULL, _g_object_unref0 (self->priv->monitor), _tmp0_);
}


static gboolean _lambda6_ (LauncherFile* self) {
	gboolean result;
	RoxenlauncherHTTPRequest* _tmp0_;
	RoxenlauncherHTTPResponse* _tmp1_;
	RoxenlauncherHTTPResponse* response;
	response = (_tmp1_ = roxenlauncher_http_request_do_method (_tmp0_ = launcher_file_get_http_client (self), g_strdup ("GET"), NULL), _g_object_unref0 (_tmp0_), _tmp1_);
	if (roxenlauncher_http_response_get_status_code (response) != 200) {
		g_warning ("launcherfile.vala:411: Bad status in download: %ld", (glong) roxenlauncher_http_response_get_status_code (response));
		launcher_file_win_set_status (self, (gint) LAUNCHER_FILE_STATUSES_NOT_DOWNLOADED);
		result = FALSE;
		_g_object_unref0 (response);
		return result;
	}
	if (launcher_file_write_download_data (self, response)) {
		launcher_file_win_set_status (self, (gint) LAUNCHER_FILE_STATUSES_DOWNLOADED);
		launcher_file_launch_editor (self);
	} else {
		g_warning ("launcherfile.vala:421: Unable to write downloaded data to disk!");
	}
	launcher_file_save (self);
	result = FALSE;
	_g_object_unref0 (response);
	return result;
}


static gboolean __lambda6__gsource_func (gpointer self) {
	return _lambda6_ (self);
}


void launcher_file_download (LauncherFile* self, gboolean do_launch_editor) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	if (self->priv->_status == LAUNCHER_FILE_STATUSES_DOWNLOADING) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = self->priv->_status == LAUNCHER_FILE_STATUSES_UPLOADING;
	}
	if (_tmp0_) {
		return;
	}
	launcher_file_stop_monitor (self);
	launcher_file_win_set_status (self, (gint) LAUNCHER_FILE_STATUSES_DOWNLOADING);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, __lambda6__gsource_func, g_object_ref (self), g_object_unref);
}


static gboolean _lambda9_ (LauncherFile* self) {
	gboolean result;
	char* _tmp1_;
	RoxenlauncherHTTPRequest* _tmp0_;
	RoxenlauncherHTTPResponse* _tmp2_;
	RoxenlauncherHTTPResponse* response;
	RoxenlauncherDateTime* _tmp3_;
	response = (_tmp2_ = roxenlauncher_http_request_do_method (_tmp0_ = launcher_file_get_http_client (self), g_strdup ("PUT"), _tmp1_ = roxenlauncher_file_get_contents (self->priv->_local_file)), _g_free0 (_tmp1_), _g_object_unref0 (_tmp0_), _tmp2_);
	if (roxenlauncher_http_response_get_status_code (response) != 200) {
		g_warning ("launcherfile.vala:454: > Bad status code (%d) in upload response!", roxenlauncher_http_response_get_status_code (response));
		launcher_file_win_set_status (self, (gint) LAUNCHER_FILE_STATUSES_NOT_UPLOADED);
		result = FALSE;
		_g_object_unref0 (response);
		return result;
	}
	launcher_file_set_last_upload (self, _tmp3_ = roxenlauncher_date_time_now ());
	_g_object_unref0 (_tmp3_);
	launcher_file_win_set_status (self, (gint) LAUNCHER_FILE_STATUSES_UPLOADED);
	launcher_file_save (self);
	result = FALSE;
	_g_object_unref0 (response);
	return result;
}


static gboolean __lambda9__gsource_func (gpointer self) {
	return _lambda9_ (self);
}


void launcher_file_upload (LauncherFile* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	if (self->priv->_status == LAUNCHER_FILE_STATUSES_DOWNLOADING) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = self->priv->_status == LAUNCHER_FILE_STATUSES_UPLOADING;
	}
	if (_tmp0_) {
		return;
	}
	launcher_file_win_set_status (self, (gint) LAUNCHER_FILE_STATUSES_UPLOADING);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, __lambda9__gsource_func, g_object_ref (self), g_object_unref);
}


static gboolean launcher_file_write_download_data (LauncherFile* self, RoxenlauncherHTTPResponse* resp) {
	gboolean result;
	GError * _inner_error_;
	char* _tmp2_;
	char* _tmp1_;
	char* _tmp0_;
	char* _tmp3_;
	char* tmpfile;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (resp != NULL, FALSE);
	_inner_error_ = NULL;
	tmpfile = (_tmp3_ = g_build_filename (_tmp0_ = roxenlauncher_getdir ("$TMP"), _tmp2_ = g_strconcat (_tmp1_ = g_path_get_basename (self->priv->_local_file), ".tmp", NULL), NULL), _g_free0 (_tmp2_), _g_free0 (_tmp1_), _g_free0 (_tmp0_), _tmp3_);
	{
		GFile* file;
		GFileOutputStream* fh;
		GDataOutputStream* ds;
		GFile* f;
		file = g_file_new_for_path (tmpfile);
		if (roxenlauncher_file_exists (tmpfile)) {
			g_file_delete (file, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (file);
				goto __catch16_g_error;
				goto __finally16;
			}
		}
		fh = g_file_create (file, G_FILE_CREATE_NONE, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (file);
			goto __catch16_g_error;
			goto __finally16;
		}
		ds = g_data_output_stream_new ((GOutputStream*) fh);
		{
			gint _tmp4_;
			guint8* c_collection;
			int c_collection_length1;
			int c_it;
			c_collection = roxenlauncher_http_response_get_raw_data (resp, &_tmp4_);
			c_collection_length1 = _tmp4_;
			for (c_it = 0; c_it < _tmp4_; c_it = c_it + 1) {
				guint8 c;
				c = c_collection[c_it];
				{
					g_data_output_stream_put_byte (ds, (guchar) c, NULL, &_inner_error_);
					if (_inner_error_ != NULL) {
						_g_object_unref0 (file);
						_g_object_unref0 (fh);
						_g_object_unref0 (ds);
						goto __catch16_g_error;
						goto __finally16;
					}
				}
			}
		}
		f = g_file_new_for_path (self->priv->_local_file);
		g_file_move (file, f, G_FILE_COPY_OVERWRITE, NULL, NULL, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (file);
			_g_object_unref0 (fh);
			_g_object_unref0 (ds);
			_g_object_unref0 (f);
			goto __catch16_g_error;
			goto __finally16;
		}
		_g_object_unref0 (file);
		_g_object_unref0 (fh);
		_g_object_unref0 (ds);
		_g_object_unref0 (f);
	}
	goto __finally16;
	__catch16_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("launcherfile.vala:491: Failed to save tmp file to disk: %s", e->message);
			result = FALSE;
			_g_error_free0 (e);
			_g_free0 (tmpfile);
			return result;
		}
	}
	__finally16:
	if (_inner_error_ != NULL) {
		_g_free0 (tmpfile);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	result = TRUE;
	_g_free0 (tmpfile);
	return result;
}


static gboolean _lambda4_ (LauncherFile* self) {
	gboolean result;
	char* _tmp0_;
	roxenlauncher_main_window_set_file_status (win, self, _tmp0_ = launcher_file_status_as_string (self));
	_g_free0 (_tmp0_);
	result = FALSE;
	return result;
}


static gboolean __lambda4__gsource_func (gpointer self) {
	return _lambda4_ (self);
}


static void launcher_file_win_set_status (LauncherFile* self, gint st) {
	g_return_if_fail (self != NULL);
	launcher_file_set_status (self, st);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, __lambda4__gsource_func, g_object_ref (self), g_object_unref);
}


static RoxenlauncherHTTPRequest* launcher_file_get_http_client (LauncherFile* self) {
	RoxenlauncherHTTPRequest* result;
	char* _tmp0_;
	RoxenlauncherHTTPRequest* _tmp1_;
	RoxenlauncherHTTPRequest* req;
	char* _tmp2_;
	g_return_val_if_fail (self != NULL, NULL);
	req = (_tmp1_ = roxenlauncher_http_request_new (_tmp0_ = launcher_file_get_uri (self)), _g_free0 (_tmp0_), _tmp1_);
	gee_abstract_map_set ((GeeAbstractMap*) roxenlauncher_http_request_get_headers (req), "User-Agent", ROXENLAUNCHER_APP_USER_AGENT);
	gee_abstract_map_set ((GeeAbstractMap*) roxenlauncher_http_request_get_headers (req), "Translate", "f");
	gee_abstract_map_set ((GeeAbstractMap*) roxenlauncher_http_request_get_headers (req), "Cookie", _tmp2_ = launcher_file_get_cookie (self));
	_g_free0 (_tmp2_);
	roxenlauncher_http_request_set_keep_alive (req, FALSE);
	result = req;
	return result;
}


static gboolean _lambda2_ (LauncherFile* self) {
	gboolean result;
	roxenlauncher_main_window_add_launcher_file (win, self);
	result = FALSE;
	return result;
}


static gboolean __lambda2__gsource_func (gpointer self) {
	return _lambda2_ (self);
}


static void launcher_file_init (LauncherFile* self, const char* _id, GError** error) {
	GError * _inner_error_;
	gboolean _tmp0_ = FALSE;
	char** _tmp2_;
	gint a_size;
	gint a_length1;
	char** _tmp1_;
	char** a;
	char** _tmp6_;
	gint p_size;
	gint p_length1;
	char** _tmp5_;
	char** p;
	char* _tmp8_;
	char* _tmp7_;
	char* _tmp9_;
	RoxenlauncherDateTime* _age;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	if (self->priv->_rawdata == NULL) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = string_get_length (self->priv->_rawdata) == 0;
	}
	if (_tmp0_) {
		_inner_error_ = g_error_new_literal (ROXENLAUNCHER_ROXEN_ERROR, ROXENLAUNCHER_ROXEN_ERROR_BAD_LAUNCHERFILE, _ ("No data in launcher file!"));
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == ROXENLAUNCHER_ROXEN_ERROR) {
				g_propagate_error (error, _inner_error_);
				return;
			} else {
				g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
				g_clear_error (&_inner_error_);
				return;
			}
		}
	}
	a = (_tmp2_ = _tmp1_ = g_strsplit (self->priv->_rawdata, "\r\n", 0), a_length1 = _vala_array_length (_tmp1_), a_size = a_length1, _tmp2_);
	if (a_length1 < 7) {
		_inner_error_ = g_error_new_literal (ROXENLAUNCHER_ROXEN_ERROR, ROXENLAUNCHER_ROXEN_ERROR_BAD_LAUNCHERFILE, _ ("Bad data in launcher file!"));
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == ROXENLAUNCHER_ROXEN_ERROR) {
				g_propagate_error (error, _inner_error_);
				a = (_vala_array_free (a, a_length1, (GDestroyNotify) g_free), NULL);
				return;
			} else {
				a = (_vala_array_free (a, a_length1, (GDestroyNotify) g_free), NULL);
				g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
				g_clear_error (&_inner_error_);
				return;
			}
		}
	}
	launcher_file_set_schema (self, a[0]);
	launcher_file_set_host (self, a[1]);
	launcher_file_set_port (self, a[2]);
	launcher_file_set_auth_cookie (self, a[3]);
	launcher_file_set_path (self, a[4]);
	launcher_file_set_content_type (self, a[5]);
	launcher_file_set_sb_params (self, a[6]);
	if (a_length1 >= 9) {
		RoxenlauncherDateTime* _tmp3_;
		launcher_file_set_last_upload (self, _tmp3_ = roxenlauncher_date_time_unixtime ((time_t) atol (a[7])));
		_g_object_unref0 (_tmp3_);
		launcher_file_set_status (self, atoi (a[8]));
	} else {
		RoxenlauncherDateTime* _tmp4_;
		launcher_file_set_last_upload (self, _tmp4_ = roxenlauncher_date_time_new (1970, 1, 1, 1, 0, 0));
		_g_object_unref0 (_tmp4_);
		launcher_file_set_status (self, (gint) LAUNCHER_FILE_STATUSES_NOT_DOWNLOADED);
	}
	if (_id == NULL) {
		launcher_file_randid (self);
	}
	p = (_tmp6_ = _tmp5_ = g_strsplit (self->priv->_path, "/", 0), p_length1 = _vala_array_length (_tmp5_), p_size = p_length1, _tmp6_);
	launcher_file_set_local_dir (self, _tmp8_ = g_build_filename (_tmp7_ = roxenlauncher_getdir ("files"), self->priv->_id, NULL));
	_g_free0 (_tmp8_);
	_g_free0 (_tmp7_);
	launcher_file_set_local_file (self, _tmp9_ = g_build_filename (self->priv->_local_dir, p[p_length1 - 1], NULL));
	_g_free0 (_tmp9_);
	if (_id == NULL) {
		g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, __lambda2__gsource_func, g_object_ref (self), g_object_unref);
		launcher_file_save (self);
		launcher_file_download (self, TRUE);
	} else {
		RoxenlauncherDateTime* lm;
		if (!roxenlauncher_file_exists (self->priv->_local_file)) {
			launcher_file_download (self, TRUE);
		}
		lm = roxenlauncher_filemtime (self->priv->_local_file);
		if (lm != NULL) {
			launcher_file_set_last_modified (self, lm);
		}
		_g_object_unref0 (lm);
	}
	_age = roxenlauncher_filectime (self->priv->_local_dir);
	if (_age != NULL) {
		launcher_file_set_age (self, _age);
	}
	a = (_vala_array_free (a, a_length1, (GDestroyNotify) g_free), NULL);
	p = (_vala_array_free (p, p_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (_age);
}


static void _vala_array_add1 (char*** array, int* length, int* size, char* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (char*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void launcher_file_randid (LauncherFile* self) {
	char* sb;
	char* p;
	char** _tmp4_;
	gint paths_size;
	gint paths_length1;
	char** _tmp3_;
	char** paths;
	char** _tmp6_;
	gint npaths_size;
	gint npaths_length1;
	char** _tmp5_ = NULL;
	char** npaths;
	g_return_if_fail (self != NULL);
	sb = g_strdup ("");
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				char* _tmp2_;
				char* _tmp1_;
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < 8)) {
					break;
				}
				sb = (_tmp2_ = g_strconcat (sb, _tmp1_ = g_strdup_printf ("%c", (gint) floor ((26 * g_random_double ()) + 65)), NULL), _g_free0 (sb), _tmp2_);
				_g_free0 (_tmp1_);
			}
		}
	}
	p = roxenlauncher_trim (self->priv->_path, "/");
	paths = (_tmp4_ = _tmp3_ = g_strsplit (p, "/", 0), paths_length1 = _vala_array_length (_tmp3_), paths_size = paths_length1, _tmp4_);
	npaths = (_tmp6_ = (_tmp5_ = g_new0 (char*, 0 + 1), _tmp5_), npaths_length1 = 0, npaths_size = npaths_length1, _tmp6_);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp7_;
			_tmp7_ = TRUE;
			while (TRUE) {
				if (!_tmp7_) {
					i++;
				}
				_tmp7_ = FALSE;
				if (!(i < (paths_length1 - 1))) {
					break;
				}
				_vala_array_add1 (&npaths, &npaths_length1, &npaths_size, g_strdup (paths[i]));
			}
		}
	}
	if (npaths_length1 > 0) {
		char* _tmp10_;
		char* _tmp9_;
		char* _tmp8_;
		launcher_file_set_id (self, _tmp10_ = g_strconcat (_tmp8_ = g_strconcat (sb, "_", NULL), _tmp9_ = roxenlauncher_implode (npaths, npaths_length1, "_"), NULL));
		_g_free0 (_tmp10_);
		_g_free0 (_tmp9_);
		_g_free0 (_tmp8_);
	} else {
		launcher_file_set_id (self, sb);
	}
	_g_free0 (sb);
	_g_free0 (p);
	paths = (_vala_array_free (paths, paths_length1, (GDestroyNotify) g_free), NULL);
	npaths = (_vala_array_free (npaths, npaths_length1, (GDestroyNotify) g_free), NULL);
}


static void launcher_file_create_dir (LauncherFile* self) {
	char* _tmp0_;
	char* _tmp1_;
	char* p;
	g_return_if_fail (self != NULL);
	p = (_tmp1_ = g_build_filename (_tmp0_ = roxenlauncher_getdir ("files"), self->priv->_id, NULL), _g_free0 (_tmp0_), _tmp1_);
	if (!g_file_test (p, G_FILE_TEST_EXISTS)) {
		if (g_mkdir_with_parents (p, 0750) == (-1)) {
			g_error ("launcherfile.vala:634: %s", _ ("Unable to create directory for launcher file!"));
		}
	}
	_g_free0 (p);
}


static char* launcher_file_load (LauncherFile* self) {
	char* result;
	char* _tmp0_;
	char* _tmp1_;
	char* p;
	g_return_val_if_fail (self != NULL, NULL);
	p = (_tmp1_ = g_build_filename (_tmp0_ = roxenlauncher_getdir ("files"), self->priv->_id, "stub", NULL), _g_free0 (_tmp0_), _tmp1_);
	result = roxenlauncher_file_get_contents (p);
	_g_free0 (p);
	return result;
}


static void launcher_file_save (LauncherFile* self) {
	GError * _inner_error_;
	char** _tmp1_;
	gint data_size;
	gint data_length1;
	char** _tmp0_ = NULL;
	char** data;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	launcher_file_create_dir (self);
	data = (_tmp1_ = (_tmp0_ = g_new0 (char*, 9 + 1), _tmp0_[0] = g_strdup (self->priv->_schema), _tmp0_[1] = g_strdup (self->priv->_host), _tmp0_[2] = g_strdup (self->priv->_port), _tmp0_[3] = g_strdup (self->priv->_auth_cookie), _tmp0_[4] = g_strdup (self->priv->_path), _tmp0_[5] = g_strdup (self->priv->_content_type), _tmp0_[6] = g_strdup (self->priv->_sb_params), _tmp0_[7] = g_strdup_printf ("%ld", (glong) roxenlauncher_date_time_to_unixtime (self->priv->_last_upload)), _tmp0_[8] = g_strdup_printf ("%i", self->priv->_status), _tmp0_), data_length1 = 9, data_size = data_length1, _tmp1_);
	{
		char* _tmp2_;
		char* _tmp3_;
		char* f;
		char* _tmp4_;
		f = (_tmp3_ = g_build_filename (_tmp2_ = roxenlauncher_getdir ("files"), self->priv->_id, "stub", NULL), _g_free0 (_tmp2_), _tmp3_);
		g_file_set_contents (f, _tmp4_ = roxenlauncher_implode (data, data_length1, "\r\n"), -1, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (f);
			goto __catch17_g_error;
			goto __finally17;
		}
		_g_free0 (_tmp4_);
		_g_free0 (f);
	}
	goto __finally17;
	__catch17_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("launcherfile.vala:671: Failed to write stub file to local directory: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally17:
	if (_inner_error_ != NULL) {
		data = (_vala_array_free (data, data_length1, (GDestroyNotify) g_free), NULL);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	data = (_vala_array_free (data, data_length1, (GDestroyNotify) g_free), NULL);
}


static void launcher_file_on_file_changed (LauncherFile* self, GFile* f, GFile* other, GFileMonitorEvent e) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (f != NULL);
	switch (e) {
		case G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED:
		{
			break;
		}
		case G_FILE_MONITOR_EVENT_CHANGED:
		{
			break;
		}
		case G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT:
		{
			gboolean _tmp0_ = FALSE;
			if (self->priv->previous_event == G_FILE_MONITOR_EVENT_CREATED) {
				_tmp0_ = TRUE;
			} else {
				_tmp0_ = self->priv->previous_event == G_FILE_MONITOR_EVENT_CHANGED;
			}
			if (_tmp0_) {
				launcher_file_upload (self);
			}
			break;
		}
		case G_FILE_MONITOR_EVENT_CREATED:
		{
			break;
		}
		case G_FILE_MONITOR_EVENT_DELETED:
		{
			break;
		}
		case G_FILE_MONITOR_EVENT_PRE_UNMOUNT:
		{
			break;
		}
		case G_FILE_MONITOR_EVENT_UNMOUNTED:
		{
			break;
		}
		default:
		{
			break;
		}
	}
	self->priv->previous_event = e;
}


const char* launcher_file_get_rawdata (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_rawdata;
	return result;
}


static void launcher_file_set_rawdata (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_rawdata = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_rawdata), _tmp0_);
	g_object_notify ((GObject *) self, "rawdata");
}


const char* launcher_file_get_schema (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_schema;
	return result;
}


static void launcher_file_set_schema (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_schema = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_schema), _tmp0_);
	g_object_notify ((GObject *) self, "schema");
}


const char* launcher_file_get_host (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_host;
	return result;
}


static void launcher_file_set_host (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_host = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_host), _tmp0_);
	g_object_notify ((GObject *) self, "host");
}


const char* launcher_file_get_port (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_port;
	return result;
}


static void launcher_file_set_port (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_port = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_port), _tmp0_);
	g_object_notify ((GObject *) self, "port");
}


const char* launcher_file_get_auth_cookie (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_auth_cookie;
	return result;
}


static void launcher_file_set_auth_cookie (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_auth_cookie = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_auth_cookie), _tmp0_);
	g_object_notify ((GObject *) self, "auth-cookie");
}


const char* launcher_file_get_content_type (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_content_type;
	return result;
}


static void launcher_file_set_content_type (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_content_type = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_content_type), _tmp0_);
	g_object_notify ((GObject *) self, "content-type");
}


const char* launcher_file_get_sb_params (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_sb_params;
	return result;
}


static void launcher_file_set_sb_params (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_sb_params = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_sb_params), _tmp0_);
	g_object_notify ((GObject *) self, "sb-params");
}


const char* launcher_file_get_id (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_id;
	return result;
}


static void launcher_file_set_id (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_id = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_id), _tmp0_);
	g_object_notify ((GObject *) self, "id");
}


const char* launcher_file_get_path (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_path;
	return result;
}


static void launcher_file_set_path (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_path = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_path), _tmp0_);
	g_object_notify ((GObject *) self, "path");
}


const char* launcher_file_get_local_dir (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_local_dir;
	return result;
}


static void launcher_file_set_local_dir (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_local_dir = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_local_dir), _tmp0_);
	g_object_notify ((GObject *) self, "local-dir");
}


const char* launcher_file_get_local_file (LauncherFile* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_local_file;
	return result;
}


static void launcher_file_set_local_file (LauncherFile* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_local_file = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_local_file), _tmp0_);
	g_object_notify ((GObject *) self, "local-file");
}


gint launcher_file_get_status (LauncherFile* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_status;
	return result;
}


static void launcher_file_set_status (LauncherFile* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->_status = value;
	g_object_notify ((GObject *) self, "status");
}


gboolean launcher_file_get_is_downloading (LauncherFile* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_is_downloading;
	return result;
}


static void launcher_file_set_is_downloading (LauncherFile* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_is_downloading = value;
	g_object_notify ((GObject *) self, "is-downloading");
}


gboolean launcher_file_get_is_uploading (LauncherFile* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_is_uploading;
	return result;
}


static void launcher_file_set_is_uploading (LauncherFile* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_is_uploading = value;
	g_object_notify ((GObject *) self, "is-uploading");
}


RoxenlauncherDateTime* launcher_file_get_last_upload (LauncherFile* self) {
	RoxenlauncherDateTime* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_last_upload;
	return result;
}


static void launcher_file_set_last_upload (LauncherFile* self, RoxenlauncherDateTime* value) {
	RoxenlauncherDateTime* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_last_upload = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_last_upload), _tmp0_);
	g_object_notify ((GObject *) self, "last-upload");
}


RoxenlauncherDateTime* launcher_file_get_last_download (LauncherFile* self) {
	RoxenlauncherDateTime* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_last_download;
	return result;
}


static void launcher_file_set_last_download (LauncherFile* self, RoxenlauncherDateTime* value) {
	RoxenlauncherDateTime* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_last_download = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_last_download), _tmp0_);
	g_object_notify ((GObject *) self, "last-download");
}


RoxenlauncherDateTime* launcher_file_get_last_modified (LauncherFile* self) {
	RoxenlauncherDateTime* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_last_modified;
	return result;
}


static void launcher_file_set_last_modified (LauncherFile* self, RoxenlauncherDateTime* value) {
	RoxenlauncherDateTime* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_last_modified = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_last_modified), _tmp0_);
	g_object_notify ((GObject *) self, "last-modified");
}


RoxenlauncherDateTime* launcher_file_get_age (LauncherFile* self) {
	RoxenlauncherDateTime* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_age;
	return result;
}


static void launcher_file_set_age (LauncherFile* self, RoxenlauncherDateTime* value) {
	RoxenlauncherDateTime* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_age = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_age), _tmp0_);
	g_object_notify ((GObject *) self, "age");
}


RoxenlauncherApplication* launcher_file_get_application (LauncherFile* self) {
	RoxenlauncherApplication* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_application;
	return result;
}


static void launcher_file_set_application (LauncherFile* self, RoxenlauncherApplication* value) {
	RoxenlauncherApplication* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_application = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_application), _tmp0_);
	g_object_notify ((GObject *) self, "application");
}


static void launcher_file_class_init (LauncherFileClass * klass) {
	launcher_file_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LauncherFilePrivate));
	G_OBJECT_CLASS (klass)->get_property = launcher_file_get_property;
	G_OBJECT_CLASS (klass)->set_property = launcher_file_set_property;
	G_OBJECT_CLASS (klass)->finalize = launcher_file_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_RAWDATA, g_param_spec_string ("rawdata", "rawdata", "rawdata", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_SCHEMA, g_param_spec_string ("schema", "schema", "schema", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_HOST, g_param_spec_string ("host", "host", "host", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_PORT, g_param_spec_string ("port", "port", "port", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_AUTH_COOKIE, g_param_spec_string ("auth-cookie", "auth-cookie", "auth-cookie", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_CONTENT_TYPE, g_param_spec_string ("content-type", "content-type", "content-type", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_SB_PARAMS, g_param_spec_string ("sb-params", "sb-params", "sb-params", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_ID, g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_PATH, g_param_spec_string ("path", "path", "path", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_LOCAL_DIR, g_param_spec_string ("local-dir", "local-dir", "local-dir", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_LOCAL_FILE, g_param_spec_string ("local-file", "local-file", "local-file", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_STATUS, g_param_spec_int ("status", "status", "status", G_MININT, G_MAXINT, -1, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_IS_DOWNLOADING, g_param_spec_boolean ("is-downloading", "is-downloading", "is-downloading", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_IS_UPLOADING, g_param_spec_boolean ("is-uploading", "is-uploading", "is-uploading", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_LAST_UPLOAD, g_param_spec_object ("last-upload", "last-upload", "last-upload", ROXENLAUNCHER_TYPE_DATE_TIME, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_LAST_DOWNLOAD, g_param_spec_object ("last-download", "last-download", "last-download", ROXENLAUNCHER_TYPE_DATE_TIME, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_LAST_MODIFIED, g_param_spec_object ("last-modified", "last-modified", "last-modified", ROXENLAUNCHER_TYPE_DATE_TIME, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_AGE, g_param_spec_object ("age", "age", "age", ROXENLAUNCHER_TYPE_DATE_TIME, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), LAUNCHER_FILE_APPLICATION, g_param_spec_object ("application", "application", "application", ROXENLAUNCHER_TYPE_APPLICATION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	launcher_file_launcherfiles = gee_array_list_new (TYPE_LAUNCHER_FILE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
}


static void launcher_file_instance_init (LauncherFile * self) {
	self->priv = LAUNCHER_FILE_GET_PRIVATE (self);
	self->priv->_status = -1;
	self->priv->_is_downloading = FALSE;
	self->priv->_is_uploading = FALSE;
}


static void launcher_file_finalize (GObject* obj) {
	LauncherFile * self;
	self = LAUNCHER_FILE (obj);
	{
		if (self->priv->monitor != NULL) {
			g_file_monitor_cancel (self->priv->monitor);
		}
	}
	_g_free0 (self->priv->_rawdata);
	_g_free0 (self->priv->_schema);
	_g_free0 (self->priv->_host);
	_g_free0 (self->priv->_port);
	_g_free0 (self->priv->_auth_cookie);
	_g_free0 (self->priv->_content_type);
	_g_free0 (self->priv->_sb_params);
	_g_free0 (self->priv->_id);
	_g_free0 (self->priv->_path);
	_g_free0 (self->priv->_local_dir);
	_g_free0 (self->priv->_local_file);
	_g_object_unref0 (self->priv->_last_upload);
	_g_object_unref0 (self->priv->_last_download);
	_g_object_unref0 (self->priv->_last_modified);
	_g_object_unref0 (self->priv->_age);
	_g_object_unref0 (self->priv->_application);
	_g_object_unref0 (self->priv->monitor);
	G_OBJECT_CLASS (launcher_file_parent_class)->finalize (obj);
}


GType launcher_file_get_type (void) {
	static GType launcher_file_type_id = 0;
	if (launcher_file_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (LauncherFileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) launcher_file_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LauncherFile), 0, (GInstanceInitFunc) launcher_file_instance_init, NULL };
		launcher_file_type_id = g_type_register_static (G_TYPE_OBJECT, "LauncherFile", &g_define_type_info, 0);
	}
	return launcher_file_type_id;
}


static void launcher_file_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	LauncherFile * self;
	self = LAUNCHER_FILE (object);
	switch (property_id) {
		case LAUNCHER_FILE_RAWDATA:
		g_value_set_string (value, launcher_file_get_rawdata (self));
		break;
		case LAUNCHER_FILE_SCHEMA:
		g_value_set_string (value, launcher_file_get_schema (self));
		break;
		case LAUNCHER_FILE_HOST:
		g_value_set_string (value, launcher_file_get_host (self));
		break;
		case LAUNCHER_FILE_PORT:
		g_value_set_string (value, launcher_file_get_port (self));
		break;
		case LAUNCHER_FILE_AUTH_COOKIE:
		g_value_set_string (value, launcher_file_get_auth_cookie (self));
		break;
		case LAUNCHER_FILE_CONTENT_TYPE:
		g_value_set_string (value, launcher_file_get_content_type (self));
		break;
		case LAUNCHER_FILE_SB_PARAMS:
		g_value_set_string (value, launcher_file_get_sb_params (self));
		break;
		case LAUNCHER_FILE_ID:
		g_value_set_string (value, launcher_file_get_id (self));
		break;
		case LAUNCHER_FILE_PATH:
		g_value_set_string (value, launcher_file_get_path (self));
		break;
		case LAUNCHER_FILE_LOCAL_DIR:
		g_value_set_string (value, launcher_file_get_local_dir (self));
		break;
		case LAUNCHER_FILE_LOCAL_FILE:
		g_value_set_string (value, launcher_file_get_local_file (self));
		break;
		case LAUNCHER_FILE_STATUS:
		g_value_set_int (value, launcher_file_get_status (self));
		break;
		case LAUNCHER_FILE_IS_DOWNLOADING:
		g_value_set_boolean (value, launcher_file_get_is_downloading (self));
		break;
		case LAUNCHER_FILE_IS_UPLOADING:
		g_value_set_boolean (value, launcher_file_get_is_uploading (self));
		break;
		case LAUNCHER_FILE_LAST_UPLOAD:
		g_value_set_object (value, launcher_file_get_last_upload (self));
		break;
		case LAUNCHER_FILE_LAST_DOWNLOAD:
		g_value_set_object (value, launcher_file_get_last_download (self));
		break;
		case LAUNCHER_FILE_LAST_MODIFIED:
		g_value_set_object (value, launcher_file_get_last_modified (self));
		break;
		case LAUNCHER_FILE_AGE:
		g_value_set_object (value, launcher_file_get_age (self));
		break;
		case LAUNCHER_FILE_APPLICATION:
		g_value_set_object (value, launcher_file_get_application (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void launcher_file_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	LauncherFile * self;
	self = LAUNCHER_FILE (object);
	switch (property_id) {
		case LAUNCHER_FILE_RAWDATA:
		launcher_file_set_rawdata (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_SCHEMA:
		launcher_file_set_schema (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_HOST:
		launcher_file_set_host (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_PORT:
		launcher_file_set_port (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_AUTH_COOKIE:
		launcher_file_set_auth_cookie (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_CONTENT_TYPE:
		launcher_file_set_content_type (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_SB_PARAMS:
		launcher_file_set_sb_params (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_ID:
		launcher_file_set_id (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_PATH:
		launcher_file_set_path (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_LOCAL_DIR:
		launcher_file_set_local_dir (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_LOCAL_FILE:
		launcher_file_set_local_file (self, g_value_get_string (value));
		break;
		case LAUNCHER_FILE_STATUS:
		launcher_file_set_status (self, g_value_get_int (value));
		break;
		case LAUNCHER_FILE_IS_DOWNLOADING:
		launcher_file_set_is_downloading (self, g_value_get_boolean (value));
		break;
		case LAUNCHER_FILE_IS_UPLOADING:
		launcher_file_set_is_uploading (self, g_value_get_boolean (value));
		break;
		case LAUNCHER_FILE_LAST_UPLOAD:
		launcher_file_set_last_upload (self, g_value_get_object (value));
		break;
		case LAUNCHER_FILE_LAST_DOWNLOAD:
		launcher_file_set_last_download (self, g_value_get_object (value));
		break;
		case LAUNCHER_FILE_LAST_MODIFIED:
		launcher_file_set_last_modified (self, g_value_get_object (value));
		break;
		case LAUNCHER_FILE_AGE:
		launcher_file_set_age (self, g_value_get_object (value));
		break;
		case LAUNCHER_FILE_APPLICATION:
		launcher_file_set_application (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




