/* main.c generated by valac, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <unique/unique.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>


#define ROXENLAUNCHER_TYPE_MAIN_WINDOW (roxenlauncher_main_window_get_type ())
#define ROXENLAUNCHER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindow))
#define ROXENLAUNCHER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowClass))
#define ROXENLAUNCHER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW))
#define ROXENLAUNCHER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_MAIN_WINDOW))
#define ROXENLAUNCHER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowClass))

typedef struct _RoxenlauncherMainWindow RoxenlauncherMainWindow;
typedef struct _RoxenlauncherMainWindowClass RoxenlauncherMainWindowClass;

#define TYPE_APPLICATION_LAUNCHER (application_launcher_get_type ())
#define APPLICATION_LAUNCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APPLICATION_LAUNCHER, ApplicationLauncher))
#define APPLICATION_LAUNCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APPLICATION_LAUNCHER, ApplicationLauncherClass))
#define IS_APPLICATION_LAUNCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APPLICATION_LAUNCHER))
#define IS_APPLICATION_LAUNCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APPLICATION_LAUNCHER))
#define APPLICATION_LAUNCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APPLICATION_LAUNCHER, ApplicationLauncherClass))

typedef struct _ApplicationLauncher ApplicationLauncher;
typedef struct _ApplicationLauncherClass ApplicationLauncherClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ApplicationLauncherPrivate ApplicationLauncherPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _unique_message_data_free0(var) ((var == NULL) ? NULL : (var = (unique_message_data_free (var), NULL)))

#define TYPE_LAUNCHER_FILE (launcher_file_get_type ())
#define LAUNCHER_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LAUNCHER_FILE, LauncherFile))
#define LAUNCHER_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LAUNCHER_FILE, LauncherFileClass))
#define IS_LAUNCHER_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LAUNCHER_FILE))
#define IS_LAUNCHER_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LAUNCHER_FILE))
#define LAUNCHER_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LAUNCHER_FILE, LauncherFileClass))

typedef struct _LauncherFile LauncherFile;
typedef struct _LauncherFileClass LauncherFileClass;

struct _ApplicationLauncher {
	GObject parent_instance;
	ApplicationLauncherPrivate * priv;
};

struct _ApplicationLauncherClass {
	GObjectClass parent_class;
};

struct _ApplicationLauncherPrivate {
	UniqueApp* instance;
};

typedef enum  {
	ROXENLAUNCHER_ROXEN_ERROR_BAD_LAUNCHERFILE,
	ROXENLAUNCHER_ROXEN_ERROR_GENERIC
} RoxenlauncherRoxenError;
#define ROXENLAUNCHER_ROXEN_ERROR roxenlauncher_roxen_error_quark ()

extern RoxenlauncherMainWindow* win;
RoxenlauncherMainWindow* win = NULL;
static gpointer application_launcher_parent_class = NULL;

GType roxenlauncher_main_window_get_type (void);
ApplicationLauncher* application_launcher_new (void);
ApplicationLauncher* application_launcher_construct (GType object_type);
GType application_launcher_get_type (void);
gint application_launcher_run (ApplicationLauncher* self, char** args, int args_length1);
gint _main (char** args, int args_length1);
#define APPLICATION_LAUNCHER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_APPLICATION_LAUNCHER, ApplicationLauncherPrivate))
enum  {
	APPLICATION_LAUNCHER_DUMMY_PROPERTY
};
RoxenlauncherMainWindow* roxenlauncher_main_window_new (void);
RoxenlauncherMainWindow* roxenlauncher_main_window_construct (GType object_type);
#define ROXENLAUNCHER_APP_LIB_UNIQUE_PATH "com.roxen.launcher"
GQuark roxenlauncher_roxen_error_quark (void);
char** roxenlauncher_slice (char** s, int s_length1, guint from, guint to, int* result_length1, GError** error);
char* roxenlauncher_implode (char** s, int s_length1, const char* glue);
static UniqueResponse application_launcher_on_message_received (ApplicationLauncher* self, UniqueApp* instance, gint command, UniqueMessageData* data, guint time);
static UniqueResponse _application_launcher_on_message_received_unique_app_message_received (UniqueApp* _sender, gint command, UniqueMessageData* message_data, guint time_, gpointer self);
void launcher_file_load_existing (void);
void roxenlauncher_application_load_from_gconf (void);
static void application_launcher_handle_incomming_file (ApplicationLauncher* self, const char* path);
void roxenlauncher_main_window_init (RoxenlauncherMainWindow* self);
char* roxenlauncher_file_get_contents (const char* file);
GType launcher_file_get_type (void);
gboolean launcher_file_incomming (const char* data, LauncherFile** file, GError** error);
const char* launcher_file_get_path (LauncherFile* self);
static void application_launcher_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);



gint _main (char** args, int args_length1) {
	gint result;
	ApplicationLauncher* app;
	app = application_launcher_new ();
	result = application_launcher_run (app, args, args_length1);
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
	g_thread_init (NULL);
	g_type_init ();
	return _main (argv, argc);
}


static UniqueResponse _application_launcher_on_message_received_unique_app_message_received (UniqueApp* _sender, gint command, UniqueMessageData* message_data, guint time_, gpointer self) {
	return application_launcher_on_message_received (self, _sender, command, message_data, time_);
}


gint application_launcher_run (ApplicationLauncher* self, char** args, int args_length1) {
	gint result;
	GError * _inner_error_;
	RoxenlauncherMainWindow* _tmp0_;
	UniqueApp* _tmp1_;
	char** _tmp2_;
	gint argslist_size;
	gint argslist_length1;
	char** argslist;
	gboolean _tmp7_;
	g_return_val_if_fail (self != NULL, 0);
	_inner_error_ = NULL;
	win = (_tmp0_ = roxenlauncher_main_window_new (), _g_object_unref0 (win), _tmp0_);
	gtk_init (&args_length1, &args);
	self->priv->instance = (_tmp1_ = unique_app_new (ROXENLAUNCHER_APP_LIB_UNIQUE_PATH, NULL), _g_object_unref0 (self->priv->instance), _tmp1_);
	argslist = (_tmp2_ = g_new0 (char*, (args_length1 - 2) + 1), argslist_length1 = args_length1 - 2, argslist_size = argslist_length1, _tmp2_);
	{
		char** _tmp5_;
		gint _tmp4__size;
		gint _tmp4__length1;
		gint _tmp3_;
		char** _tmp4_;
		char** _tmp6_;
		_tmp4_ = (_tmp5_ = roxenlauncher_slice (args, args_length1, (guint) 1, 0, &_tmp3_, &_inner_error_), _tmp4__length1 = _tmp3_, _tmp4__size = _tmp4__length1, _tmp5_);
		if (_inner_error_ != NULL) {
			goto __catch9_g_error;
			goto __finally9;
		}
		argslist = (_tmp6_ = _tmp4_, argslist = (_vala_array_free (argslist, argslist_length1, (GDestroyNotify) g_free), NULL), argslist_length1 = _tmp4__length1, argslist_size = argslist_length1, _tmp6_);
	}
	goto __finally9;
	__catch9_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("main.vala:26: Error: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally9:
	if (_inner_error_ != NULL) {
		argslist = (_vala_array_free (argslist, argslist_length1, (GDestroyNotify) g_free), NULL);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return 0;
	}
	if ((g_object_get (self->priv->instance, "is-running", &_tmp7_, NULL), _tmp7_)) {
		if (argslist_length1 > 0) {
			char* _tmp8_;
			UniqueMessageData* md;
			char* _tmp9_;
			g_message ("main.vala:31: Send args: %s", _tmp8_ = roxenlauncher_implode (argslist, argslist_length1, ", "));
			_g_free0 (_tmp8_);
			md = unique_message_data_new ();
			unique_message_data_set_text (md, _tmp9_ = roxenlauncher_implode (argslist, argslist_length1, ";"), (gssize) (-1));
			_g_free0 (_tmp9_);
			unique_app_send_message (self->priv->instance, (gint) UNIQUE_OPEN, md);
			_unique_message_data_free0 (md);
		}
		gdk_notify_startup_complete ();
		result = 0;
		argslist = (_vala_array_free (argslist, argslist_length1, (GDestroyNotify) g_free), NULL);
		return result;
	}
	g_signal_connect_object (self->priv->instance, "message-received", (GCallback) _application_launcher_on_message_received_unique_app_message_received, self, 0);
	launcher_file_load_existing ();
	roxenlauncher_application_load_from_gconf ();
	if (argslist_length1 > 0) {
		{
			char** s_collection;
			int s_collection_length1;
			int s_it;
			s_collection = argslist;
			s_collection_length1 = argslist_length1;
			for (s_it = 0; s_it < argslist_length1; s_it = s_it + 1) {
				char* s;
				s = g_strdup (s_collection[s_it]);
				{
					application_launcher_handle_incomming_file (self, s);
					_g_free0 (s);
				}
			}
		}
	}
	roxenlauncher_main_window_init (win);
	gtk_main ();
	result = 0;
	argslist = (_vala_array_free (argslist, argslist_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


static void application_launcher_handle_incomming_file (ApplicationLauncher* self, const char* path) {
	GError * _inner_error_;
	char* d;
	g_return_if_fail (self != NULL);
	g_return_if_fail (path != NULL);
	_inner_error_ = NULL;
	g_message ("main.vala:59: *** handle_incomming_file(%s)", path);
	d = roxenlauncher_file_get_contents (path);
	if (d != NULL) {
		LauncherFile* lf;
		LauncherFile* _tmp2_;
		gboolean _tmp1_;
		LauncherFile* _tmp0_ = NULL;
		gboolean _tmp3_;
		lf = NULL;
		_tmp3_ = (_tmp1_ = launcher_file_incomming (d, &_tmp0_, &_inner_error_), lf = (_tmp2_ = _tmp0_, _g_object_unref0 (lf), _tmp2_), _tmp1_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (lf);
			_g_free0 (d);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
			return;
		}
		if (_tmp3_) {
			g_message ("main.vala:64: Incomming file is new...%s", launcher_file_get_path (lf));
		} else {
			g_message ("main.vala:67: Incomming file exists locally...re-download!");
		}
		_g_object_unref0 (lf);
	}
	_g_free0 (d);
}


static UniqueResponse application_launcher_on_message_received (ApplicationLauncher* self, UniqueApp* instance, gint command, UniqueMessageData* data, guint time) {
	UniqueResponse result;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (instance != NULL, 0);
	g_return_val_if_fail (data != NULL, 0);
	if (command == UNIQUE_OPEN) {
		{
			char** _tmp1_;
			char* _tmp0_;
			char** _tmp2_;
			char** s_collection;
			int s_collection_length1;
			int s_it;
			s_collection = (_tmp2_ = _tmp1_ = g_strsplit (_tmp0_ = unique_message_data_get_text (data), ";", 0), _g_free0 (_tmp0_), _tmp2_);
			s_collection_length1 = _vala_array_length (_tmp1_);
			for (s_it = 0; s_it < _vala_array_length (_tmp1_); s_it = s_it + 1) {
				char* s;
				s = g_strdup (s_collection[s_it]);
				{
					application_launcher_handle_incomming_file (self, s);
					_g_free0 (s);
				}
			}
			s_collection = (_vala_array_free (s_collection, s_collection_length1, (GDestroyNotify) g_free), NULL);
		}
	}
	result = UNIQUE_RESPONSE_OK;
	return result;
}


ApplicationLauncher* application_launcher_construct (GType object_type) {
	ApplicationLauncher * self;
	self = (ApplicationLauncher*) g_object_new (object_type, NULL);
	return self;
}


ApplicationLauncher* application_launcher_new (void) {
	return application_launcher_construct (TYPE_APPLICATION_LAUNCHER);
}


static void application_launcher_class_init (ApplicationLauncherClass * klass) {
	application_launcher_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ApplicationLauncherPrivate));
	G_OBJECT_CLASS (klass)->finalize = application_launcher_finalize;
}


static void application_launcher_instance_init (ApplicationLauncher * self) {
	self->priv = APPLICATION_LAUNCHER_GET_PRIVATE (self);
}


static void application_launcher_finalize (GObject* obj) {
	ApplicationLauncher * self;
	self = APPLICATION_LAUNCHER (obj);
	_g_object_unref0 (self->priv->instance);
	G_OBJECT_CLASS (application_launcher_parent_class)->finalize (obj);
}


GType application_launcher_get_type (void) {
	static GType application_launcher_type_id = 0;
	if (application_launcher_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (ApplicationLauncherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) application_launcher_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ApplicationLauncher), 0, (GInstanceInitFunc) application_launcher_instance_init, NULL };
		application_launcher_type_id = g_type_register_static (G_TYPE_OBJECT, "ApplicationLauncher", &g_define_type_info, 0);
	}
	return application_launcher_type_id;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}




