/* mainwindow.c generated by valac, the Vala compiler
 * generated from mainwindow.vala, do not modify */

/* -*- Mode: Vala; indent-tabs-mode: t; c-basic-offset: 2; tab-width: 2 -*- */
/*
 * mainwindow.vala
 * Copyright (C) Pontus Östlund 2009 <pontus@poppa.se>
 *
 * This file is part of Roxen Application Launcher (RAL)
 * 
 * RAL is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * RAL is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with RAL.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <config.h>
#include <gdk/gdk.h>
#include <glib/gi18n-lib.h>
#include <time.h>
#include <gee.h>
#include <gdk-pixbuf/gdk-pixdata.h>


#define ROXENLAUNCHER_TYPE_MAIN_WINDOW (roxenlauncher_main_window_get_type ())
#define ROXENLAUNCHER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindow))
#define ROXENLAUNCHER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowClass))
#define ROXENLAUNCHER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW))
#define ROXENLAUNCHER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_MAIN_WINDOW))
#define ROXENLAUNCHER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowClass))

typedef struct _RoxenlauncherMainWindow RoxenlauncherMainWindow;
typedef struct _RoxenlauncherMainWindowClass RoxenlauncherMainWindowClass;
typedef struct _RoxenlauncherMainWindowPrivate RoxenlauncherMainWindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define ROXENLAUNCHER_TYPE_WINDOWS_PROPERTIES (roxenlauncher_windows_properties_get_type ())
typedef struct _RoxenlauncherWindowsProperties RoxenlauncherWindowsProperties;

#define TYPE_LAUNCHER_FILE (launcher_file_get_type ())
#define LAUNCHER_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LAUNCHER_FILE, LauncherFile))
#define LAUNCHER_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LAUNCHER_FILE, LauncherFileClass))
#define IS_LAUNCHER_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LAUNCHER_FILE))
#define IS_LAUNCHER_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LAUNCHER_FILE))
#define LAUNCHER_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LAUNCHER_FILE, LauncherFileClass))

typedef struct _LauncherFile LauncherFile;
typedef struct _LauncherFileClass LauncherFileClass;

#define ROXENLAUNCHER_TYPE_DATE_TIME (roxenlauncher_date_time_get_type ())
#define ROXENLAUNCHER_DATE_TIME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTime))
#define ROXENLAUNCHER_DATE_TIME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTimeClass))
#define ROXENLAUNCHER_IS_DATE_TIME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_DATE_TIME))
#define ROXENLAUNCHER_IS_DATE_TIME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_DATE_TIME))
#define ROXENLAUNCHER_DATE_TIME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_DATE_TIME, RoxenlauncherDateTimeClass))

typedef struct _RoxenlauncherDateTime RoxenlauncherDateTime;
typedef struct _RoxenlauncherDateTimeClass RoxenlauncherDateTimeClass;

#define ROXENLAUNCHER_TYPE_APPLICATION (roxenlauncher_application_get_type ())
#define ROXENLAUNCHER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplication))
#define ROXENLAUNCHER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))
#define ROXENLAUNCHER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_APPLICATION))
#define ROXENLAUNCHER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_APPLICATION, RoxenlauncherApplicationClass))

typedef struct _RoxenlauncherApplication RoxenlauncherApplication;
typedef struct _RoxenlauncherApplicationClass RoxenlauncherApplicationClass;

#define ROXENLAUNCHER_TYPE_APPLICATION_FORM (roxenlauncher_application_form_get_type ())
#define ROXENLAUNCHER_APPLICATION_FORM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_APPLICATION_FORM, RoxenlauncherApplicationForm))
#define ROXENLAUNCHER_APPLICATION_FORM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_APPLICATION_FORM, RoxenlauncherApplicationFormClass))
#define ROXENLAUNCHER_IS_APPLICATION_FORM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_APPLICATION_FORM))
#define ROXENLAUNCHER_IS_APPLICATION_FORM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_APPLICATION_FORM))
#define ROXENLAUNCHER_APPLICATION_FORM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_APPLICATION_FORM, RoxenlauncherApplicationFormClass))

typedef struct _RoxenlauncherApplicationForm RoxenlauncherApplicationForm;
typedef struct _RoxenlauncherApplicationFormClass RoxenlauncherApplicationFormClass;

#define ROXENLAUNCHER_TYPE_ABOUT (roxenlauncher_about_get_type ())
#define ROXENLAUNCHER_ABOUT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ROXENLAUNCHER_TYPE_ABOUT, RoxenlauncherAbout))
#define ROXENLAUNCHER_ABOUT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ROXENLAUNCHER_TYPE_ABOUT, RoxenlauncherAboutClass))
#define ROXENLAUNCHER_IS_ABOUT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ROXENLAUNCHER_TYPE_ABOUT))
#define ROXENLAUNCHER_IS_ABOUT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ROXENLAUNCHER_TYPE_ABOUT))
#define ROXENLAUNCHER_ABOUT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ROXENLAUNCHER_TYPE_ABOUT, RoxenlauncherAboutClass))

typedef struct _RoxenlauncherAbout RoxenlauncherAbout;
typedef struct _RoxenlauncherAboutClass RoxenlauncherAboutClass;
typedef struct _Block1Data Block1Data;
typedef struct _Block2Data Block2Data;
typedef struct _RoxenlauncherAboutPrivate RoxenlauncherAboutPrivate;

struct _RoxenlauncherMainWindow {
	GObject parent_instance;
	RoxenlauncherMainWindowPrivate * priv;
};

struct _RoxenlauncherMainWindowClass {
	GObjectClass parent_class;
};

struct _RoxenlauncherMainWindowPrivate {
	GtkBuilder* builder;
	GtkWindow* win;
	GtkScrolledWindow* sw_files;
	GtkCheckButton* cb_logging;
	GtkFileChooserButton* fc_logfile;
	GtkButton* btn_edit_file;
	GtkButton* btn_finish_file;
	GtkButton* btn_finish_all;
	GtkButton* btn_edit_app;
	GtkButton* btn_add_app;
	GtkButton* btn_remove_app;
	GtkTreeView* tv_files;
	GtkTreeView* tv_apps;
	GtkListStore* ls_files;
	GtkListStore* ls_apps;
	GtkStatusbar* statusbar;
};

struct _RoxenlauncherWindowsProperties {
	gint width;
	gint height;
	gint x;
	gint y;
};

struct _Block1Data {
	int _ref_count_;
	RoxenlauncherMainWindow * self;
	LauncherFile* lf;
	char* status;
};

struct _Block2Data {
	int _ref_count_;
	RoxenlauncherMainWindow * self;
	LauncherFile* lf;
};

struct _RoxenlauncherAbout {
	GObject parent_instance;
	RoxenlauncherAboutPrivate * priv;
};

struct _RoxenlauncherAboutClass {
	GObjectClass parent_class;
};


extern RoxenlauncherWindowsProperties winprops;
static gpointer roxenlauncher_main_window_parent_class = NULL;
static gpointer roxenlauncher_about_parent_class = NULL;

GType roxenlauncher_main_window_get_type (void);
#define ROXENLAUNCHER_MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ROXENLAUNCHER_TYPE_MAIN_WINDOW, RoxenlauncherMainWindowPrivate))
enum  {
	ROXENLAUNCHER_MAIN_WINDOW_DUMMY_PROPERTY
};
char* roxenlauncher_get_ui_path (const char* local_path);
#define ROXENLAUNCHER_APP_MAIN_UI_FILENAME "mainwindow.ui"
static GObject* roxenlauncher_main_window_gtkobj (RoxenlauncherMainWindow* self, const char* name);
GType roxenlauncher_windows_properties_get_type (void);
RoxenlauncherWindowsProperties* roxenlauncher_windows_properties_dup (const RoxenlauncherWindowsProperties* self);
void roxenlauncher_windows_properties_free (RoxenlauncherWindowsProperties* self);
void roxenlauncher_save_window_properties (gint width, gint height, gint x, gint y);
static gboolean _lambda0_ (GtkWidget* widget, GdkEventConfigure* event, RoxenlauncherMainWindow* self);
static gboolean __lambda0__gtk_widget_configure_event (GtkWidget* _sender, GdkEventConfigure* event, gpointer self);
void roxenlauncher_main_window_on_window_destroy (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_window_destroy_gtk_object_destroy (GtkWindow* _sender, gpointer self);
static void _lambda1_ (RoxenlauncherMainWindow* self);
static void __lambda1__gtk_toggle_button_toggled (GtkCheckButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_edit_file_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_edit_file_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_finish_file_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_finish_file_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_finish_all_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_finish_all_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _roxenlauncher_main_window_on_window_destroy_gtk_menu_item_activate (GtkImageMenuItem* _sender, gpointer self);
static void roxenlauncher_main_window_on_about (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_about_gtk_menu_item_activate (GtkImageMenuItem* _sender, gpointer self);
static void roxenlauncher_main_window_on_tv_files_activated (RoxenlauncherMainWindow* self, GtkTreePath* path, GtkTreeViewColumn* col);
static void _roxenlauncher_main_window_on_tv_files_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
GType launcher_file_get_type (void);
RoxenlauncherDateTime* roxenlauncher_date_time_new (guint year, guint month, guint date, guint hour, guint minute, guint second);
RoxenlauncherDateTime* roxenlauncher_date_time_construct (GType object_type, guint year, guint month, guint date, guint hour, guint minute, guint second);
GType roxenlauncher_date_time_get_type (void);
time_t roxenlauncher_date_time_to_unixtime (RoxenlauncherDateTime* self);
GeeArrayList* launcher_file_get_files (void);
RoxenlauncherDateTime* launcher_file_get_last_upload (LauncherFile* self);
char* roxenlauncher_date_time_format (RoxenlauncherDateTime* self, const char* fmt);
#define ROXENLAUNCHER_APP_DATE_FORMAT "%Y-%m-%d %H:%M"
char* launcher_file_get_uri (LauncherFile* self);
char* launcher_file_status_as_string (LauncherFile* self);
static void roxenlauncher_main_window_set_file_count (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_on_tv_files_selection_changed (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_tv_files_selection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self);
static gboolean roxenlauncher_main_window_on_tv_files_key_release_event (RoxenlauncherMainWindow* self, GtkWidget* source, GdkEventKey* key);
static gboolean _roxenlauncher_main_window_on_tv_files_key_release_event_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
GType roxenlauncher_application_get_type (void);
GeeArrayList* roxenlauncher_application_get_applications (void);
const char* roxenlauncher_application_get_mimetype (RoxenlauncherApplication* self);
const char* roxenlauncher_application_get_name (RoxenlauncherApplication* self);
static void roxenlauncher_main_window_on_tv_apps_activated (RoxenlauncherMainWindow* self, GtkTreePath* path, GtkTreeViewColumn* col);
static void _roxenlauncher_main_window_on_tv_apps_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
static void roxenlauncher_main_window_on_tv_apps_selection_changed (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_tv_apps_selection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self);
RoxenlauncherApplication* roxenlauncher_main_window_editor_dialog_new (RoxenlauncherMainWindow* self, const char* content_type);
static void _lambda10_ (RoxenlauncherMainWindow* self);
static void __lambda10__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_edit_app_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_edit_app_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void roxenlauncher_main_window_on_btn_remove_app_clicked (RoxenlauncherMainWindow* self);
static void _roxenlauncher_main_window_on_btn_remove_app_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static gboolean roxenlauncher_main_window_on_tv_apps_key_release_event (RoxenlauncherMainWindow* self, GtkWidget* source, GdkEventKey* key);
static gboolean _roxenlauncher_main_window_on_tv_apps_key_release_event_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
void roxenlauncher_main_window_init (RoxenlauncherMainWindow* self);
RoxenlauncherApplicationForm* roxenlauncher_application_form_new (void);
RoxenlauncherApplicationForm* roxenlauncher_application_form_construct (GType object_type);
GType roxenlauncher_application_form_get_type (void);
void roxenlauncher_application_form_set_content_type (RoxenlauncherApplicationForm* self, const char* value);
void roxenlauncher_application_form_run (RoxenlauncherApplicationForm* self);
gboolean roxenlauncher_application_form_get_response (RoxenlauncherApplicationForm* self);
const char* roxenlauncher_application_form_get_editor_name (RoxenlauncherApplicationForm* self);
const char* roxenlauncher_application_form_get_editor_command (RoxenlauncherApplicationForm* self);
const char* roxenlauncher_application_form_get_content_type (RoxenlauncherApplicationForm* self);
const char* roxenlauncher_application_form_get_editor_arguments (RoxenlauncherApplicationForm* self);
RoxenlauncherApplication* roxenlauncher_application_new (const char* name, const char* command, const char* mimetype, const char* arguments);
RoxenlauncherApplication* roxenlauncher_application_construct (GType object_type, const char* name, const char* command, const char* mimetype, const char* arguments);
void roxenlauncher_application_add_application (RoxenlauncherApplication* app);
RoxenlauncherAbout* roxenlauncher_about_new (void);
RoxenlauncherAbout* roxenlauncher_about_construct (GType object_type);
GType roxenlauncher_about_get_type (void);
GtkWindow* roxenlauncher_main_window_get_window (RoxenlauncherMainWindow* self);
static RoxenlauncherApplication* roxenlauncher_main_window_get_selected_application (RoxenlauncherMainWindow* self, GtkTreeModel** _model, GtkTreeIter* _iter);
void roxenlauncher_application_form_set_editor_name (RoxenlauncherApplicationForm* self, const char* value);
const char* roxenlauncher_application_get_command (RoxenlauncherApplication* self);
void roxenlauncher_application_form_set_editor_command (RoxenlauncherApplicationForm* self, const char* value);
const char* roxenlauncher_application_get_arguments (RoxenlauncherApplication* self);
void roxenlauncher_application_form_set_editor_arguments (RoxenlauncherApplicationForm* self, const char* value);
void roxenlauncher_application_set_mimetype (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_name (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_command (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_set_arguments (RoxenlauncherApplication* self, const char* value);
void roxenlauncher_application_save_list (void);
void roxenlauncher_main_window_editor_dialog_edit (RoxenlauncherMainWindow* self);
const char* launcher_file_get_id (LauncherFile* self);
static gboolean _lambda5_ (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, Block1Data* _data1_);
static gboolean __lambda5__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (Block1Data* _data1_);
void roxenlauncher_main_window_set_file_status (RoxenlauncherMainWindow* self, LauncherFile* lf, const char* status);
void launcher_file_add_file (LauncherFile* lf);
gint launcher_file_get_status (LauncherFile* self);
char* roxenlauncher_date_time_to_string (RoxenlauncherDateTime* self);
void roxenlauncher_main_window_set_file_selection (RoxenlauncherMainWindow* self, LauncherFile* lf);
void roxenlauncher_main_window_add_launcher_file (RoxenlauncherMainWindow* self, LauncherFile* lf);
static gboolean _lambda3_ (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, Block2Data* _data2_);
static gboolean __lambda3__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (Block2Data* _data2_);
static void roxenlauncher_main_window_remove_application (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_begin_edit_file (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_finish_file (RoxenlauncherMainWindow* self);
void roxenlauncher_main_window_finish_all_files (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_set_app_buttons_sensitivity (RoxenlauncherMainWindow* self);
static void roxenlauncher_main_window_set_buttons_sensitivity (RoxenlauncherMainWindow* self);
static LauncherFile* roxenlauncher_main_window_get_selected_file (RoxenlauncherMainWindow* self, GtkTreeModel** _model, GtkTreeIter* _iter);
gboolean roxenlauncher_alert_confirm (GtkWindow* parent, const char* message);
gboolean launcher_file_delete (LauncherFile* self);
void launcher_file_remove_file (LauncherFile* file);
void launcher_file_clear_files (void);
RoxenlauncherApplication* launcher_file_get_application (LauncherFile* self);
void launcher_file_unset_application (LauncherFile* self);
void roxenlauncher_application_remove_application (RoxenlauncherApplication* app);
void launcher_file_download (LauncherFile* self, gboolean do_launch_editor);
static void roxenlauncher_main_window_set_status (RoxenlauncherMainWindow* self, const char* text);
RoxenlauncherMainWindow* roxenlauncher_main_window_new (void);
RoxenlauncherMainWindow* roxenlauncher_main_window_construct (GType object_type);
static void roxenlauncher_main_window_finalize (GObject* obj);
enum  {
	ROXENLAUNCHER_ABOUT_DUMMY_PROPERTY
};
static GObject * roxenlauncher_about_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static int _vala_strcmp0 (const char * str1, const char * str2);



static gboolean _lambda0_ (GtkWidget* widget, GdkEventConfigure* event, RoxenlauncherMainWindow* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (widget != NULL, FALSE);
	if ((*event).type == GDK_CONFIGURE) {
		gboolean _tmp1_ = FALSE;
		gboolean _tmp2_ = FALSE;
		gboolean _tmp3_ = FALSE;
		if ((*event).width != winprops.width) {
			_tmp3_ = TRUE;
		} else {
			_tmp3_ = (*event).height != winprops.height;
		}
		if (_tmp3_) {
			_tmp2_ = TRUE;
		} else {
			_tmp2_ = (*event).x != winprops.x;
		}
		if (_tmp2_) {
			_tmp1_ = TRUE;
		} else {
			_tmp1_ = (*event).y != winprops.y;
		}
		_tmp0_ = _tmp1_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		roxenlauncher_save_window_properties ((*event).width, (*event).height, (*event).x, (*event).y);
	}
}


static gboolean __lambda0__gtk_widget_configure_event (GtkWidget* _sender, GdkEventConfigure* event, gpointer self) {
	return _lambda0_ (_sender, event, self);
}


static void _roxenlauncher_main_window_on_window_destroy_gtk_object_destroy (GtkWindow* _sender, gpointer self) {
	roxenlauncher_main_window_on_window_destroy (self);
}


static void _lambda1_ (RoxenlauncherMainWindow* self) {
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->fc_logfile, gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->cb_logging));
}


static void __lambda1__gtk_toggle_button_toggled (GtkCheckButton* _sender, gpointer self) {
	_lambda1_ (self);
}


static void _roxenlauncher_main_window_on_btn_edit_file_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_edit_file_clicked (self);
}


static void _roxenlauncher_main_window_on_btn_finish_file_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_finish_file_clicked (self);
}


static void _roxenlauncher_main_window_on_btn_finish_all_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_finish_all_clicked (self);
}


static void _roxenlauncher_main_window_on_window_destroy_gtk_menu_item_activate (GtkImageMenuItem* _sender, gpointer self) {
	roxenlauncher_main_window_on_window_destroy (self);
}


static void _roxenlauncher_main_window_on_about_gtk_menu_item_activate (GtkImageMenuItem* _sender, gpointer self) {
	roxenlauncher_main_window_on_about (self);
}


static void _roxenlauncher_main_window_on_tv_files_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
	roxenlauncher_main_window_on_tv_files_activated (self, path, column);
}


static void _roxenlauncher_main_window_on_tv_files_selection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self) {
	roxenlauncher_main_window_on_tv_files_selection_changed (self);
}


static gboolean _roxenlauncher_main_window_on_tv_files_key_release_event_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	return roxenlauncher_main_window_on_tv_files_key_release_event (self, _sender, event);
}


static void _roxenlauncher_main_window_on_tv_apps_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
	roxenlauncher_main_window_on_tv_apps_activated (self, path, column);
}


static void _roxenlauncher_main_window_on_tv_apps_selection_changed_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self) {
	roxenlauncher_main_window_on_tv_apps_selection_changed (self);
}


static void _lambda10_ (RoxenlauncherMainWindow* self) {
	RoxenlauncherApplication* _tmp0_;
	_tmp0_ = roxenlauncher_main_window_editor_dialog_new (self, "");
	_g_object_unref0 (_tmp0_);
}


static void __lambda10__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	_lambda10_ (self);
}


static void _roxenlauncher_main_window_on_btn_edit_app_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_edit_app_clicked (self);
}


static void _roxenlauncher_main_window_on_btn_remove_app_clicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	roxenlauncher_main_window_on_btn_remove_app_clicked (self);
}


static gboolean _roxenlauncher_main_window_on_tv_apps_key_release_event_gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	return roxenlauncher_main_window_on_tv_apps_key_release_event (self, _sender, event);
}


void roxenlauncher_main_window_init (RoxenlauncherMainWindow* self) {
	GError * _inner_error_;
	GtkBuilder* _tmp0_;
	char* filename;
	GtkWindow* _tmp1_;
	GtkScrolledWindow* _tmp2_;
	GtkFileChooserButton* _tmp3_;
	GtkCheckButton* _tmp4_;
	GtkButton* _tmp5_;
	GtkButton* _tmp6_;
	GtkButton* _tmp7_;
	GtkButton* _tmp8_;
	GtkButton* _tmp9_;
	GtkButton* _tmp10_;
	GtkTreeView* _tmp11_;
	GtkListStore* _tmp12_;
	GtkTreeView* _tmp13_;
	GtkListStore* _tmp14_;
	GtkStatusbar* _tmp15_;
	gboolean _tmp16_ = FALSE;
	gboolean _tmp17_ = FALSE;
	GtkImageMenuItem* _tmp18_;
	GtkImageMenuItem* _tmp19_;
	GtkListStore* _tmp20_;
	char** _tmp22_;
	gint cols_size;
	gint cols_length1;
	char** _tmp21_ = NULL;
	char** cols;
	RoxenlauncherDateTime* _tmp24_;
	time_t _tmp25_;
	time_t dummy_date;
	GeeArrayList* _tmp31_;
	gboolean _tmp32_;
	GtkListStore* _tmp33_;
	char** _tmp35_;
	char** _tmp34_ = NULL;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	self->priv->builder = (_tmp0_ = gtk_builder_new (), _g_object_unref0 (self->priv->builder), _tmp0_);
	filename = roxenlauncher_get_ui_path (ROXENLAUNCHER_APP_MAIN_UI_FILENAME);
	if (filename == NULL) {
		g_error ("mainwindow.vala:55: Unable to load GUI for main window");
	}
	{
		gtk_builder_set_translation_domain (self->priv->builder, GETTEXT_PACKAGE);
		gtk_builder_add_from_file (self->priv->builder, filename, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch25_g_error;
			goto __finally25;
		}
	}
	goto __finally25;
	__catch25_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_error ("mainwindow.vala:62: GUI load error: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally25:
	if (_inner_error_ != NULL) {
		_g_free0 (filename);
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return;
	}
	self->priv->win = (_tmp1_ = GTK_WINDOW (roxenlauncher_main_window_gtkobj (self, "mainwindow")), _g_object_unref0 (self->priv->win), _tmp1_);
	self->priv->sw_files = (_tmp2_ = GTK_SCROLLED_WINDOW (roxenlauncher_main_window_gtkobj (self, "sw_files")), _g_object_unref0 (self->priv->sw_files), _tmp2_);
	self->priv->fc_logfile = (_tmp3_ = GTK_FILE_CHOOSER_BUTTON (roxenlauncher_main_window_gtkobj (self, "fc_logfile")), _g_object_unref0 (self->priv->fc_logfile), _tmp3_);
	self->priv->cb_logging = (_tmp4_ = GTK_CHECK_BUTTON (roxenlauncher_main_window_gtkobj (self, "cb_logging")), _g_object_unref0 (self->priv->cb_logging), _tmp4_);
	self->priv->btn_edit_file = (_tmp5_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_edit_file")), _g_object_unref0 (self->priv->btn_edit_file), _tmp5_);
	self->priv->btn_finish_file = (_tmp6_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_finish_file")), _g_object_unref0 (self->priv->btn_finish_file), _tmp6_);
	self->priv->btn_finish_all = (_tmp7_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_finish_all")), _g_object_unref0 (self->priv->btn_finish_all), _tmp7_);
	self->priv->btn_edit_app = (_tmp8_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_edit_app")), _g_object_unref0 (self->priv->btn_edit_app), _tmp8_);
	self->priv->btn_add_app = (_tmp9_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_add_app")), _g_object_unref0 (self->priv->btn_add_app), _tmp9_);
	self->priv->btn_remove_app = (_tmp10_ = GTK_BUTTON (roxenlauncher_main_window_gtkobj (self, "btn_remove_app")), _g_object_unref0 (self->priv->btn_remove_app), _tmp10_);
	self->priv->tv_files = (_tmp11_ = GTK_TREE_VIEW (roxenlauncher_main_window_gtkobj (self, "tv_files")), _g_object_unref0 (self->priv->tv_files), _tmp11_);
	self->priv->ls_files = (_tmp12_ = GTK_LIST_STORE (roxenlauncher_main_window_gtkobj (self, "ls_files")), _g_object_unref0 (self->priv->ls_files), _tmp12_);
	self->priv->tv_apps = (_tmp13_ = GTK_TREE_VIEW (roxenlauncher_main_window_gtkobj (self, "tv_apps")), _g_object_unref0 (self->priv->tv_apps), _tmp13_);
	self->priv->ls_apps = (_tmp14_ = GTK_LIST_STORE (roxenlauncher_main_window_gtkobj (self, "ls_apps")), _g_object_unref0 (self->priv->ls_apps), _tmp14_);
	self->priv->statusbar = (_tmp15_ = GTK_STATUSBAR (roxenlauncher_main_window_gtkobj (self, "statusbar1")), _g_object_unref0 (self->priv->statusbar), _tmp15_);
	if (winprops.width > 0) {
		_tmp16_ = winprops.height > 0;
	} else {
		_tmp16_ = FALSE;
	}
	if (_tmp16_) {
		gtk_window_set_default_size (self->priv->win, winprops.width, winprops.height);
	}
	if (winprops.x > 0) {
		_tmp17_ = TRUE;
	} else {
		_tmp17_ = winprops.y > 0;
	}
	if (_tmp17_) {
		gtk_window_move (self->priv->win, winprops.x, winprops.y);
	}
	g_signal_connect_object ((GtkWidget*) self->priv->win, "configure-event", (GCallback) __lambda0__gtk_widget_configure_event, self, 0);
	g_signal_connect_object ((GtkObject*) self->priv->win, "destroy", (GCallback) _roxenlauncher_main_window_on_window_destroy_gtk_object_destroy, self, 0);
	g_signal_connect_object ((GtkToggleButton*) self->priv->cb_logging, "toggled", (GCallback) __lambda1__gtk_toggle_button_toggled, self, 0);
	g_signal_connect_object (self->priv->btn_edit_file, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_edit_file_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btn_finish_file, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_finish_file_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btn_finish_all, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_finish_all_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object ((GtkMenuItem*) (_tmp18_ = GTK_IMAGE_MENU_ITEM (roxenlauncher_main_window_gtkobj (self, "im_quit"))), "activate", (GCallback) _roxenlauncher_main_window_on_window_destroy_gtk_menu_item_activate, self, 0);
	_g_object_unref0 (_tmp18_);
	g_signal_connect_object ((GtkMenuItem*) (_tmp19_ = GTK_IMAGE_MENU_ITEM (roxenlauncher_main_window_gtkobj (self, "im_about"))), "activate", (GCallback) _roxenlauncher_main_window_on_about_gtk_menu_item_activate, self, 0);
	_g_object_unref0 (_tmp19_);
	g_signal_connect_object (self->priv->tv_files, "row-activated", (GCallback) _roxenlauncher_main_window_on_tv_files_activated_gtk_tree_view_row_activated, self, 0);
	self->priv->ls_files = (_tmp20_ = gtk_list_store_new (4, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, TYPE_LAUNCHER_FILE, NULL), _g_object_unref0 (self->priv->ls_files), _tmp20_);
	gtk_tree_view_set_model (self->priv->tv_files, (GtkTreeModel*) self->priv->ls_files);
	cols = (_tmp22_ = (_tmp21_ = g_new0 (char*, 3 + 1), _tmp21_[0] = g_strdup (_ ("File")), _tmp21_[1] = g_strdup (_ ("Status")), _tmp21_[2] = g_strdup (_ ("Last upload")), _tmp21_), cols_length1 = 3, cols_size = cols_length1, _tmp22_);
	{
		gulong i;
		i = (gulong) 0;
		{
			gboolean _tmp23_;
			_tmp23_ = TRUE;
			while (TRUE) {
				GtkCellRendererText* ct;
				GtkTreeViewColumn* cl;
				if (!_tmp23_) {
					i++;
				}
				_tmp23_ = FALSE;
				if (!(i < cols_length1)) {
					break;
				}
				ct = g_object_ref_sink ((GtkCellRendererText*) gtk_cell_renderer_text_new ());
				cl = g_object_ref_sink (gtk_tree_view_column_new_with_attributes (cols[i], (GtkCellRenderer*) ct, "text", i, NULL, NULL));
				gtk_tree_view_column_set_resizable (cl, TRUE);
				gtk_tree_view_column_set_expand (cl, TRUE);
				gtk_tree_view_insert_column (self->priv->tv_files, cl, -1);
				_g_object_unref0 (ct);
				_g_object_unref0 (cl);
			}
		}
	}
	dummy_date = (_tmp25_ = roxenlauncher_date_time_to_unixtime (_tmp24_ = roxenlauncher_date_time_new (1970, 1, 1, 1, 0, 0)), _g_object_unref0 (_tmp24_), _tmp25_);
	{
		GeeArrayList* _tmp26_;
		GeeIterator* _tmp27_;
		GeeIterator* _lf_it;
		_lf_it = (_tmp27_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) (_tmp26_ = launcher_file_get_files ())), _g_object_unref0 (_tmp26_), _tmp27_);
		while (TRUE) {
			LauncherFile* lf;
			GtkTreeIter iter = {0};
			char* last_upload;
			char* _tmp30_;
			char* _tmp29_;
			if (!gee_iterator_next (_lf_it)) {
				break;
			}
			lf = (LauncherFile*) gee_iterator_get (_lf_it);
			gtk_list_store_append (self->priv->ls_files, &iter);
			last_upload = g_strdup ("");
			if (roxenlauncher_date_time_to_unixtime (launcher_file_get_last_upload (lf)) > dummy_date) {
				char* _tmp28_;
				last_upload = (_tmp28_ = roxenlauncher_date_time_format (launcher_file_get_last_upload (lf), ROXENLAUNCHER_APP_DATE_FORMAT), _g_free0 (last_upload), _tmp28_);
			}
			gtk_list_store_set (self->priv->ls_files, &iter, 0, _tmp29_ = launcher_file_get_uri (lf), 1, _tmp30_ = launcher_file_status_as_string (lf), 2, last_upload, 3, lf, -1, -1);
			_g_free0 (_tmp30_);
			_g_free0 (_tmp29_);
			_g_object_unref0 (lf);
			_g_free0 (last_upload);
		}
		_g_object_unref0 (_lf_it);
	}
	if ((_tmp32_ = gee_collection_get_size ((GeeCollection*) (_tmp31_ = launcher_file_get_files ())) > 0, _g_object_unref0 (_tmp31_), _tmp32_)) {
		gtk_widget_set_sensitive ((GtkWidget*) self->priv->btn_finish_all, TRUE);
	}
	roxenlauncher_main_window_set_file_count (self);
	g_signal_connect_object (gtk_tree_view_get_selection (self->priv->tv_files), "changed", (GCallback) _roxenlauncher_main_window_on_tv_files_selection_changed_gtk_tree_selection_changed, self, 0);
	g_signal_connect_object ((GtkWidget*) self->priv->tv_files, "key-release-event", (GCallback) _roxenlauncher_main_window_on_tv_files_key_release_event_gtk_widget_key_release_event, self, 0);
	self->priv->ls_apps = (_tmp33_ = gtk_list_store_new (3, G_TYPE_STRING, G_TYPE_STRING, ROXENLAUNCHER_TYPE_APPLICATION, NULL), _g_object_unref0 (self->priv->ls_apps), _tmp33_);
	gtk_tree_view_set_model (self->priv->tv_apps, (GtkTreeModel*) self->priv->ls_apps);
	cols = (_tmp35_ = (_tmp34_ = g_new0 (char*, 2 + 1), _tmp34_[0] = g_strdup (_ ("Content type")), _tmp34_[1] = g_strdup (_ ("Application")), _tmp34_), cols = (_vala_array_free (cols, cols_length1, (GDestroyNotify) g_free), NULL), cols_length1 = 2, cols_size = cols_length1, _tmp35_);
	{
		gulong i;
		i = (gulong) 0;
		{
			gboolean _tmp36_;
			_tmp36_ = TRUE;
			while (TRUE) {
				GtkCellRendererText* ct;
				GtkTreeViewColumn* cl;
				if (!_tmp36_) {
					i++;
				}
				_tmp36_ = FALSE;
				if (!(i < cols_length1)) {
					break;
				}
				ct = g_object_ref_sink ((GtkCellRendererText*) gtk_cell_renderer_text_new ());
				cl = g_object_ref_sink (gtk_tree_view_column_new_with_attributes (cols[i], (GtkCellRenderer*) ct, "text", i, NULL, NULL));
				gtk_tree_view_column_set_resizable (cl, TRUE);
				gtk_tree_view_insert_column (self->priv->tv_apps, cl, -1);
				_g_object_unref0 (ct);
				_g_object_unref0 (cl);
			}
		}
	}
	{
		GeeArrayList* _tmp37_;
		GeeIterator* _tmp38_;
		GeeIterator* _app_it;
		_app_it = (_tmp38_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) (_tmp37_ = roxenlauncher_application_get_applications ())), _g_object_unref0 (_tmp37_), _tmp38_);
		while (TRUE) {
			RoxenlauncherApplication* app;
			GtkTreeIter iter = {0};
			if (!gee_iterator_next (_app_it)) {
				break;
			}
			app = (RoxenlauncherApplication*) gee_iterator_get (_app_it);
			gtk_list_store_append (self->priv->ls_apps, &iter);
			gtk_list_store_set (self->priv->ls_apps, &iter, 0, roxenlauncher_application_get_mimetype (app), 1, roxenlauncher_application_get_name (app), 2, app, -1, -1);
			_g_object_unref0 (app);
		}
		_g_object_unref0 (_app_it);
	}
	g_signal_connect_object (self->priv->tv_apps, "row-activated", (GCallback) _roxenlauncher_main_window_on_tv_apps_activated_gtk_tree_view_row_activated, self, 0);
	g_signal_connect_object (gtk_tree_view_get_selection (self->priv->tv_apps), "changed", (GCallback) _roxenlauncher_main_window_on_tv_apps_selection_changed_gtk_tree_selection_changed, self, 0);
	g_signal_connect_object (self->priv->btn_add_app, "clicked", (GCallback) __lambda10__gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btn_edit_app, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_edit_app_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btn_remove_app, "clicked", (GCallback) _roxenlauncher_main_window_on_btn_remove_app_clicked_gtk_button_clicked, self, 0);
	g_signal_connect_object ((GtkWidget*) self->priv->tv_apps, "key-release-event", (GCallback) _roxenlauncher_main_window_on_tv_apps_key_release_event_gtk_widget_key_release_event, self, 0);
	_g_free0 (filename);
	cols = (_vala_array_free (cols, cols_length1, (GDestroyNotify) g_free), NULL);
}


RoxenlauncherApplication* roxenlauncher_main_window_editor_dialog_new (RoxenlauncherMainWindow* self, const char* content_type) {
	RoxenlauncherApplication* result;
	RoxenlauncherApplicationForm* d;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (content_type != NULL, NULL);
	d = roxenlauncher_application_form_new ();
	roxenlauncher_application_form_set_content_type (d, content_type);
	roxenlauncher_application_form_run (d);
	if (roxenlauncher_application_form_get_response (d)) {
		RoxenlauncherApplication* app;
		GtkTreeIter iter = {0};
		app = roxenlauncher_application_new (roxenlauncher_application_form_get_editor_name (d), roxenlauncher_application_form_get_editor_command (d), roxenlauncher_application_form_get_content_type (d), roxenlauncher_application_form_get_editor_arguments (d));
		roxenlauncher_application_add_application (app);
		gtk_list_store_append (self->priv->ls_apps, &iter);
		gtk_list_store_set (self->priv->ls_apps, &iter, 0, roxenlauncher_application_get_mimetype (app), 1, roxenlauncher_application_get_name (app), 2, app, -1);
		result = app;
		_g_object_unref0 (d);
		return result;
	}
	result = NULL;
	_g_object_unref0 (d);
	return result;
}


static void roxenlauncher_main_window_on_about (RoxenlauncherMainWindow* self) {
	RoxenlauncherAbout* a;
	RoxenlauncherAbout* _tmp0_;
	g_return_if_fail (self != NULL);
	a = roxenlauncher_about_new ();
	a = (_tmp0_ = NULL, _g_object_unref0 (a), _tmp0_);
	_g_object_unref0 (a);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GtkWindow* roxenlauncher_main_window_get_window (RoxenlauncherMainWindow* self) {
	GtkWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = _g_object_ref0 (self->priv->win);
	return result;
}


void roxenlauncher_main_window_editor_dialog_edit (RoxenlauncherMainWindow* self) {
	GtkTreeModel* model;
	GtkTreeIter iter = {0};
	GtkTreeModel* _tmp2_;
	RoxenlauncherApplication* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	RoxenlauncherApplication* app;
	g_return_if_fail (self != NULL);
	model = NULL;
	app = (_tmp1_ = roxenlauncher_main_window_get_selected_application (self, &_tmp0_, &iter), model = (_tmp2_ = _tmp0_, _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (app != NULL) {
		RoxenlauncherApplicationForm* d;
		d = roxenlauncher_application_form_new ();
		roxenlauncher_application_form_set_content_type (d, roxenlauncher_application_get_mimetype (app));
		roxenlauncher_application_form_set_editor_name (d, roxenlauncher_application_get_name (app));
		roxenlauncher_application_form_set_editor_command (d, roxenlauncher_application_get_command (app));
		roxenlauncher_application_form_set_editor_arguments (d, roxenlauncher_application_get_arguments (app));
		roxenlauncher_application_form_run (d);
		if (roxenlauncher_application_form_get_response (d)) {
			roxenlauncher_application_set_mimetype (app, roxenlauncher_application_form_get_content_type (d));
			roxenlauncher_application_set_name (app, roxenlauncher_application_form_get_editor_name (d));
			roxenlauncher_application_set_command (app, roxenlauncher_application_form_get_editor_command (d));
			roxenlauncher_application_set_arguments (app, roxenlauncher_application_form_get_editor_arguments (d));
			roxenlauncher_application_save_list ();
			gtk_list_store_set (self->priv->ls_apps, &iter, 0, roxenlauncher_application_form_get_content_type (d), 1, roxenlauncher_application_form_get_editor_name (d), -1);
		}
		_g_object_unref0 (d);
	}
	_g_object_unref0 (model);
	_g_object_unref0 (app);
}


static gboolean _lambda5_ (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, Block1Data* _data1_) {
	RoxenlauncherMainWindow * self;
	gboolean result;
	GValue v = {0};
	GValue _tmp1_;
	GValue _tmp0_ = {0};
	LauncherFile* f;
	gboolean _tmp2_ = FALSE;
	self = _data1_->self;
	g_return_val_if_fail (model != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	gtk_tree_model_get_value (model, iter, 3, &_tmp0_);
	v = (_tmp1_ = _tmp0_, G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL, _tmp1_);
	f = _g_object_ref0 (g_value_get_object (&v));
	if (f != NULL) {
		_tmp2_ = _vala_strcmp0 (launcher_file_get_id (_data1_->lf), launcher_file_get_id (f)) == 0;
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		RoxenlauncherDateTime* _tmp3_;
		gboolean _tmp4_;
		gtk_list_store_set (self->priv->ls_files, iter, 1, _data1_->status, -1);
		if ((_tmp4_ = roxenlauncher_date_time_to_unixtime (launcher_file_get_last_upload (f)) > roxenlauncher_date_time_to_unixtime (_tmp3_ = roxenlauncher_date_time_new (1970, 1, 1, 1, 0, 0)), _g_object_unref0 (_tmp3_), _tmp4_)) {
			char* _tmp5_;
			gtk_list_store_set (self->priv->ls_files, iter, 2, _tmp5_ = roxenlauncher_date_time_format (launcher_file_get_last_upload (f), ROXENLAUNCHER_APP_DATE_FORMAT), -1);
			_g_free0 (_tmp5_);
		}
		result = TRUE;
		G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL;
		_g_object_unref0 (f);
		return result;
	}
	g_value_unset (&v);
	result = FALSE;
	G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL;
	_g_object_unref0 (f);
	return result;
}


static gboolean __lambda5__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self) {
	return _lambda5_ (model, path, iter, self);
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	++_data1_->_ref_count_;
	return _data1_;
}


static void block1_data_unref (Block1Data* _data1_) {
	if ((--_data1_->_ref_count_) == 0) {
		_g_object_unref0 (_data1_->self);
		_g_object_unref0 (_data1_->lf);
		_g_free0 (_data1_->status);
		g_slice_free (Block1Data, _data1_);
	}
}


void roxenlauncher_main_window_set_file_status (RoxenlauncherMainWindow* self, LauncherFile* lf, const char* status) {
	Block1Data* _data1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (lf != NULL);
	g_return_if_fail (status != NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_data1_->lf = _g_object_ref0 (lf);
	_data1_->status = g_strdup (status);
	gtk_tree_model_foreach ((GtkTreeModel*) self->priv->ls_files, __lambda5__gtk_tree_model_foreach_func, _data1_);
	block1_data_unref (_data1_);
}


void roxenlauncher_main_window_add_launcher_file (RoxenlauncherMainWindow* self, LauncherFile* lf) {
	GtkTreeIter iter = {0};
	char* last_upload;
	char* _tmp2_;
	char* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (lf != NULL);
	launcher_file_add_file (lf);
	gtk_list_store_append (self->priv->ls_files, &iter);
	last_upload = g_strdup ("");
	if (launcher_file_get_status (lf) == 0) {
		char* _tmp0_;
		last_upload = (_tmp0_ = roxenlauncher_date_time_to_string (launcher_file_get_last_upload (lf)), _g_free0 (last_upload), _tmp0_);
	}
	gtk_list_store_set (self->priv->ls_files, &iter, 0, _tmp1_ = launcher_file_get_uri (lf), 1, _tmp2_ = launcher_file_status_as_string (lf), 2, last_upload, 3, lf, -1, -1);
	_g_free0 (_tmp2_);
	_g_free0 (_tmp1_);
	roxenlauncher_main_window_set_file_selection (self, lf);
	roxenlauncher_main_window_set_file_count (self);
	_g_free0 (last_upload);
}


static gboolean _lambda3_ (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, Block2Data* _data2_) {
	RoxenlauncherMainWindow * self;
	gboolean result;
	GError * _inner_error_;
	GValue v = {0};
	GValue _tmp1_;
	GValue _tmp0_ = {0};
	self = _data2_->self;
	g_return_val_if_fail (model != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	_inner_error_ = NULL;
	gtk_tree_model_get_value (model, iter, 3, &_tmp0_);
	v = (_tmp1_ = _tmp0_, G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL, _tmp1_);
	{
		LauncherFile* f;
		gboolean _tmp2_ = FALSE;
		f = _g_object_ref0 (g_value_get_object (&v));
		if (f != NULL) {
			_tmp2_ = _vala_strcmp0 (launcher_file_get_id (f), launcher_file_get_id (_data2_->lf)) == 0;
		} else {
			_tmp2_ = FALSE;
		}
		if (_tmp2_) {
			gtk_tree_selection_select_path (gtk_tree_view_get_selection (self->priv->tv_files), path);
			result = TRUE;
			_g_object_unref0 (f);
			G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL;
			return result;
		}
		_g_object_unref0 (f);
	}
	goto __finally26;
	__catch26_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("mainwindow.vala:324: set_file_selection(): %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally26:
	if (_inner_error_ != NULL) {
		G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL;
		g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	g_value_unset (&v);
	result = FALSE;
	G_IS_VALUE (&v) ? (g_value_unset (&v), NULL) : NULL;
	return result;
}


static gboolean __lambda3__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self) {
	return _lambda3_ (model, path, iter, self);
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
	++_data2_->_ref_count_;
	return _data2_;
}


static void block2_data_unref (Block2Data* _data2_) {
	if ((--_data2_->_ref_count_) == 0) {
		_g_object_unref0 (_data2_->self);
		_g_object_unref0 (_data2_->lf);
		g_slice_free (Block2Data, _data2_);
	}
}


void roxenlauncher_main_window_set_file_selection (RoxenlauncherMainWindow* self, LauncherFile* lf) {
	Block2Data* _data2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (lf != NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_data2_->self = g_object_ref (self);
	_data2_->lf = _g_object_ref0 (lf);
	gtk_tree_model_foreach ((GtkTreeModel*) self->priv->ls_files, __lambda3__gtk_tree_model_foreach_func, _data2_);
	block2_data_unref (_data2_);
}


static GObject* roxenlauncher_main_window_gtkobj (RoxenlauncherMainWindow* self, const char* name) {
	GObject* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	result = _g_object_ref0 (gtk_builder_get_object (self->priv->builder, name));
	return result;
}


static void roxenlauncher_main_window_on_btn_edit_app_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_editor_dialog_edit (self);
}


static void roxenlauncher_main_window_on_btn_remove_app_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_remove_application (self);
}


static void roxenlauncher_main_window_on_btn_edit_file_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_begin_edit_file (self);
}


static void roxenlauncher_main_window_on_btn_finish_file_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_finish_file (self);
}


static void roxenlauncher_main_window_on_btn_finish_all_clicked (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_finish_all_files (self);
}


static void roxenlauncher_main_window_on_tv_apps_selection_changed (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_set_app_buttons_sensitivity (self);
}


static void roxenlauncher_main_window_on_tv_files_selection_changed (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	roxenlauncher_main_window_set_buttons_sensitivity (self);
}


static void roxenlauncher_main_window_on_tv_files_activated (RoxenlauncherMainWindow* self, GtkTreePath* path, GtkTreeViewColumn* col) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (col != NULL);
	roxenlauncher_main_window_begin_edit_file (self);
}


static void roxenlauncher_main_window_on_tv_apps_activated (RoxenlauncherMainWindow* self, GtkTreePath* path, GtkTreeViewColumn* col) {
	GtkTreeModel* a;
	GtkTreeIter b = {0};
	RoxenlauncherApplication* _tmp3_;
	GtkTreeModel* _tmp2_;
	RoxenlauncherApplication* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean _tmp4_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (col != NULL);
	a = NULL;
	if ((_tmp4_ = (_tmp3_ = (_tmp1_ = roxenlauncher_main_window_get_selected_application (self, &_tmp0_, &b), a = (_tmp2_ = _tmp0_, _g_object_unref0 (a), _tmp2_), _tmp1_)) != NULL, _g_object_unref0 (_tmp3_), _tmp4_)) {
		roxenlauncher_main_window_editor_dialog_edit (self);
	}
	_g_object_unref0 (a);
}


static gboolean roxenlauncher_main_window_on_tv_files_key_release_event (RoxenlauncherMainWindow* self, GtkWidget* source, GdkEventKey* key) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	GeeArrayList* _tmp1_;
	gboolean _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (source != NULL, FALSE);
	if ((_tmp2_ = gee_collection_get_size ((GeeCollection*) (_tmp1_ = launcher_file_get_files ())) > 0, _g_object_unref0 (_tmp1_), _tmp2_)) {
		char* _tmp3_;
		_tmp0_ = _vala_strcmp0 (_tmp3_ = g_utf8_strdown (gdk_keyval_name ((*key).keyval), -1), "delete") == 0;
		_g_free0 (_tmp3_);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		GtkTreeModel* model;
		GtkTreeIter iter = {0};
		LauncherFile* _tmp7_;
		GtkTreeModel* _tmp6_;
		LauncherFile* _tmp5_;
		GtkTreeModel* _tmp4_ = NULL;
		gboolean _tmp8_;
		model = NULL;
		if ((_tmp8_ = (_tmp7_ = (_tmp5_ = roxenlauncher_main_window_get_selected_file (self, &_tmp4_, &iter), model = (_tmp6_ = _tmp4_, _g_object_unref0 (model), _tmp6_), _tmp5_)) == NULL, _g_object_unref0 (_tmp7_), _tmp8_)) {
			result = FALSE;
			_g_object_unref0 (model);
			return result;
		}
		if (roxenlauncher_alert_confirm (self->priv->win, _ ("Do you want to delete the selected file?"))) {
			roxenlauncher_main_window_finish_file (self);
			result = TRUE;
			_g_object_unref0 (model);
			return result;
		}
		_g_object_unref0 (model);
	}
	result = FALSE;
	return result;
}


static gboolean roxenlauncher_main_window_on_tv_apps_key_release_event (RoxenlauncherMainWindow* self, GtkWidget* source, GdkEventKey* key) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	GeeArrayList* _tmp1_;
	gboolean _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (source != NULL, FALSE);
	if ((_tmp2_ = gee_collection_get_size ((GeeCollection*) (_tmp1_ = roxenlauncher_application_get_applications ())) > 0, _g_object_unref0 (_tmp1_), _tmp2_)) {
		char* _tmp3_;
		_tmp0_ = _vala_strcmp0 (_tmp3_ = g_utf8_strdown (gdk_keyval_name ((*key).keyval), -1), "delete") == 0;
		_g_free0 (_tmp3_);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		GtkTreeModel* model;
		GtkTreeIter iter = {0};
		RoxenlauncherApplication* _tmp7_;
		GtkTreeModel* _tmp6_;
		RoxenlauncherApplication* _tmp5_;
		GtkTreeModel* _tmp4_ = NULL;
		gboolean _tmp8_;
		char* msg;
		model = NULL;
		if ((_tmp8_ = (_tmp7_ = (_tmp5_ = roxenlauncher_main_window_get_selected_application (self, &_tmp4_, &iter), model = (_tmp6_ = _tmp4_, _g_object_unref0 (model), _tmp6_), _tmp5_)) == NULL, _g_object_unref0 (_tmp7_), _tmp8_)) {
			result = FALSE;
			_g_object_unref0 (model);
			return result;
		}
		msg = g_strdup (_ ("Do you want to delete the selected application?"));
		if (roxenlauncher_alert_confirm (self->priv->win, msg)) {
			roxenlauncher_main_window_remove_application (self);
			result = TRUE;
			_g_object_unref0 (model);
			_g_free0 (msg);
			return result;
		}
		_g_object_unref0 (model);
		_g_free0 (msg);
	}
	result = FALSE;
	return result;
}


void roxenlauncher_main_window_on_window_destroy (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	gtk_main_quit ();
}


static void roxenlauncher_main_window_set_app_buttons_sensitivity (RoxenlauncherMainWindow* self) {
	GtkTreeSelection* sel;
	GtkTreeIter iter = {0};
	GtkTreeModel* model;
	GtkTreeModel* _tmp2_;
	gboolean _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean is_active;
	g_return_if_fail (self != NULL);
	sel = _g_object_ref0 (gtk_tree_view_get_selection (self->priv->tv_apps));
	model = NULL;
	is_active = (_tmp1_ = gtk_tree_selection_get_selected (sel, &_tmp0_, &iter), model = (_tmp2_ = _g_object_ref0 (_tmp0_), _g_object_unref0 (model), _tmp2_), _tmp1_);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->btn_edit_app, is_active);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->btn_remove_app, is_active);
	_g_object_unref0 (sel);
	_g_object_unref0 (model);
}


static void roxenlauncher_main_window_set_buttons_sensitivity (RoxenlauncherMainWindow* self) {
	GtkTreeSelection* sel;
	GtkTreeIter iter = {0};
	GtkTreeModel* model;
	GtkTreeModel* _tmp2_;
	gboolean _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean is_active;
	GeeArrayList* _tmp3_;
	g_return_if_fail (self != NULL);
	sel = _g_object_ref0 (gtk_tree_view_get_selection (self->priv->tv_files));
	model = NULL;
	is_active = (_tmp1_ = gtk_tree_selection_get_selected (sel, &_tmp0_, &iter), model = (_tmp2_ = _g_object_ref0 (_tmp0_), _g_object_unref0 (model), _tmp2_), _tmp1_);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->btn_edit_file, is_active);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->btn_finish_file, is_active);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->btn_finish_all, gee_collection_get_size ((GeeCollection*) (_tmp3_ = launcher_file_get_files ())) > 0);
	_g_object_unref0 (_tmp3_);
	_g_object_unref0 (sel);
	_g_object_unref0 (model);
}


static void roxenlauncher_main_window_finish_file (RoxenlauncherMainWindow* self) {
	GtkTreeModel* model;
	GtkTreeIter iter = {0};
	GtkTreeModel* _tmp2_;
	LauncherFile* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	LauncherFile* file;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (self != NULL);
	model = NULL;
	file = (_tmp1_ = roxenlauncher_main_window_get_selected_file (self, &_tmp0_, &iter), model = (_tmp2_ = _tmp0_, _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (file != NULL) {
		_tmp3_ = launcher_file_delete (file);
	} else {
		_tmp3_ = FALSE;
	}
	if (_tmp3_) {
		gtk_list_store_remove (self->priv->ls_files, &iter);
		launcher_file_remove_file (file);
	}
	roxenlauncher_main_window_set_file_count (self);
	roxenlauncher_main_window_set_buttons_sensitivity (self);
	_g_object_unref0 (model);
	_g_object_unref0 (file);
}


void roxenlauncher_main_window_finish_all_files (RoxenlauncherMainWindow* self) {
	g_return_if_fail (self != NULL);
	gtk_list_store_clear (self->priv->ls_files);
	{
		GeeArrayList* _tmp0_;
		GeeIterator* _tmp1_;
		GeeIterator* _lf_it;
		_lf_it = (_tmp1_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) (_tmp0_ = launcher_file_get_files ())), _g_object_unref0 (_tmp0_), _tmp1_);
		while (TRUE) {
			LauncherFile* lf;
			if (!gee_iterator_next (_lf_it)) {
				break;
			}
			lf = (LauncherFile*) gee_iterator_get (_lf_it);
			launcher_file_delete (lf);
			_g_object_unref0 (lf);
		}
		_g_object_unref0 (_lf_it);
	}
	launcher_file_clear_files ();
	roxenlauncher_main_window_set_buttons_sensitivity (self);
	roxenlauncher_main_window_set_file_count (self);
}


static void roxenlauncher_main_window_remove_application (RoxenlauncherMainWindow* self) {
	GtkTreeModel* model;
	GtkTreeIter iter = {0};
	GtkTreeModel* _tmp2_;
	RoxenlauncherApplication* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	RoxenlauncherApplication* app;
	g_return_if_fail (self != NULL);
	model = NULL;
	app = (_tmp1_ = roxenlauncher_main_window_get_selected_application (self, &_tmp0_, &iter), model = (_tmp2_ = _tmp0_, _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (app != NULL) {
		{
			GeeArrayList* _tmp3_;
			GeeIterator* _tmp4_;
			GeeIterator* _lf_it;
			_lf_it = (_tmp4_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) (_tmp3_ = launcher_file_get_files ())), _g_object_unref0 (_tmp3_), _tmp4_);
			while (TRUE) {
				LauncherFile* lf;
				if (!gee_iterator_next (_lf_it)) {
					break;
				}
				lf = (LauncherFile*) gee_iterator_get (_lf_it);
				if (_vala_strcmp0 (roxenlauncher_application_get_mimetype (launcher_file_get_application (lf)), roxenlauncher_application_get_mimetype (app)) == 0) {
					launcher_file_unset_application (lf);
				}
				_g_object_unref0 (lf);
			}
			_g_object_unref0 (_lf_it);
		}
		roxenlauncher_application_remove_application (app);
		gtk_list_store_remove (self->priv->ls_apps, &iter);
	}
	_g_object_unref0 (model);
	_g_object_unref0 (app);
}


static void roxenlauncher_main_window_begin_edit_file (RoxenlauncherMainWindow* self) {
	GtkTreeModel* a;
	GtkTreeIter b = {0};
	GtkTreeModel* _tmp2_;
	LauncherFile* _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	LauncherFile* lf;
	g_return_if_fail (self != NULL);
	a = NULL;
	lf = (_tmp1_ = roxenlauncher_main_window_get_selected_file (self, &_tmp0_, &b), a = (_tmp2_ = _tmp0_, _g_object_unref0 (a), _tmp2_), _tmp1_);
	if (lf != NULL) {
		launcher_file_download (lf, TRUE);
	}
	_g_object_unref0 (a);
	_g_object_unref0 (lf);
}


static LauncherFile* roxenlauncher_main_window_get_selected_file (RoxenlauncherMainWindow* self, GtkTreeModel** _model, GtkTreeIter* _iter) {
	LauncherFile* result;
	GtkTreeSelection* sel;
	GtkTreeIter iter = {0};
	GtkTreeModel* model;
	GtkTreeModel* _tmp2_;
	gboolean _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean has_sel;
	LauncherFile* lf;
	GtkTreeModel* _tmp3_;
	g_return_val_if_fail (self != NULL, NULL);
	if (_model != NULL) {
		*_model = NULL;
	}
	sel = _g_object_ref0 (gtk_tree_view_get_selection (self->priv->tv_files));
	model = NULL;
	has_sel = (_tmp1_ = gtk_tree_selection_get_selected (sel, &_tmp0_, &iter), model = (_tmp2_ = _g_object_ref0 (_tmp0_), _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (!has_sel) {
		result = NULL;
		_g_object_unref0 (sel);
		_g_object_unref0 (model);
		return result;
	}
	lf = NULL;
	gtk_tree_model_get (model, &iter, 3, &lf, -1, -1);
	if (lf == NULL) {
		result = NULL;
		_g_object_unref0 (sel);
		_g_object_unref0 (model);
		_g_object_unref0 (lf);
		return result;
	}
	*_model = (_tmp3_ = _g_object_ref0 (model), _g_object_unref0 (*_model), _tmp3_);
	*_iter = iter;
	result = lf;
	_g_object_unref0 (sel);
	_g_object_unref0 (model);
	return result;
}


static RoxenlauncherApplication* roxenlauncher_main_window_get_selected_application (RoxenlauncherMainWindow* self, GtkTreeModel** _model, GtkTreeIter* _iter) {
	RoxenlauncherApplication* result;
	GtkTreeSelection* sel;
	GtkTreeIter iter = {0};
	GtkTreeModel* model;
	GtkTreeModel* _tmp2_;
	gboolean _tmp1_;
	GtkTreeModel* _tmp0_ = NULL;
	gboolean has_sel;
	RoxenlauncherApplication* app;
	GtkTreeModel* _tmp3_;
	g_return_val_if_fail (self != NULL, NULL);
	if (_model != NULL) {
		*_model = NULL;
	}
	sel = _g_object_ref0 (gtk_tree_view_get_selection (self->priv->tv_apps));
	model = NULL;
	has_sel = (_tmp1_ = gtk_tree_selection_get_selected (sel, &_tmp0_, &iter), model = (_tmp2_ = _g_object_ref0 (_tmp0_), _g_object_unref0 (model), _tmp2_), _tmp1_);
	if (!has_sel) {
		result = NULL;
		_g_object_unref0 (sel);
		_g_object_unref0 (model);
		return result;
	}
	app = NULL;
	gtk_tree_model_get (model, &iter, 2, &app, -1, -1);
	if (app == NULL) {
		result = NULL;
		_g_object_unref0 (sel);
		_g_object_unref0 (model);
		_g_object_unref0 (app);
		return result;
	}
	*_model = (_tmp3_ = _g_object_ref0 (model), _g_object_unref0 (*_model), _tmp3_);
	*_iter = iter;
	result = app;
	_g_object_unref0 (sel);
	_g_object_unref0 (model);
	return result;
}


static void roxenlauncher_main_window_set_file_count (RoxenlauncherMainWindow* self) {
	char* m;
	GeeArrayList* _tmp0_;
	gint _tmp1_;
	gint num;
	char* _tmp5_;
	g_return_if_fail (self != NULL);
	m = g_strdup ("");
	num = (_tmp1_ = gee_collection_get_size ((GeeCollection*) (_tmp0_ = launcher_file_get_files ())), _g_object_unref0 (_tmp0_), _tmp1_);
	if (num == 0) {
		char* _tmp2_;
		m = (_tmp2_ = g_strdup (_ ("No files")), _g_free0 (m), _tmp2_);
	} else {
		if (num == 1) {
			char* _tmp3_;
			m = (_tmp3_ = g_strdup (_ ("One file")), _g_free0 (m), _tmp3_);
		} else {
			char* _tmp4_;
			m = (_tmp4_ = g_strdup_printf (_ ("%d active files"), (gint) num), _g_free0 (m), _tmp4_);
		}
	}
	roxenlauncher_main_window_set_status (self, _tmp5_ = g_strconcat ("# ", m, NULL));
	_g_free0 (_tmp5_);
	_g_free0 (m);
}


static void roxenlauncher_main_window_set_status (RoxenlauncherMainWindow* self, const char* text) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (text != NULL);
	gtk_statusbar_push (self->priv->statusbar, (guint) 0, text);
}


RoxenlauncherMainWindow* roxenlauncher_main_window_construct (GType object_type) {
	RoxenlauncherMainWindow * self;
	self = (RoxenlauncherMainWindow*) g_object_new (object_type, NULL);
	return self;
}


RoxenlauncherMainWindow* roxenlauncher_main_window_new (void) {
	return roxenlauncher_main_window_construct (ROXENLAUNCHER_TYPE_MAIN_WINDOW);
}


static void roxenlauncher_main_window_class_init (RoxenlauncherMainWindowClass * klass) {
	roxenlauncher_main_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (RoxenlauncherMainWindowPrivate));
	G_OBJECT_CLASS (klass)->finalize = roxenlauncher_main_window_finalize;
}


static void roxenlauncher_main_window_instance_init (RoxenlauncherMainWindow * self) {
	self->priv = ROXENLAUNCHER_MAIN_WINDOW_GET_PRIVATE (self);
}


static void roxenlauncher_main_window_finalize (GObject* obj) {
	RoxenlauncherMainWindow * self;
	self = ROXENLAUNCHER_MAIN_WINDOW (obj);
	_g_object_unref0 (self->priv->builder);
	_g_object_unref0 (self->priv->win);
	_g_object_unref0 (self->priv->sw_files);
	_g_object_unref0 (self->priv->cb_logging);
	_g_object_unref0 (self->priv->fc_logfile);
	_g_object_unref0 (self->priv->btn_edit_file);
	_g_object_unref0 (self->priv->btn_finish_file);
	_g_object_unref0 (self->priv->btn_finish_all);
	_g_object_unref0 (self->priv->btn_edit_app);
	_g_object_unref0 (self->priv->btn_add_app);
	_g_object_unref0 (self->priv->btn_remove_app);
	_g_object_unref0 (self->priv->tv_files);
	_g_object_unref0 (self->priv->tv_apps);
	_g_object_unref0 (self->priv->ls_files);
	_g_object_unref0 (self->priv->ls_apps);
	_g_object_unref0 (self->priv->statusbar);
	G_OBJECT_CLASS (roxenlauncher_main_window_parent_class)->finalize (obj);
}


GType roxenlauncher_main_window_get_type (void) {
	static GType roxenlauncher_main_window_type_id = 0;
	if (roxenlauncher_main_window_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (RoxenlauncherMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) roxenlauncher_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RoxenlauncherMainWindow), 0, (GInstanceInitFunc) roxenlauncher_main_window_instance_init, NULL };
		roxenlauncher_main_window_type_id = g_type_register_static (G_TYPE_OBJECT, "RoxenlauncherMainWindow", &g_define_type_info, 0);
	}
	return roxenlauncher_main_window_type_id;
}


RoxenlauncherAbout* roxenlauncher_about_construct (GType object_type) {
	RoxenlauncherAbout * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


RoxenlauncherAbout* roxenlauncher_about_new (void) {
	return roxenlauncher_about_construct (ROXENLAUNCHER_TYPE_ABOUT);
}


static GObject * roxenlauncher_about_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	RoxenlauncherAbout * self;
	GError * _inner_error_;
	parent_class = G_OBJECT_CLASS (roxenlauncher_about_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = ROXENLAUNCHER_ABOUT (obj);
	_inner_error_ = NULL;
	{
		GtkBuilder* builder;
		char* filename;
		GtkAboutDialog* d;
		char* about_logo;
		GtkAboutDialog* _tmp2_;
		GtkBuilder* _tmp3_;
		builder = gtk_builder_new ();
		filename = roxenlauncher_get_ui_path (ROXENLAUNCHER_APP_MAIN_UI_FILENAME);
		if (filename == NULL) {
			g_error ("mainwindow.vala:690: Unable to load GUI for about dialog");
		}
		{
			gtk_builder_set_translation_domain (builder, GETTEXT_PACKAGE);
			gtk_builder_add_from_file (builder, filename, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch27_g_error;
				goto __finally27;
			}
		}
		goto __finally27;
		__catch27_g_error:
		{
			GError * e;
			e = _inner_error_;
			_inner_error_ = NULL;
			{
				g_error ("mainwindow.vala:697: GUI load error: %s", e->message);
				_g_error_free0 (e);
			}
		}
		__finally27:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (builder);
			_g_free0 (filename);
			g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
			g_clear_error (&_inner_error_);
		}
		d = _g_object_ref0 (GTK_ABOUT_DIALOG (gtk_builder_get_object (builder, "aboutdialog")));
		about_logo = roxenlauncher_get_ui_path ("pixmap/roxen-logo.png");
		if (about_logo != NULL) {
			{
				GdkPixbuf* _tmp0_;
				GdkPixbuf* _tmp1_;
				_tmp0_ = gdk_pixbuf_new_from_file (about_logo, &_inner_error_);
				if (_inner_error_ != NULL) {
					goto __catch28_g_error;
					goto __finally28;
				}
				gtk_about_dialog_set_logo (d, _tmp1_ = _tmp0_);
				_g_object_unref0 (_tmp1_);
			}
			goto __finally28;
			__catch28_g_error:
			{
				GError * e;
				e = _inner_error_;
				_inner_error_ = NULL;
				{
					g_warning ("mainwindow.vala:707: Unable to set logo for about dialog: %s", e->message);
					_g_error_free0 (e);
				}
			}
			__finally28:
			if (_inner_error_ != NULL) {
				_g_object_unref0 (builder);
				_g_free0 (filename);
				_g_object_unref0 (d);
				_g_free0 (about_logo);
				g_critical ("file %s: line %d: uncaught error: %s", __FILE__, __LINE__, _inner_error_->message);
				g_clear_error (&_inner_error_);
			}
		}
		gtk_about_dialog_set_program_name (d, _ ("Roxen™ Application Launcher"));
		gtk_about_dialog_set_version (d, VERSION);
		gtk_dialog_run ((GtkDialog*) d);
		gtk_object_destroy ((GtkObject*) d);
		d = (_tmp2_ = NULL, _g_object_unref0 (d), _tmp2_);
		builder = (_tmp3_ = NULL, _g_object_unref0 (builder), _tmp3_);
		_g_object_unref0 (builder);
		_g_free0 (filename);
		_g_object_unref0 (d);
		_g_free0 (about_logo);
	}
	return obj;
}


static void roxenlauncher_about_class_init (RoxenlauncherAboutClass * klass) {
	roxenlauncher_about_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = roxenlauncher_about_constructor;
}


static void roxenlauncher_about_instance_init (RoxenlauncherAbout * self) {
}


GType roxenlauncher_about_get_type (void) {
	static GType roxenlauncher_about_type_id = 0;
	if (roxenlauncher_about_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (RoxenlauncherAboutClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) roxenlauncher_about_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RoxenlauncherAbout), 0, (GInstanceInitFunc) roxenlauncher_about_instance_init, NULL };
		roxenlauncher_about_type_id = g_type_register_static (G_TYPE_OBJECT, "RoxenlauncherAbout", &g_define_type_info, 0);
	}
	return roxenlauncher_about_type_id;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




